Chronos: Chronos::Engine::Texture Class Reference
Chronos::Engine::Texture Class Reference
This class holds the Vulkan data and objects needed for a texture.
#include <texture.hpp>
Public Member Functions
void create (Chronos::Engine::Device device, VkCommandPool commandPool, std::string texturePath, std::string textureName)
Create the texture by loading the texture from the given path. Only supports jpg and png images.
void create (Chronos::Engine::Device device, VkCommandPool commandPool, void *data, size_t texWidth, size_t texHeight, VkDeviceSize imageSize, VkFormat format, std::string textureName)
Create the texture by loading the texture from the given raw data.
void destroy ()
Destroy the texture assets.
Public Attributes
VkDeviceMemory textureImageMemory
The memory for the texture.
VkImage textureImage
The image for the texture.
VkImageView textureImageView
The image view for the texture.
std::string texturePath
The path of the texture that it was loaded from.
std::string textureName
The name of the texture.
int height
int width
Private Attributes
Chronos::Engine::Device device
The device that has the texture.
Detailed Description
This class holds the Vulkan data and objects needed for a texture.
The items needed for creating a texture that are stored in this class are:
VkDeviceMemory for the texture memory
VkImage for the texture
VkImageView for the texture image view
Definition at line 112 of file texture.hpp.
Member Function Documentation
create() [1/2]
void Chronos::Engine::Texture::create (Chronos::Engine::Device device, VkCommandPool commandPool, std::string texturePath, std::string textureName)
Create the texture by loading the texture from the given path. Only supports jpg and png images.
Parameters
device The device that has the texture.
commandPool The command pool to create the temporary command buffer from.
texturePath The path to the texture(only jpg or png).
textureName The name of the texture(must be unique).
Definition at line 86 of file texture.cpp.
 {
     this->texturePath = texturePath;
     this->textureName = textureName;
     int texWidth = 0, texHeight = 0, texChannels = 0;
     this->device = device;
     VkDeviceSize imageSize;
     uint8_t* pixels;
     if (texturePath.ends_with(".png") || texturePath.ends_with(".jpg")) {
         pixels = stbi_load(texturePath.c_str(), &texWidth, &texHeight, &texChannels,
             STBI_rgb_alpha);
         imageSize = texWidth * texHeight * 4;
         this->width = texWidth;
         this->height = texHeight;
         if (!pixels) {
             throw std::runtime_error("failed to load texture image " + texturePath);
         }
     } else {
         throw std::runtime_error("unsupported texture format " + texturePath);
     }
     VkBuffer stagingBuffer;
     VkDeviceMemory stagingBufferMemory;
     Chronos::Engine::createBuffer(device, imageSize, VK_BUFFER_USAGE_TRANSFER_SRC_BIT,
         VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT | VK_MEMORY_PROPERTY_HOST_COHERENT_BIT,
         &stagingBuffer, &stagingBufferMemory);
     void* data;
     vkMapMemory(device.device, stagingBufferMemory, 0, imageSize, 0, &data);
     memcpy(data, pixels, static_cast<size_t>(imageSize));
     vkUnmapMemory(device.device, stagingBufferMemory);
     stbi_image_free(pixels);
     Chronos::Engine::createImage(device, texWidth, texHeight, VK_FORMAT_R8G8B8A8_SRGB,
         VK_IMAGE_TILING_OPTIMAL,
         VK_IMAGE_USAGE_TRANSFER_DST_BIT | VK_IMAGE_USAGE_SAMPLED_BIT,
         VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT, &textureImage,
         &textureImageMemory, VK_SAMPLE_COUNT_1_BIT);
     Chronos::Engine::transitionImageLayout(
         textureImage, VK_IMAGE_LAYOUT_UNDEFINED,
         VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL, commandPool, device);
     Chronos::Engine::copyBufferToImage(stagingBuffer, textureImage,
         static_cast<uint32_t>(texWidth),
         static_cast<uint32_t>(texHeight), commandPool, device);
     Chronos::Engine::transitionImageLayout(textureImage,
         VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL,
         VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL, commandPool,
         device);
     vkDestroyBuffer(device.device, stagingBuffer, nullptr);
     vkFreeMemory(device.device, stagingBufferMemory, nullptr);
     textureImageView = createImageView(device, VK_FORMAT_R8G8B8A8_SRGB, textureImage);
 #ifdef ENABLE_EDITOR
     Chronos::Engine::createTextureSampler(device, &textureSampler);
     descriptorSet = ImGui_ImplVulkan_AddTexture(textureSampler, textureImageView,
         VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL);
 #endif
 }
References Chronos::Engine::copyBufferToImage(), Chronos::Engine::createBuffer(), Chronos::Engine::createImage(), Chronos::Engine::createImageView(), Chronos::Engine::createTextureSampler(), Chronos::Engine::Device::device, device, height, textureImage, textureImageMemory, textureImageView, textureName, texturePath, Chronos::Engine::transitionImageLayout(), and width.
create() [2/2]
void Chronos::Engine::Texture::create (Chronos::Engine::Device device, VkCommandPool commandPool, void * data, size_t texWidth, size_t texHeight, VkDeviceSize imageSize, VkFormat format, std::string textureName)
Create the texture by loading the texture from the given raw data.
Used in Text Rendering
Parameters
device The device that has the texture.
commandPool The command pool to create the temporary command buffer from.
data The raw data of the texture.
texWidth The width of the texture.
texHeight The height of the texture.
imageSize The size of the image.
format The format of the image.
textureName The name of the texture(must be unique).
Definition at line 149 of file texture.cpp.
 {
     this->textureName = textureName;
     this->texturePath = "NA";
     this->device = device;
     VkBuffer stagingBuffer;
     VkDeviceMemory stagingBufferMemory;
     Chronos::Engine::createBuffer(device, imageSize, VK_BUFFER_USAGE_TRANSFER_SRC_BIT,
         VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT | VK_MEMORY_PROPERTY_HOST_COHERENT_BIT,
         &stagingBuffer, &stagingBufferMemory);
     void* mappedData;
     vkMapMemory(device.device, stagingBufferMemory, 0, imageSize, 0, &mappedData);
     memcpy(mappedData, data, static_cast<size_t>(imageSize));
     vkUnmapMemory(device.device, stagingBufferMemory);
     Chronos::Engine::createImage(device, texWidth, texHeight, format,
         VK_IMAGE_TILING_OPTIMAL,
         VK_IMAGE_USAGE_TRANSFER_DST_BIT | VK_IMAGE_USAGE_SAMPLED_BIT,
         VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT, &textureImage,
         &textureImageMemory, VK_SAMPLE_COUNT_1_BIT);
     Chronos::Engine::transitionImageLayout(
         textureImage, VK_IMAGE_LAYOUT_UNDEFINED,
         VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL, commandPool, device);
     Chronos::Engine::copyBufferToImage(stagingBuffer, textureImage,
         static_cast<uint32_t>(texWidth),
         static_cast<uint32_t>(texHeight), commandPool, device);
     Chronos::Engine::transitionImageLayout(textureImage,
         VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL,
         VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL, commandPool,
         device);
     vkDestroyBuffer(device.device, stagingBuffer, nullptr);
     vkFreeMemory(device.device, stagingBufferMemory, nullptr);
     textureImageView = createImageView(device, format, textureImage);
 }
References Chronos::Engine::copyBufferToImage(), Chronos::Engine::createBuffer(), Chronos::Engine::createImage(), Chronos::Engine::createImageView(), Chronos::Engine::Device::device, and Chronos::Engine::transitionImageLayout().
destroy()
void Chronos::Engine::Texture::destroy ()
Destroy the texture assets.
Definition at line 295 of file texture.cpp.
 {
     vkDestroyImageView(device.device, textureImageView, nullptr);
     vkDestroyImage(device.device, textureImage, nullptr);
     vkFreeMemory(device.device, textureImageMemory, nullptr);
 }
Member Data Documentation
device
Chronos::Engine::Device Chronos::Engine::Texture::device private
The device that has the texture.
Definition at line 184 of file texture.hpp.
height
int Chronos::Engine::Texture::height
Definition at line 173 of file texture.hpp.
textureImage
VkImage Chronos::Engine::Texture::textureImage
The image for the texture.
Definition at line 122 of file texture.hpp.
textureImageMemory
VkDeviceMemory Chronos::Engine::Texture::textureImageMemory
The memory for the texture.
Definition at line 117 of file texture.hpp.
textureImageView
VkImageView Chronos::Engine::Texture::textureImageView
The image view for the texture.
Definition at line 127 of file texture.hpp.
textureName
std::string Chronos::Engine::Texture::textureName
The name of the texture.
Definition at line 171 of file texture.hpp.
texturePath
std::string Chronos::Engine::Texture::texturePath
The path of the texture that it was loaded from.
Definition at line 166 of file texture.hpp.
width
int Chronos::Engine::Texture::width
Definition at line 174 of file texture.hpp.
The documentation for this class was generated from the following files:
Source/Engine/Headers/texture.hpp
Source/Engine/Source/texture.cpp