Chronos: Chronos::Engine::ShapeManager Class Reference
Chronos::Engine::ShapeManager Class Reference
This is the shape manager for Chronos. It handles creation, modification, updating and desrtuction of shapes.
#include <shapeManager.hpp>
Public Member Functions
int addTriangle (Chronos::Engine::ShapeParams shapeParams, std::string texturePath)
Adds a triangle to the shape manager.
int addRectangle (Chronos::Engine::ShapeParams shapeParams, std::string texturePath)
Adds a rectangle to the shape manager.
void render (uint32_t currentFrame, uint32_t imageIndex, float bgColor[3])
Records the commands needed for rendering the shapes.
Public Member Functions inherited from Chronos::Engine::ObjectManager< Chronos::Engine::Shape >
void remove (int objectNo)
void init (Chronos::Engine::Device *device, Chronos::Engine::SwapChain *swapChain, VkCommandPool commandPool)
void destroy ()
void update (uint32_t currentFrame)
void changeMsaa ()
void recreate ()
Private Member Functions
void createRenderPass ()
Creates the render pass for the shapes.
Additional Inherited Members
Public Attributes inherited from Chronos::Engine::ObjectManager< Chronos::Engine::Shape >
int nextFreeObjectNo
std::map< int, Object > objects
std::vector< VkCommandBuffer > commandBuffers
Protected Member Functions inherited from Chronos::Engine::ObjectManager< Chronos::Engine::Shape >
void endRender (uint32_t currentFrame)
int addObject (Object object)
void cleanup ()
Protected Attributes inherited from Chronos::Engine::ObjectManager< Chronos::Engine::Shape >
Chronos::Engine::Device * device
Chronos::Engine::SwapChain * swapChain
VkCommandPool commandPool
VkRenderPass renderPass
VkSampler textureSampler
std::vector< VkFramebuffer > framebuffers
Detailed Description
This is the shape manager for Chronos. It handles creation, modification, updating and desrtuction of shapes.
This is for use by Engine only and should not be used for any other purpose. Code using Chronos should not use this class directly.
Generally in order to manage shapes the methods to be used are:
addTriangle
addRectangle
`remove
Inherits from Object Manager. All the public methods defined in that class is also available. It includes the following functions for internal use -init -destroy -update -render -changeMsaa -recreate
For more details on these functions, please reference the [ObjectManger](Chronos::Engine::ObjectManager) class
Definition at line 35 of file shapeManager.hpp.
Member Function Documentation
addRectangle()
int Chronos::Engine::ShapeManager::addRectangle (Chronos::Engine::ShapeParams shapeParams, std::string texturePath)
Adds a rectangle to the shape manager.
Necessary shapeParams and texture path must be provided. Supported textures are .jpg and .png Returns a shapeNo that references the shape for modifying and destroying t.
Definition at line 46 of file shapeManager.cpp.
 {
     int shapeNo = Chronos::Engine::ObjectManager<Chronos::Engine::Shape>::addObject(Rectangle());
     objects[shapeNo].init(device, commandPool, swapChain, textureSampler,
         texturePath, &renderPass);
     objects[shapeNo].params = shapeParams;
     return shapeNo;
 }
References Chronos::Engine::ObjectManager< Object >::addObject().
addTriangle()
int Chronos::Engine::ShapeManager::addTriangle (Chronos::Engine::ShapeParams shapeParams, std::string texturePath)
Adds a triangle to the shape manager.
Necessary shapeParams and texture path must be provided. Supported textures are .jpg and .png Returns a shapeNo that references the shape for modifying and destroying t.
Definition at line 56 of file shapeManager.cpp.
 {
     int shapeNo = Chronos::Engine::ObjectManager<Chronos::Engine::Shape>::addObject(Triangle());
     objects[shapeNo].init(device, commandPool, swapChain, textureSampler,
         texturePath, &renderPass);
     objects[shapeNo].params = shapeParams;
     return shapeNo;
 }
References Chronos::Engine::ObjectManager< Object >::addObject().
createRenderPass()
void Chronos::Engine::ShapeManager::createRenderPass () private virtual
Creates the render pass for the shapes.
This function is called by the init function. It creates the render pass for the shapes.
Implements Chronos::Engine::ObjectManager< Chronos::Engine::Shape >.
Definition at line 66 of file shapeManager.cpp.
{
      /*
     For the render pass the formats are as follows:
             initial - undefined; this is due to the fact that image is cleared
             final(color and msaa) - color attachment optimal; this is due to the
     fact that the image going to next renderpass(Text) Also we are clearing the
     framebuffer
     */
     renderPass = Chronos::Engine::createRenderPass(*device, *swapChain, VK_IMAGE_LAYOUT_UNDEFINED,
         VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL,
         VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL, true,
         true, false);
 }
References Chronos::Engine::createRenderPass().
render()
void Chronos::Engine::ShapeManager::render (uint32_t currentFrame, uint32_t imageIndex, float bgColor[3]) virtual
Records the commands needed for rendering the shapes.
When this function is called, it records the commands that are needed for rendering all the shapes stored in this class.
Parameters
currentFrame The current frame to render to.
imageIndex The index of the framebuffer associated with the current frame
bgColor The background color to set during rendering
Reimplemented from Chronos::Engine::ObjectManager< Chronos::Engine::Shape >.
Definition at line 7 of file shapeManager.cpp.
 {
     Chronos::Engine::ObjectManager<Chronos::Engine::Shape>::render(currentFrame, imageIndex, bgColor);
     VkViewport viewport {};
     viewport.x = 0.0f;
     viewport.y = 0.0f;
     viewport.width = static_cast<float>(swapChain->swapChainExtent.width);
     viewport.height = static_cast<float>(swapChain->swapChainExtent.height);
     viewport.minDepth = 0.0f;
     viewport.maxDepth = 1.0f;
     VkRect2D scissor {};
     scissor.offset = { 0, 0 };
     scissor.extent = swapChain->swapChainExtent;
     // render the shapes
     for (auto& shape : objects) {
         vkCmdBindPipeline(commandBuffers[currentFrame],
             VK_PIPELINE_BIND_POINT_GRAPHICS, shape.second.graphicsPipeline);
         vkCmdSetViewport(commandBuffers[currentFrame], 0, 1, &viewport);
         vkCmdSetScissor(commandBuffers[currentFrame], 0, 1, &scissor);
         VkBuffer vertexBuffers[] = { shape.second.vertexBuffer.buffer };
         VkDeviceSize offsets[] = { 0 };
         vkCmdBindVertexBuffers(commandBuffers[currentFrame], 0, 1, vertexBuffers,
             offsets);
         vkCmdBindIndexBuffer(commandBuffers[currentFrame], shape.second.indexBuffer.buffer,
             0, VK_INDEX_TYPE_UINT16);
         vkCmdBindDescriptorSets(commandBuffers[currentFrame],
             VK_PIPELINE_BIND_POINT_GRAPHICS,
             shape.second.pipelineLayout, 0, 1,
             &shape.second.descriptorSets[currentFrame], 0, nullptr);
         vkCmdDrawIndexed(commandBuffers[currentFrame],
             static_cast<uint32_t>(shape.second.indices.size()), 1, 0, 0, 0);
     }
     endRender(currentFrame);
 }
References Chronos::Engine::ObjectManager< Chronos::Engine::Shape >::commandBuffers, Chronos::Engine::ObjectManager< Chronos::Engine::Shape >::endRender(), Chronos::Engine::ObjectManager< Chronos::Engine::Shape >::objects, Chronos::Engine::ObjectManager< Object >::render(), Chronos::Engine::ObjectManager< Chronos::Engine::Shape >::swapChain, and Chronos::Engine::SwapChain::swapChainExtent.
The documentation for this class was generated from the following files:
Source/Engine/Headers/shapeManager.hpp
Source/Engine/Source/shapeManager.cpp