Chronos: Chronos::Engine::Font Class Reference
Chronos::Engine::Font Class Reference
Class for creating a font object for rendering text.
#include <font.hpp>
Public Member Functions
void init (Chronos::Engine::Device *device, VkCommandPool commandPool, Chronos::Engine::SwapChain *swapChain, VkSampler textureSampler, VkRenderPass *renderPass)
Initializes the font object and creates the necessary objects.
void destroy ()
Destroys the font object and frees the memory.
void clear ()
Clears the text stored in the font object.
void render (uint32_t currentFrame, uint32_t imageIndex, float bgColor[3])
Records the commands needed for rendering the text .
void update (uint32_t currentFrame)
Updates the attributes(like position, color, etc) of the text.
Public Member Functions inherited from Chronos::Engine::Object
void recreateGraphicsPipeline ()
Recreates the graphics pipeline for the object.
Public Attributes
VkBuffer vertexBuffer
The vertices of each character used for rendering.
uint32_t numLetters
The total number of letters to render.
Chronos::Engine::TextParams params
Various parameters of the text that are set by the user.
Public Attributes inherited from Chronos::Engine::Object
VkPipeline graphicsPipeline
VkPipelineLayout pipelineLayout
std::vector< VkDescriptorSet > descriptorSets
Private Member Functions
void createDescriptorSets ()
Creates the descriptor sets needed for rendering the text.
std::vector< VkDescriptorType > getDescriptorTypes ()
Gets the descriptor types needed for rendering the text.
std::vector< VkShaderStageFlagBits > getDescriptorStages ()
Gets the descriptor stages in which the descriptor sets are used.
PipelineAttributes getPipelineAttributes ()
Returns the pipeline attributes that are set for the graphics pipeline.
void updateBuffer ()
Updates the buffer with the new text.
Private Attributes
uint32_t maxTextLength = 2048
Maximum number of characters that can be rendered.
stb_fontchar stbFontData [STB_FONT_consolas_24_latin1_NUM_CHARS]
The texture atlas that contains all the characters in the font.
VkDeviceMemory vertexBufferMemory
The vertex buffer memory.
Chronos::Engine::Texture fontTexture
glm::vec4 * mappedMemory
Additional Inherited Members
Protected Member Functions inherited from Chronos::Engine::Object
void createGraphicsPipeline ()
Creates the graphics pipeline for the object.
void createDescriptorPool ()
Creates the Vulkan descriptor pool for the object.
void createDescriptorSetLayout ()
Creates the Vulkan descriptor set layout for the object.
Protected Attributes inherited from Chronos::Engine::Object
std::string vertexShaderPath
std::string fragmentShaderPath
Chronos::Engine::Device * device
Chronos::Engine::SwapChain * swapChain
VkCommandPool commandPool
VkSampler textureSampler
VkRenderPass * renderPass
VkDescriptorSetLayout descriptorSetLayout
VkDescriptorPool descriptorPool
std::vector< Chronos::Engine::UniformBuffer > uniformBuffers
Detailed Description
Class for creating a font object for rendering text.
For rendering text in vulkan, we need a bunch of setup and objects. It is also a very complex process. This class handles this process and abstracts this complex process into a simple class with simple methods that can be used for rendering text.
The way the test is rendered is by creating a texture atlas. This is a texture that contains all the characters in the font. This texture is then used to render the text. The text is rendered by creating a rectangle for each character and then rendering it.
This class is not meant to be directly used, but instead to be used by the FontManager class. That will handle the creation and destruction of the font object, along with any updates needed.
Definition at line 22 of file font.hpp.
Member Function Documentation
clear()
void Chronos::Engine::Font::clear ()
Clears the text stored in the font object.
Used for resetting the text stored in the font object.
Definition at line 216 of file font.cpp.
{
     if (vkMapMemory(device->device, vertexBufferMemory, 0, VK_WHOLE_SIZE, 0,
             (void**)&mappedMemory)
         != VK_SUCCESS) {
         throw std::runtime_error("failed to map memory!");
     }
     numLetters = 0;
     mappedMemory = nullptr;
     vkUnmapMemory(device->device, vertexBufferMemory);
     mappedMemory = nullptr;
 }
createDescriptorSets()
void Chronos::Engine::Font::createDescriptorSets () private virtual
Creates the descriptor sets needed for rendering the text.
This function is used to create the descriptor sets needed for rendering the text. The descriptor sets contain information about the texture sampler and the uniform buffer.
Implements Chronos::Engine::Object.
Definition at line 43 of file font.cpp.
{
     std::vector<VkDescriptorSetLayout> layouts(MAX_FRAMES_IN_FLIGHT,
         descriptorSetLayout);
     VkDescriptorSetAllocateInfo allocInfo {};
     allocInfo.sType = VK_STRUCTURE_TYPE_DESCRIPTOR_SET_ALLOCATE_INFO;
     allocInfo.descriptorPool = descriptorPool;
     allocInfo.descriptorSetCount = static_cast<uint32_t>(MAX_FRAMES_IN_FLIGHT);
     allocInfo.pSetLayouts = layouts.data();
     descriptorSets.resize(MAX_FRAMES_IN_FLIGHT);
     if (vkAllocateDescriptorSets(device->device, &allocInfo,
             descriptorSets.data())
         != VK_SUCCESS) {
         throw std::runtime_error("failed to allocate descriptor sets!");
     }
     for (size_t i = 0; i < MAX_FRAMES_IN_FLIGHT; i++) {
         VkDescriptorImageInfo imageInfo {};
         imageInfo.imageLayout = VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL;
         imageInfo.imageView = fontTexture.textureImageView;
         imageInfo.sampler = textureSampler;
         VkDescriptorBufferInfo bufferInfo {};
         bufferInfo.buffer = uniformBuffers[i].buffer;
         bufferInfo.offset = 0;
         bufferInfo.range = sizeof(UniformBufferObject);
         VkWriteDescriptorSet descriptorWrite {};
         std::array<VkWriteDescriptorSet, 2> descriptorWrites {};
         descriptorWrites[0].sType = VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET;
         descriptorWrites[0].dstSet = descriptorSets[i];
         descriptorWrites[0].dstBinding = 0;
         descriptorWrites[0].dstArrayElement = 0;
         descriptorWrites[0].descriptorType = VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER;
         descriptorWrites[0].descriptorCount = 1;
         descriptorWrites[0].pImageInfo = &imageInfo;
         descriptorWrites[1].sType = VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET;
         descriptorWrites[1].dstSet = descriptorSets[i];
         descriptorWrites[1].dstBinding = 1;
         descriptorWrites[1].dstArrayElement = 0;
         descriptorWrites[1].descriptorType = VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER;
         descriptorWrites[1].descriptorCount = 1;
         descriptorWrites[1].pBufferInfo = &bufferInfo;
         vkUpdateDescriptorSets(device->device,
             static_cast<uint32_t>(descriptorWrites.size()),
             descriptorWrites.data(), 0, nullptr);
     }
 };
References MAX_FRAMES_IN_FLIGHT.
destroy()
void Chronos::Engine::Font::destroy () virtual
Destroys the font object and frees the memory.
This destroys all the vulkan related objects related to this class and frees memory.
Implements Chronos::Engine::Object.
Definition at line 133 of file font.cpp.
{
     Chronos::Engine::Object::destroy();
     vkDestroyBuffer(device->device, vertexBuffer, nullptr);
     vkFreeMemory(device->device, vertexBufferMemory, nullptr);
     fontTexture.destroy();
 }
References Chronos::Engine::Object::destroy().
getDescriptorStages()
std::vector< VkShaderStageFlagBits > Chronos::Engine::Font::getDescriptorStages () private virtual
Gets the descriptor stages in which the descriptor sets are used.
Implements Chronos::Engine::Object.
Definition at line 37 of file font.cpp.
 {
     return std::vector<VkShaderStageFlagBits> {VK_SHADER_STAGE_FRAGMENT_BIT,
         VK_SHADER_STAGE_VERTEX_BIT};
 }
getDescriptorTypes()
std::vector< VkDescriptorType > Chronos::Engine::Font::getDescriptorTypes () private virtual
Gets the descriptor types needed for rendering the text.
Implements Chronos::Engine::Object.
Definition at line 31 of file font.cpp.
 {
     return std::vector<VkDescriptorType> {VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER,
         VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER };
 }
getPipelineAttributes()
Chronos::Engine::PipelineAttributes Chronos::Engine::Font::getPipelineAttributes () private virtual
Returns the pipeline attributes that are set for the graphics pipeline.
Implements Chronos::Engine::Object.
Definition at line 95 of file font.cpp.
 {
     PipelineAttributes pipelineAttributes;
     pipelineAttributes.bindingDescriptions = std::vector<VkVertexInputBindingDescription> {2};
     pipelineAttributes.bindingDescriptions[0].binding = 0;
     pipelineAttributes.bindingDescriptions[0].stride = sizeof(glm::vec4);
     pipelineAttributes.bindingDescriptions[0].inputRate = VK_VERTEX_INPUT_RATE_VERTEX;
     pipelineAttributes.bindingDescriptions[1].binding = 1;
     pipelineAttributes.bindingDescriptions[1].stride = sizeof(glm::vec4);
     pipelineAttributes.bindingDescriptions[1].inputRate = VK_VERTEX_INPUT_RATE_VERTEX;
     pipelineAttributes.attributeDescriptions = std::vector<VkVertexInputAttributeDescription> {2};
     pipelineAttributes.attributeDescriptions[0].binding = 0;
     pipelineAttributes.attributeDescriptions[0].location = 0;
     pipelineAttributes.attributeDescriptions[0].format = VK_FORMAT_R32G32_SFLOAT;
     pipelineAttributes.attributeDescriptions[0].offset = 0;
     pipelineAttributes.attributeDescriptions[1].binding = 1;
     pipelineAttributes.attributeDescriptions[1].location = 1;
     pipelineAttributes.attributeDescriptions[1].format = VK_FORMAT_R32G32_SFLOAT;
     pipelineAttributes.attributeDescriptions[1].offset = sizeof(glm::vec2);
     pipelineAttributes.topology = VK_PRIMITIVE_TOPOLOGY_TRIANGLE_STRIP;
     pipelineAttributes.frontFace = VK_FRONT_FACE_CLOCKWISE;
     pipelineAttributes.colorBlendAttachment.blendEnable = VK_TRUE;
     pipelineAttributes.colorBlendAttachment.colorWriteMask = VK_COLOR_COMPONENT_R_BIT | VK_COLOR_COMPONENT_G_BIT | VK_COLOR_COMPONENT_B_BIT | VK_COLOR_COMPONENT_A_BIT;
     pipelineAttributes.colorBlendAttachment.srcColorBlendFactor = VK_BLEND_FACTOR_SRC_ALPHA;
     pipelineAttributes.colorBlendAttachment.dstColorBlendFactor = VK_BLEND_FACTOR_ONE_MINUS_SRC_ALPHA;
     pipelineAttributes.colorBlendAttachment.colorBlendOp = VK_BLEND_OP_ADD;
     pipelineAttributes.colorBlendAttachment.srcAlphaBlendFactor = VK_BLEND_FACTOR_ONE_MINUS_SRC_ALPHA;
     pipelineAttributes.colorBlendAttachment.dstAlphaBlendFactor = VK_BLEND_FACTOR_ZERO;
     pipelineAttributes.colorBlendAttachment.alphaBlendOp = VK_BLEND_OP_ADD;
     return pipelineAttributes;
 }
References Chronos::Engine::PipelineAttributes::attributeDescriptions, Chronos::Engine::PipelineAttributes::bindingDescriptions, Chronos::Engine::PipelineAttributes::colorBlendAttachment, Chronos::Engine::PipelineAttributes::frontFace, and Chronos::Engine::PipelineAttributes::topology.
init()
void Chronos::Engine::Font::init (Chronos::Engine::Device * device, VkCommandPool commandPool, Chronos::Engine::SwapChain * swapChain, VkSampler textureSampler, VkRenderPass * renderPass) virtual
Initializes the font object and creates the necessary objects.
Parameters
device The device to use for creating the objects.
commandPool The command pool to use for rendering
swapChain The swapchain to use for rendering
textureSampler The texture sampler to use for fonts
renderPass The renderpass to use for rendering
Reimplemented from Chronos::Engine::Object.
Definition at line 4 of file font.cpp.
{
     vertexShaderPath = "ThirdParty/Chronos/Shaders/textVert.spv";
     fragmentShaderPath = "ThirdParty/Chronos/Shaders/textFrag.spv";
     // initalize the font
     const uint32_t fontWidth = STB_FONT_consolas_24_latin1_BITMAP_WIDTH;
     const uint32_t fontHeight = STB_FONT_consolas_24_latin1_BITMAP_HEIGHT;
     static unsigned char fontpixels[fontHeight][fontWidth];
     stb_font_consolas_24_latin1(stbFontData, fontpixels, fontHeight);
     fontTexture.create(*device, commandPool, (void*)&fontpixels[0][0], static_cast<size_t>(fontWidth),
      static_cast<size_t>(fontHeight), static_cast<VkDeviceSize>(fontWidth*fontHeight), VK_FORMAT_R8_UNORM);
     // create the vertex buffer
     VkDeviceSize bufferSize = maxTextLength * sizeof(glm::vec4);
     Chronos::Engine::createBuffer(*device, bufferSize, VK_BUFFER_USAGE_VERTEX_BUFFER_BIT,
         VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT | VK_MEMORY_PROPERTY_HOST_COHERENT_BIT,
         &vertexBuffer, &vertexBufferMemory);
     Chronos::Engine::Object::init(device, commandPool, swapChain, textureSampler, renderPass);
 }
References Chronos::Engine::Object::commandPool, Chronos::Engine::Texture::create(), Chronos::Engine::createBuffer(), Chronos::Engine::Object::device, fontTexture, Chronos::Engine::Object::fragmentShaderPath, Chronos::Engine::Object::init(), maxTextLength, Chronos::Engine::Object::renderPass, stbFontData, Chronos::Engine::Object::swapChain, Chronos::Engine::Object::textureSampler, vertexBuffer, vertexBufferMemory, and Chronos::Engine::Object::vertexShaderPath.
render()
void Chronos::Engine::Font::render (uint32_t currentFrame, uint32_t imageIndex, float bgColor[3])
Records the commands needed for rendering the text .
When this function is called, it records the commands that are needed for rendering the text stored in this class.
Parameters
currentFrame The current frame number to render to.
imageIndex The index of the framebuffer associated with the current frame
bgColor The background color to use for rendering the text.
update()
void Chronos::Engine::Font::update (uint32_t currentFrame) virtual
Updates the attributes(like position, color, etc) of the text.
This function is used to update the attributes of the text. It is called by the FontManager class. It does this by updating the uniform buffer.
Implements Chronos::Engine::Object.
Definition at line 229 of file font.cpp.
{
     updateBuffer();
     uniformBuffers[currentFrame].update(swapChain->swapChainExtent, params.x, params.y, params.rotation - 90, 1.0f, -1.0f);
 }
updateBuffer()
void Chronos::Engine::Font::updateBuffer () private
Updates the buffer with the new text.
Definition at line 141 of file font.cpp.
{
 if (vkMapMemory(device->device, vertexBufferMemory, 0, VK_WHOLE_SIZE, 0,
             (void**)&mappedMemory)
         != VK_SUCCESS) {
         throw std::runtime_error("failed to map memory!");
     }
         numLetters = 0;
     const uint32_t firstChar = STB_FONT_consolas_24_latin1_FIRST_CHAR;
     assert(mappedMemory != nullptr);
     const float charW = 1.5f * params.scale / swapChain->swapChainExtent.width;
     const float charH = 1.5f * params.scale / swapChain->swapChainExtent.height;
     float fbW = (float)swapChain->swapChainExtent.width;
     float fbH = (float)swapChain->swapChainExtent.height;
     float x = (0 / fbW * 2.0f);
     float y = (0 / fbH * 2.0f);
     // Calculate text width
     float textWidth = 0;
     for (auto letter : params.text) {
         stb_fontchar* charData = &stbFontData[(uint32_t)letter - firstChar];
         textWidth += charData->advance * charW;
     }
     // switch (alignment) {
     // case Right:
     //     x -= textWidth;
     //     break;
     // case Center:
         x -= textWidth / 2.0f;
     //     break;
     // case Left:
     //     break;
     // }
     // Generate a uv mapped quad per char in the new text
     for (auto letter : params.text) {
         stb_fontchar* charData = &stbFontData[(uint32_t)letter - firstChar];
         mappedMemory->x = (x + (float)charData->x0 * charW);
         mappedMemory->y = (y + (float)charData->y0 * charH);
         mappedMemory->z = charData->s0;
         mappedMemory->w = charData->t0;
         mappedMemory++;
         mappedMemory->x = (x + (float)charData->x1 * charW);
         mappedMemory->y = (y + (float)charData->y0 * charH);
         mappedMemory->z = charData->s1;
         mappedMemory->w = charData->t0;
         mappedMemory++;
         mappedMemory->x = (x + (float)charData->x0 * charW);
         mappedMemory->y = (y + (float)charData->y1 * charH);
         mappedMemory->z = charData->s0;
         mappedMemory->w = charData->t1;
         mappedMemory++;
         mappedMemory->x = (x + (float)charData->x1 * charW);
         mappedMemory->y = (y + (float)charData->y1 * charH);
         mappedMemory->z = charData->s1;
         mappedMemory->w = charData->t1;
         mappedMemory++;
         x += charData->advance * charW;
         numLetters++;
     }
     vkUnmapMemory(device->device, vertexBufferMemory);
     mappedMemory = nullptr;
 }
Member Data Documentation
fontTexture
Chronos::Engine::Texture Chronos::Engine::Font::fontTexture private
The font texture
Definition at line 132 of file font.hpp.
mappedMemory
glm::vec4* Chronos::Engine::Font::mappedMemory private
The mapped memory to the vertex buffer
Definition at line 137 of file font.hpp.
maxTextLength
uint32_t Chronos::Engine::Font::maxTextLength = 2048 private
Maximum number of characters that can be rendered.
Definition at line 117 of file font.hpp.
numLetters
uint32_t Chronos::Engine::Font::numLetters
The total number of letters to render.
Definition at line 79 of file font.hpp.
params
Chronos::Engine::TextParams Chronos::Engine::Font::params
Various parameters of the text that are set by the user.
Definition at line 84 of file font.hpp.
stbFontData
stb_fontchar Chronos::Engine::Font::stbFontData[STB_FONT_consolas_24_latin1_NUM_CHARS] private
The texture atlas that contains all the characters in the font.
Definition at line 122 of file font.hpp.
vertexBuffer
VkBuffer Chronos::Engine::Font::vertexBuffer
The vertices of each character used for rendering.
Definition at line 74 of file font.hpp.
vertexBufferMemory
VkDeviceMemory Chronos::Engine::Font::vertexBufferMemory private
The vertex buffer memory.
Definition at line 127 of file font.hpp.
The documentation for this class was generated from the following files:
Source/Engine/Headers/font.hpp
Source/Engine/Source/font.cpp