Chronos: Chronos::Editor::EditorRenderer Class Reference
Chronos::Editor::EditorRenderer Class Reference
#include <editorRenderer.hpp>
Public Member Functions
void init (Chronos::Engine::Device *device, GLFWwindow *window, Chronos::Engine::SwapChain *swapChain, VkInstance instance, VkSurfaceKHR surface)
void render (uint32_t currentFrame, uint32_t imageIndex, float bgColor[3])
void destroy ()
void update ()
void recreate ()
void changeMsaa ()
void cleanup ()
void renderAdditionalViewports ()
Public Attributes
Chronos::Engine::Device * device
Chronos::Engine::SwapChain * swapChain
VkSurfaceKHR surface
GLFWwindow * window
VkCommandPool commandPool
VkDescriptorPool descriptorPool
std::vector< VkCommandBuffer > commandBuffers
std::vector< VkFramebuffer > framebuffers
VkRenderPass renderPass
void(* addElements)()
Detailed Description
Definition at line 27 of file editorRenderer.hpp.
Member Function Documentation
changeMsaa()
void Chronos::Editor::EditorRenderer::changeMsaa ()
Definition at line 203 of file editorRenderer.cpp.
 {
     vkDestroyRenderPass(device->device, renderPass, nullptr);
     renderPass = Chronos::Engine::createRenderPass(*device, *swapChain,
     VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL,
     VK_IMAGE_LAYOUT_PRESENT_SRC_KHR,
     VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL, false, false, true);
     recreate();
 }
References Chronos::Engine::createRenderPass().
cleanup()
void Chronos::Editor::EditorRenderer::cleanup ()
Definition at line 177 of file editorRenderer.cpp.
 {
     for (auto framebuffer : framebuffers)
     vkDestroyFramebuffer(device->device, framebuffer, nullptr);
     LOG(3, "EditorRenderer", "EditorRenderer cleaned up")
 }
References LOG.
destroy()
void Chronos::Editor::EditorRenderer::destroy ()
Definition at line 131 of file editorRenderer.cpp.
 {
     ImGui_ImplVulkan_Shutdown();
     vkDestroyRenderPass(device->device, renderPass, nullptr);
     for (auto framebuffer : framebuffers)
     vkDestroyFramebuffer(device->device, framebuffer, nullptr);
     vkDestroyCommandPool(device->device, commandPool, nullptr);
     vkDestroyDescriptorPool(device->device, descriptorPool, nullptr);
     LOG(3, "EditorRenderer", "EditorRenderer destroyed")
 }
References LOG.
init()
void Chronos::Editor::EditorRenderer::init (Chronos::Engine::Device * device, GLFWwindow * window, Chronos::Engine::SwapChain * swapChain, VkInstance instance, VkSurfaceKHR surface)
Definition at line 33 of file editorRenderer.cpp.
 {
     this->device = device;
     this->swapChain = swapChain;
     this->surface = surface;
     this->window = window;
     renderPass = Chronos::Engine::createRenderPass(*device, *swapChain,
     VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL,
     VK_IMAGE_LAYOUT_PRESENT_SRC_KHR,
     VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL, false, false, true);
     framebuffers = Chronos::Engine::createFramebuffer(
     *device, *swapChain, renderPass, false);
     // Setup Dear ImGui context
     IMGUI_CHECKVERSION();
     ImGui::CreateContext();
     ImGuiIO& io = ImGui::GetIO();
     (void)io;
     io.ConfigFlags |= ImGuiConfigFlags_NavEnableKeyboard;
     io.ConfigFlags |= ImGuiConfigFlags_DockingEnable;
 #ifdef WIN32
     io.ConfigFlags |= ImGuiConfigFlags_ViewportsEnable;
     LOG(3, "EditorRenderer", "Viewports enabled")
 #endif
     ImGui::StyleColorsDark();
     std::array<VkDescriptorPoolSize, 1> poolSizes {};
     poolSizes[0].type = VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER;
     poolSizes[0].descriptorCount = static_cast<uint32_t>(MAX_FRAMES_IN_FLIGHT);
     VkDescriptorPoolSize pool_sizes[]
     = { { VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER, 100 } };
     VkDescriptorPoolCreateInfo pool_info = {};
     pool_info.sType = VK_STRUCTURE_TYPE_DESCRIPTOR_POOL_CREATE_INFO;
     pool_info.flags = VK_DESCRIPTOR_POOL_CREATE_FREE_DESCRIPTOR_SET_BIT;
     pool_info.maxSets = 100;
     pool_info.poolSizeCount = (uint32_t)IM_ARRAYSIZE(pool_sizes);
     pool_info.pPoolSizes = pool_sizes;
     vkCreateDescriptorPool(
     device->device, &pool_info, nullptr, &descriptorPool);
     ImGui_ImplGlfw_InitForVulkan(window, true);
     ImGui_ImplVulkan_InitInfo init_info = {};
     init_info.Instance = instance;
     init_info.PhysicalDevice = device->physicalDevice;
     init_info.Device = device->device;
     init_info.QueueFamily
     = Chronos::Engine::findQueueFamilies(device->physicalDevice, surface)
           .graphicsFamily.value();
     init_info.Queue = device->graphicsQueue;
     init_info.PipelineCache = VK_NULL_HANDLE;
     init_info.DescriptorPool = descriptorPool;
     init_info.RenderPass = renderPass;
     init_info.Allocator = nullptr;
     init_info.MinImageCount = MAX_FRAMES_IN_FLIGHT;
     init_info.ImageCount = MAX_FRAMES_IN_FLIGHT;
     init_info.MSAASamples = VK_SAMPLE_COUNT_1_BIT;
     init_info.CheckVkResultFn = nullptr; // add a fucntion to this
     ImGui_ImplVulkan_Init(&init_info);
     VkCommandPoolCreateInfo commandPoolCreateInfo = {};
     commandPoolCreateInfo.sType = VK_STRUCTURE_TYPE_COMMAND_POOL_CREATE_INFO;
     commandPoolCreateInfo.queueFamilyIndex
     = Chronos::Engine::findQueueFamilies(device->physicalDevice, surface)
           .graphicsFamily.value();
     commandPoolCreateInfo.flags
     = VK_COMMAND_POOL_CREATE_RESET_COMMAND_BUFFER_BIT;
     if (vkCreateCommandPool(
         device->device, &commandPoolCreateInfo, nullptr, &commandPool)
     != VK_SUCCESS) {
     LOG(1, "EditorRenderer", "Could not create graphics command pool")
     throw std::runtime_error("Could not create graphics command pool");
     }
     VkCommandBuffer command_buffer
     = Chronos::Engine::beginSingleTimeCommands(commandPool, device->device);
     ImGui_ImplVulkan_CreateFontsTexture();
     Chronos::Engine::endSingleTimeCommands(
     &command_buffer, *device, commandPool);
     commandBuffers.resize(swapChain->swapChainImageViews.size());
     VkCommandBufferAllocateInfo allocInfo {};
     allocInfo.sType = VK_STRUCTURE_TYPE_COMMAND_BUFFER_ALLOCATE_INFO;
     allocInfo.commandPool = commandPool;
     allocInfo.level = VK_COMMAND_BUFFER_LEVEL_PRIMARY;
     allocInfo.commandBufferCount = static_cast<uint32_t>(commandBuffers.size());
     if (vkAllocateCommandBuffers(
         device->device, &allocInfo, commandBuffers.data())
     != VK_SUCCESS) {
     LOG(1, "EditorRenderer", "failed to allocate command buffers!")
     throw std::runtime_error("failed to allocate command buffers!");
     }
     LOG(3, "EditorRenderer", "EditorRenderer initialized")
 }
References Chronos::Engine::beginSingleTimeCommands(), commandBuffers, commandPool, Chronos::Engine::createFramebuffer(), Chronos::Engine::createRenderPass(), descriptorPool, device, Chronos::Engine::Device::device, Chronos::Engine::endSingleTimeCommands(), Chronos::Engine::findQueueFamilies(), framebuffers, Chronos::Engine::QueueFamilyIndices::graphicsFamily, Chronos::Engine::Device::graphicsQueue, LOG, MAX_FRAMES_IN_FLIGHT, Chronos::Engine::Device::physicalDevice, renderPass, surface, swapChain, Chronos::Engine::SwapChain::swapChainImageViews, and window.
recreate()
void Chronos::Editor::EditorRenderer::recreate ()
Definition at line 184 of file editorRenderer.cpp.
 {
     cleanup();
     framebuffers = Chronos::Engine::createFramebuffer(
     *device, *swapChain, renderPass, false);
     LOG(3, "EditorRenderer", "EditorRenderer recreated")
 }
References Chronos::Engine::createFramebuffer(), and LOG.
render()
void Chronos::Editor::EditorRenderer::render (uint32_t currentFrame, uint32_t imageIndex, float bgColor[3])
Definition at line 152 of file editorRenderer.cpp.
 {
     vkResetCommandBuffer(commandBuffers[currentFrame], 0);
     VkCommandBufferBeginInfo beginInfo {};
     beginInfo.sType = VK_STRUCTURE_TYPE_COMMAND_BUFFER_BEGIN_INFO;
     VkClearValue clearColor
     = { { { bgColor[0], bgColor[1], bgColor[2], 1.0f } } };
     vkBeginCommandBuffer(commandBuffers[currentFrame], &beginInfo);
     VkRenderPassBeginInfo info = {};
     info.sType = VK_STRUCTURE_TYPE_RENDER_PASS_BEGIN_INFO;
     info.renderPass = renderPass;
     info.framebuffer = framebuffers[imageIndex];
     info.renderArea.extent = swapChain->swapChainExtent;
     info.clearValueCount = 1;
     info.pClearValues = &clearColor;
     vkCmdBeginRenderPass(
     commandBuffers[currentFrame], &info, VK_SUBPASS_CONTENTS_INLINE);
     ImGui_ImplVulkan_RenderDrawData(
     ImGui::GetDrawData(), commandBuffers[currentFrame]);
     vkCmdEndRenderPass(commandBuffers[currentFrame]);
     vkEndCommandBuffer(commandBuffers[currentFrame]);
     LOG(4, "EditorRenderer", "EditorRenderer rendered")
 }
References LOG.
renderAdditionalViewports()
void Chronos::Editor::EditorRenderer::renderAdditionalViewports ()
Definition at line 192 of file editorRenderer.cpp.
 {
 #ifdef WIN32
     if (ImGui::GetIO().ConfigFlags & ImGuiConfigFlags_ViewportsEnable) {
     ImGui::UpdatePlatformWindows();
     ImGui::RenderPlatformWindowsDefault();
     }
     LOG(4, "EditorRenderer", "Rendered additional viewports")
 #endif
 }
References LOG.
update()
void Chronos::Editor::EditorRenderer::update ()
Definition at line 142 of file editorRenderer.cpp.
 {
     ImGui_ImplVulkan_NewFrame();
     ImGui_ImplGlfw_NewFrame();
     ImGui::NewFrame();
     this->addElements();
     ImGui::Render();
     LOG(4, "EditorRenderer", "EditorRenderer updated")
 }
References addElements(), and LOG.
Member Data Documentation
addElements
void(* Chronos::Editor::EditorRenderer::addElements) ()
Definition at line 51 of file editorRenderer.hpp.
commandBuffers
std::vector<VkCommandBuffer> Chronos::Editor::EditorRenderer::commandBuffers
Definition at line 36 of file editorRenderer.hpp.
commandPool
VkCommandPool Chronos::Editor::EditorRenderer::commandPool
Definition at line 34 of file editorRenderer.hpp.
descriptorPool
VkDescriptorPool Chronos::Editor::EditorRenderer::descriptorPool
Definition at line 35 of file editorRenderer.hpp.
device
Chronos::Engine::Device* Chronos::Editor::EditorRenderer::device
Definition at line 29 of file editorRenderer.hpp.
framebuffers
std::vector<VkFramebuffer> Chronos::Editor::EditorRenderer::framebuffers
Definition at line 37 of file editorRenderer.hpp.
renderPass
VkRenderPass Chronos::Editor::EditorRenderer::renderPass
Definition at line 38 of file editorRenderer.hpp.
surface
VkSurfaceKHR Chronos::Editor::EditorRenderer::surface
Definition at line 31 of file editorRenderer.hpp.
swapChain
Chronos::Engine::SwapChain* Chronos::Editor::EditorRenderer::swapChain
Definition at line 30 of file editorRenderer.hpp.
window
GLFWwindow* Chronos::Editor::EditorRenderer::window
Definition at line 32 of file editorRenderer.hpp.
The documentation for this class was generated from the following files:
Source/Editor/Headers/editorRenderer.hpp
Source/Editor/Source/editorRenderer.cpp