Chronos: Chronos::Engine::ObjectManager< Object > Class Template Reference
Chronos::Engine::ObjectManager< Object > Class Template Reference abstract
Manages objects within the Chronos::Engine namespace.
#include <objectManager.hpp>
Public Member Functions
void remove (int objectNo)
Removes an object with the specified index.
void init (Chronos::Engine::Device *device, Chronos::Engine::SwapChain *swapChain, VkCommandPool commandPool)
Initializes the ObjectManager.
void destroy ()
Destroys resources associated with the ObjectManager.
void update (uint32_t currentFrame)
Updates the objects managed by the ObjectManager.
virtual void render (uint32_t currentFrame, uint32_t imageIndex, float bgColor[3])
Renders the objects managed by the ObjectManager.
void changeMsaa ()
Changes the multisampling settings for rendering.
void recreate ()
Recreates resources for rendering.
Public Attributes
int nextFreeObjectNo = 0
std::map< int, Object > objects
std::vector< VkCommandBuffer > commandBuffers
Protected Member Functions
void endRender (uint32_t currentFrame)
Ends the rendering process for the specified frame.
int addObject (Object object)
Adds an object to the ObjectManager.
virtual void createRenderPass ()=0
Creates the render pass used for rendering.
void cleanup ()
Cleans up resources associated with rendering.
Protected Attributes
Chronos::Engine::Device * device
Chronos::Engine::SwapChain * swapChain
VkCommandPool commandPool
VkRenderPass renderPass
VkSampler textureSampler
std::vector< VkFramebuffer > framebuffers
Detailed Description
template<ObjectLike Object>
class Chronos::Engine::ObjectManager< Object >
Manages objects within the Chronos::Engine namespace.
The ObjectManager class is a generic template that manages objects within the Chronos::Engine namespace. It provides functionalities for object initialization, destruction, rendering, and updating. The managed objects must adhere to the ObjectLike concept, i.e., they should be derived from Chronos::Engine::Object.
Template Parameters
Object The type of object managed by this ObjectManager.
Definition at line 31 of file objectManager.hpp.
Member Function Documentation
addObject()
template<Chronos::Engine::ObjectLike Object> int Chronos::Engine::ObjectManager< Object >::addObject (Object object) protected
Adds an object to the ObjectManager.
This function adds an object to the ObjectManager and assigns it a unique index.
Parameters
object The object to be added.
Returns
The index assigned to the added object.
Definition at line 82 of file objectManagerDefs.hpp.
 {
     int objectNo = nextFreeObjectNo;
     nextFreeObjectNo++;
     objects[objectNo] = object;
     return objectNo;
 }
changeMsaa()
template<Chronos::Engine::ObjectLike Object> void Chronos::Engine::ObjectManager< Object >::changeMsaa
Changes the multisampling settings for rendering.
This function changes the multisampling settings, recreating the Vulkan render pass accordingly.
Definition at line 61 of file objectManagerDefs.hpp.
 {
     vkDestroyRenderPass(device->device, renderPass, nullptr);
     renderPass = Chronos::Engine::createRenderPass(*device, *swapChain, VK_IMAGE_LAYOUT_UNDEFINED,
         VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL,
         VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL, true,
         true, false);
 }
References Chronos::Engine::createRenderPass().
cleanup()
template<Chronos::Engine::ObjectLike Object> void Chronos::Engine::ObjectManager< Object >::cleanup protected
Cleans up resources associated with rendering.
This function cleans up Vulkan framebuffers. This is called when swap chain is recreated.
Definition at line 70 of file objectManagerDefs.hpp.
 {
     for (auto framebuffer : framebuffers)
         vkDestroyFramebuffer(device->device, framebuffer, nullptr);
 }
createRenderPass()
template<ObjectLike Object> virtual void Chronos::Engine::ObjectManager< Object >::createRenderPass () protected pure virtual
Creates the render pass used for rendering.
This pure virtual function needs to be implemented by derived classes to create the Vulkan render pass.
Implemented in Chronos::Engine::TextManager, and Chronos::Engine::ShapeManager.
destroy()
template<Chronos::Engine::ObjectLike Object> void Chronos::Engine::ObjectManager< Object >::destroy
Destroys resources associated with the ObjectManager.
This function cleans up all Vulkan resources and destroys objects managed by the ObjectManager.
Definition at line 17 of file objectManagerDefs.hpp.
 {
     vkDestroySampler(device->device, textureSampler, nullptr);
     vkDestroyRenderPass(device->device, renderPass, nullptr);
     for (auto framebuffer : framebuffers)
         vkDestroyFramebuffer(device->device, framebuffer, nullptr);
     for (auto& objectMap : objects) {
         objectMap.second.destroy();
     }
 }
endRender()
template<Chronos::Engine::ObjectLike Object> void Chronos::Engine::ObjectManager< Object >::endRender (uint32_t currentFrame) protected
Ends the rendering process for the specified frame.
This function marks the end of recording of vulkan rendering commands for the specified frame when started by the render command
Parameters
currentFrame The current frame number.
Definition at line 54 of file objectManagerDefs.hpp.
{
     vkCmdEndRenderPass(commandBuffers[currentFrame]);
     if (vkEndCommandBuffer(commandBuffers[currentFrame]) != VK_SUCCESS) {
         throw std::runtime_error("failed to record command buffer!");
     }
 }
init()
template<Chronos::Engine::ObjectLike Object> void Chronos::Engine::ObjectManager< Object >::init (Chronos::Engine::Device * device, Chronos::Engine::SwapChain * swapChain, VkCommandPool commandPool)
Initializes the ObjectManager.
This function initializes the ObjectManager with the given Chronos::Engine::Device, Chronos::Engine::SwapChain, and Vulkan command pool. It creates necessary Vulkan resources like render pass, framebuffers, and command buffers.
Parameters
device Pointer to the Chronos::Engine::Device used for initialization.
swapChain Pointer to the Chronos::Engine::SwapChain used for initialization.
commandPool Vulkan command pool used for initialization.
Definition at line 3 of file objectManagerDefs.hpp.
 {
     this->device = device;
     this->swapChain = swapChain;
     this->commandPool = commandPool;
     Chronos::Engine::createTextureSampler(*device, &textureSampler);
     createRenderPass();
     commandBuffers = Chronos::Engine::createCommandBuffer(*device, *swapChain, commandPool);
     framebuffers = Chronos::Engine::createFramebuffer(*device, *swapChain, renderPass, true);
 }
References Chronos::Engine::createCommandBuffer(), Chronos::Engine::createFramebuffer(), Chronos::Engine::createRenderPass(), and Chronos::Engine::createTextureSampler().
recreate()
template<Chronos::Engine::ObjectLike Object> void Chronos::Engine::ObjectManager< Object >::recreate
Recreates resources for rendering.
This function recreates Vulkan framebuffers after cleaning up the existing ones during swapchain recreation.
Definition at line 76 of file objectManagerDefs.hpp.
 {
     cleanup();
     framebuffers = createFramebuffer(*device, *swapChain, renderPass, true);
 }
References Chronos::Engine::createFramebuffer().
remove()
template<Chronos::Engine::ObjectLike Object> void Chronos::Engine::ObjectManager< Object >::remove (int objectNo)
Removes an object with the specified index.
This function removes an object from the ObjectManager based on the provided index. The associated Vulkan resources are also cleaned up, and the object is destroyed.
Parameters
objectNo The index of the object to remove.
Definition at line 90 of file objectManagerDefs.hpp.
 {
     objects[objectNo].destroy();
     objects.erase(objectNo);
 }
render()
template<Chronos::Engine::ObjectLike Object> void Chronos::Engine::ObjectManager< Object >::render (uint32_t currentFrame, uint32_t imageIndex, float bgColor[3]) virtual
Renders the objects managed by the ObjectManager.
This virtual function needs to be implemented by derived classes. It initiates the rendering process for the specified frame and image index with a given background color.
Parameters
currentFrame The current frame number.
imageIndex The index of the image being rendered.
bgColor Array representing the background color.
Reimplemented in Chronos::Engine::TextManager, and Chronos::Engine::ShapeManager.
Definition at line 29 of file objectManagerDefs.hpp.
 {
     vkResetCommandBuffer(commandBuffers[currentFrame], 0);
     VkCommandBufferBeginInfo beginInfo {};
     beginInfo.sType = VK_STRUCTURE_TYPE_COMMAND_BUFFER_BEGIN_INFO;
     if (vkBeginCommandBuffer(commandBuffers[currentFrame], &beginInfo) != VK_SUCCESS) {
         throw std::runtime_error("failed to begin recording command buffer!");
     }
     VkRenderPassBeginInfo renderPassInfo {};
     renderPassInfo.sType = VK_STRUCTURE_TYPE_RENDER_PASS_BEGIN_INFO;
     renderPassInfo.renderPass = renderPass;
     renderPassInfo.framebuffer = framebuffers[imageIndex];
     renderPassInfo.renderArea.offset = { 0, 0 };
     renderPassInfo.renderArea.extent = swapChain->swapChainExtent;
     VkClearValue clearColor = { bgColor[0], bgColor[1], bgColor[2],
         1.0f }; // bg color
     renderPassInfo.clearValueCount = 1;
     renderPassInfo.pClearValues = &clearColor;
     vkCmdBeginRenderPass(commandBuffers[currentFrame], &renderPassInfo,
         VK_SUBPASS_CONTENTS_INLINE);
 }
update()
template<Chronos::Engine::ObjectLike Object> void Chronos::Engine::ObjectManager< Object >::update (uint32_t currentFrame)
Updates the objects managed by the ObjectManager.
This function updates all objects managed by the ObjectManager for the given frame.
Parameters
currentFrame The current frame number.
Definition at line 96 of file objectManagerDefs.hpp.
 {
     for (auto& objectMap : objects) {
         objectMap.second.update(currentFrame);
     }
 }
Member Data Documentation
commandBuffers
template<ObjectLike Object> std::vector<VkCommandBuffer> Chronos::Engine::ObjectManager< Object >::commandBuffers
Vector of Vulkan command buffers.
Definition at line 35 of file objectManager.hpp.
commandPool
template<ObjectLike Object> VkCommandPool Chronos::Engine::ObjectManager< Object >::commandPool protected
Vulkan command pool used for rendering.
Definition at line 140 of file objectManager.hpp.
device
template<ObjectLike Object> Chronos::Engine::Device* Chronos::Engine::ObjectManager< Object >::device protected
Pointer to the Chronos::Engine::Device used for rendering.
Definition at line 138 of file objectManager.hpp.
framebuffers
template<ObjectLike Object> std::vector<VkFramebuffer> Chronos::Engine::ObjectManager< Object >::framebuffers protected
Vector of Vulkan framebuffers.
Definition at line 143 of file objectManager.hpp.
nextFreeObjectNo
template<ObjectLike Object> int Chronos::Engine::ObjectManager< Object >::nextFreeObjectNo = 0
The index for the next free object.
Definition at line 33 of file objectManager.hpp.
objects
template<ObjectLike Object> std::map<int, Object> Chronos::Engine::ObjectManager< Object >::objects
A map of object indices to their corresponding objects.
Definition at line 34 of file objectManager.hpp.
renderPass
template<ObjectLike Object> VkRenderPass Chronos::Engine::ObjectManager< Object >::renderPass protected
Vulkan render pass used for rendering.
Definition at line 141 of file objectManager.hpp.
swapChain
template<ObjectLike Object> Chronos::Engine::SwapChain* Chronos::Engine::ObjectManager< Object >::swapChain protected
Pointer to the Chronos::Engine::SwapChain used for rendering.
Definition at line 139 of file objectManager.hpp.
textureSampler
template<ObjectLike Object> VkSampler Chronos::Engine::ObjectManager< Object >::textureSampler protected
Vulkan sampler for textures.
Definition at line 142 of file objectManager.hpp.
The documentation for this class was generated from the following files:
Source/Engine/Headers/objectManager.hpp
Source/Engine/Headers/objectManagerDefs.hpp