Chronos: Chronos::Engine::TexturedRectangle Class Reference
Chronos::Engine::TexturedRectangle Class Reference
#include <TexturedRectangle.hpp>
Public Member Functions
void init (Chronos::Engine::Device *device, VkCommandPool commandPool, Chronos::Engine::SwapChain *swapChain, VkSampler textureSampler, Chronos::Engine::Texture texture, VkRenderPass *renderPass)
void update (uint32_t currentFrame) override
Updates the object for the current frame.
void destroy () override
Destroys the object and releases associated resources.
void render (uint32_t currentFrame, uint32_t imageIndex, float bgColor[3], VkViewport &viewport, VkRect2D &scissor, std::vector< VkCommandBuffer > &commandBuffers) override
Public Member Functions inherited from Chronos::Engine::Object
void init (Chronos::Engine::Device *device, VkCommandPool commandPool, Chronos::Engine::SwapChain *swapChain, VkSampler textureSampler, VkRenderPass *renderPass, ObjectType objectType)
Initializes the object.
void recreateGraphicsPipeline ()
Recreates the graphics pipeline for the object.
Public Attributes
const std::vector< uint16_t > indices = std::vector<uint16_t> { 0, 1, 2, 2, 3, 0 }
const std::vector< TexturedVertex > vertices
Chronos::Engine::Texture texture
Chronos::Manager::ShapeParams params
Chronos::Engine::Buffer vertexBuffer
The vertex buffer that is used to store the vertices.
Chronos::Engine::Buffer indexBuffer
The index buffer that is used to store the indices.
Public Attributes inherited from Chronos::Engine::Object
VkPipeline graphicsPipeline
VkPipelineLayout pipelineLayout
std::vector< VkDescriptorSet > descriptorSets
Chronos::Engine::ObjectType objectType
Private Member Functions
void createDescriptorSets () override
std::vector< VkDescriptorType > getDescriptorTypes () override
std::vector< VkShaderStageFlagBits > getDescriptorStages () override
PipelineAttributes getPipelineAttributes () override
Additional Inherited Members
Protected Member Functions inherited from Chronos::Engine::Object
void createGraphicsPipeline ()
Creates the graphics pipeline for the object.
void createDescriptorPool ()
Creates the Vulkan descriptor pool for the object.
void createDescriptorSetLayout ()
Creates the Vulkan descriptor set layout for the object.
Protected Attributes inherited from Chronos::Engine::Object
std::string vertexShaderPath
std::string fragmentShaderPath
Chronos::Engine::Device * device
Chronos::Engine::SwapChain * swapChain
VkCommandPool commandPool
VkSampler textureSampler
VkRenderPass * renderPass
VkDescriptorSetLayout descriptorSetLayout
VkDescriptorPool descriptorPool
std::vector< Chronos::Engine::UniformBuffer > uniformBuffers
Detailed Description
Definition at line 34 of file TexturedRectangle.hpp.
Member Function Documentation
createDescriptorSets()
void Chronos::Engine::TexturedRectangle::createDescriptorSets () override private virtual
Implements Chronos::Engine::Object.
Definition at line 66 of file TexturedRectangle.cpp.
{
    std::vector<VkDescriptorSetLayout> layouts(
    MAX_FRAMES_IN_FLIGHT, descriptorSetLayout);
    VkDescriptorSetAllocateInfo allocInfo {};
    allocInfo.sType = VK_STRUCTURE_TYPE_DESCRIPTOR_SET_ALLOCATE_INFO;
    allocInfo.descriptorPool = descriptorPool;
    allocInfo.descriptorSetCount = static_cast<uint32_t>(MAX_FRAMES_IN_FLIGHT);
    allocInfo.pSetLayouts = layouts.data();
    descriptorSets.resize(MAX_FRAMES_IN_FLIGHT);
    if (vkAllocateDescriptorSets(
        device->device, &allocInfo, descriptorSets.data())
    != VK_SUCCESS) {
    throw std::runtime_error("failed to allocate descriptor sets!");
    }
    for (size_t i = 0; i < MAX_FRAMES_IN_FLIGHT; i++) {
    VkDescriptorBufferInfo bufferInfo {};
    bufferInfo.buffer = uniformBuffers[i].buffer;
    bufferInfo.offset = 0;
    bufferInfo.range = sizeof(UniformBufferObject);
    VkDescriptorImageInfo imageInfo {};
    imageInfo.imageLayout = VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL;
    imageInfo.imageView = texture.textureImageView;
    imageInfo.sampler = textureSampler;
    std::array<VkWriteDescriptorSet, 2> descriptorWrites {};
    descriptorWrites[0].sType = VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET;
    descriptorWrites[0].dstSet = descriptorSets[i];
    descriptorWrites[0].dstBinding = 0;
    descriptorWrites[0].dstArrayElement = 0;
    descriptorWrites[0].descriptorType = VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER;
    descriptorWrites[0].descriptorCount = 1;
    descriptorWrites[0].pBufferInfo = &bufferInfo;
    descriptorWrites[1].sType = VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET;
    descriptorWrites[1].dstSet = descriptorSets[i];
    descriptorWrites[1].dstBinding = 1;
    descriptorWrites[1].dstArrayElement = 0;
    descriptorWrites[1].descriptorType
        = VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER;
    descriptorWrites[1].descriptorCount = 1;
    descriptorWrites[1].pImageInfo = &imageInfo;
    vkUpdateDescriptorSets(device->device,
        static_cast<uint32_t>(descriptorWrites.size()),
        descriptorWrites.data(), 0, nullptr);
    }
}
References MAX_FRAMES_IN_FLIGHT.
destroy()
void Chronos::Engine::TexturedRectangle::destroy () override virtual
Destroys the object and releases associated resources.
This method is responsible for cleaning up the object's resources, including uniform buffers, descriptor pool, descriptor set layout, graphics pipeline, and pipeline layout.
Implements Chronos::Engine::Object.
Definition at line 59 of file TexturedRectangle.cpp.
{
    vertexBuffer.destroy();
    indexBuffer.destroy();
    Chronos::Engine::Object::destroy();
}
References Chronos::Engine::Object::destroy().
getDescriptorStages()
std::vector< VkShaderStageFlagBits > Chronos::Engine::TexturedRectangle::getDescriptorStages () override private virtual
Implements Chronos::Engine::Object.
Definition at line 124 of file TexturedRectangle.cpp.
{
    return std::vector<VkShaderStageFlagBits> { VK_SHADER_STAGE_VERTEX_BIT,
    VK_SHADER_STAGE_FRAGMENT_BIT };
}
getDescriptorTypes()
std::vector< VkDescriptorType > Chronos::Engine::TexturedRectangle::getDescriptorTypes () override private virtual
Implements Chronos::Engine::Object.
Definition at line 117 of file TexturedRectangle.cpp.
{
    return std::vector<VkDescriptorType> { VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER,
    VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER };
}
getPipelineAttributes()
Chronos::Engine::PipelineAttributes Chronos::Engine::TexturedRectangle::getPipelineAttributes () override private virtual
Implements Chronos::Engine::Object.
Definition at line 131 of file TexturedRectangle.cpp.
{
    Chronos::Engine::PipelineAttributes pipelineAttributes;
    auto bindingDescription = TexturedVertex::getBindingDescription();
    auto attributeDescriptions = TexturedVertex::getAttributeDescriptions();
    pipelineAttributes.bindingDescriptions.resize(1);
    pipelineAttributes.bindingDescriptions[0] = bindingDescription;
    pipelineAttributes.attributeDescriptions.resize(
    attributeDescriptions.size());
    for (int i = 0; i < static_cast<int>(attributeDescriptions.size()); i++) {
    pipelineAttributes.attributeDescriptions[i] = attributeDescriptions[i];
    }
    pipelineAttributes.topology = VK_PRIMITIVE_TOPOLOGY_TRIANGLE_LIST;
    pipelineAttributes.frontFace = VK_FRONT_FACE_COUNTER_CLOCKWISE;
    pipelineAttributes.colorBlendAttachment.colorWriteMask
    = VK_COLOR_COMPONENT_R_BIT | VK_COLOR_COMPONENT_G_BIT
    | VK_COLOR_COMPONENT_B_BIT | VK_COLOR_COMPONENT_A_BIT;
    pipelineAttributes.colorBlendAttachment.blendEnable = VK_FALSE;
    pipelineAttributes.colorBlendAttachment.srcColorBlendFactor
    = VK_BLEND_FACTOR_ONE;
    pipelineAttributes.colorBlendAttachment.dstColorBlendFactor
    = VK_BLEND_FACTOR_ZERO; // Optional
    pipelineAttributes.colorBlendAttachment.colorBlendOp
    = VK_BLEND_OP_ADD; // Optional
    pipelineAttributes.colorBlendAttachment.srcAlphaBlendFactor
    = VK_BLEND_FACTOR_ONE; // Optional
    pipelineAttributes.colorBlendAttachment.dstAlphaBlendFactor
    = VK_BLEND_FACTOR_ZERO; // Optional
    pipelineAttributes.colorBlendAttachment.alphaBlendOp
    = VK_BLEND_OP_ADD; // Optional
    return pipelineAttributes;
}
References Chronos::Engine::PipelineAttributes::attributeDescriptions, Chronos::Engine::PipelineAttributes::bindingDescriptions, Chronos::Engine::PipelineAttributes::colorBlendAttachment, Chronos::Engine::PipelineAttributes::frontFace, Chronos::Engine::TexturedVertex::getAttributeDescriptions(), Chronos::Engine::TexturedVertex::getBindingDescription(), and Chronos::Engine::PipelineAttributes::topology.
init()
void Chronos::Engine::TexturedRectangle::init (Chronos::Engine::Device * device, VkCommandPool commandPool, Chronos::Engine::SwapChain * swapChain, VkSampler textureSampler, Chronos::Engine::Texture texture, VkRenderPass * renderPass)
Definition at line 26 of file TexturedRectangle.cpp.
{
    this->vertexShaderPath = SPIV_SHADER_PATH "/textureVert.spv";
    this->fragmentShaderPath = SPIV_SHADER_PATH "/textureFrag.spv";
    this->texture = texture;
    Chronos::Engine::Object::init(device, commandPool, swapChain,
    textureSampler, renderPass,
    Chronos::Engine::ObjectType::TypeTexturedRectangle);
    // create the vertex and index buffers and copy the data
    vertexBuffer.size = sizeof(vertices[0]) * vertices.size();
    vertexBuffer.create(*device,
    VK_BUFFER_USAGE_TRANSFER_DST_BIT | VK_BUFFER_USAGE_VERTEX_BUFFER_BIT,
    VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT);
    vertexBuffer.copy((void*)vertices.data(), commandPool);
    indexBuffer.size = sizeof(indices[0]) * indices.size();
    indexBuffer.create(*device,
    VK_BUFFER_USAGE_TRANSFER_DST_BIT | VK_BUFFER_USAGE_INDEX_BUFFER_BIT,
    VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT);
    indexBuffer.copy((void*)indices.data(), commandPool);
}
References Chronos::Engine::Object::commandPool, Chronos::Engine::Buffer::copy(), Chronos::Engine::Buffer::create(), Chronos::Engine::Object::device, Chronos::Engine::Object::fragmentShaderPath, indexBuffer, indices, Chronos::Engine::Object::init(), Chronos::Engine::Object::renderPass, Chronos::Engine::Buffer::size, Chronos::Engine::Object::swapChain, texture, Chronos::Engine::Object::textureSampler, Chronos::Engine::TypeTexturedRectangle, vertexBuffer, Chronos::Engine::Object::vertexShaderPath, and vertices.
render()
void Chronos::Engine::TexturedRectangle::render (uint32_t currentFrame, uint32_t imageIndex, float bgColor[3], VkViewport & viewport, VkRect2D & scissor, std::vector< VkCommandBuffer > & commandBuffers) override virtual
Implements Chronos::Engine::Object.
Definition at line 170 of file TexturedRectangle.cpp.
{
    vkCmdBindPipeline(commandBuffers[currentFrame],
    VK_PIPELINE_BIND_POINT_GRAPHICS, this->graphicsPipeline);
    vkCmdSetViewport(commandBuffers[currentFrame], 0, 1, &viewport);
    vkCmdSetScissor(commandBuffers[currentFrame], 0, 1, &scissor);
    VkBuffer vertexBuffers[] = { this->vertexBuffer.buffer };
    VkDeviceSize offsets[] = { 0 };
    vkCmdBindVertexBuffers(
    commandBuffers[currentFrame], 0, 1, vertexBuffers, offsets);
    vkCmdBindIndexBuffer(commandBuffers[currentFrame], this->indexBuffer.buffer,
    0, VK_INDEX_TYPE_UINT16);
    vkCmdBindDescriptorSets(commandBuffers[currentFrame],
    VK_PIPELINE_BIND_POINT_GRAPHICS, this->pipelineLayout, 0, 1,
    &this->descriptorSets[currentFrame], 0, nullptr);
    vkCmdDrawIndexed(commandBuffers[currentFrame],
    static_cast<uint32_t>(this->indices.size()), 1, 0, 0, 0);
}
update()
void Chronos::Engine::TexturedRectangle::update (uint32_t currentFrame) override virtual
Updates the object for the current frame.
This pure virtual method must be implemented by derived classes to perform any updates required for the object during each frame. The currentFrame parameter represents the index of the current frame in the application.
Parameters
currentFrame Index of the current frame.
Implements Chronos::Engine::Object.
Definition at line 53 of file TexturedRectangle.cpp.
{
    uniformBuffers[currentFrame].update(swapChain->swapChainExtent, params.x,
    params.y, params.rotation, params.xSize, params.ySize);
}
Member Data Documentation
indexBuffer
Chronos::Engine::Buffer Chronos::Engine::TexturedRectangle::indexBuffer
The index buffer that is used to store the indices.
Definition at line 64 of file TexturedRectangle.hpp.
indices
const std::vector<uint16_t> Chronos::Engine::TexturedRectangle::indices = std::vector<uint16_t> { 0, 1, 2, 2, 3, 0 }
Definition at line 41 of file TexturedRectangle.hpp.
{ 0, 1, 2, 2, 3, 0 };
params
Chronos::Manager::ShapeParams Chronos::Engine::TexturedRectangle::params
Definition at line 52 of file TexturedRectangle.hpp.
texture
Chronos::Engine::Texture Chronos::Engine::TexturedRectangle::texture
Definition at line 51 of file TexturedRectangle.hpp.
vertexBuffer
Chronos::Engine::Buffer Chronos::Engine::TexturedRectangle::vertexBuffer
The vertex buffer that is used to store the vertices.
Definition at line 56 of file TexturedRectangle.hpp.
vertices
const std::vector<TexturedVertex> Chronos::Engine::TexturedRectangle::vertices
Initial value:
= std::vector<TexturedVertex> { { { -0.5f, -0.5f },
                        { 1.0f, 0.0f } },
          { { 0.5f, -0.5f }, { 0.0f, 0.0f } },
          { { 0.5f, 0.5f }, { 0.0f, 1.0f } },
          { { -0.5f, 0.5f }, { 1.0f, 1.0f } } }
Definition at line 44 of file TexturedRectangle.hpp.
                                    { { { -0.5f, -0.5f },
                        { 1.0f, 0.0f } },
          { { 0.5f, -0.5f }, { 0.0f, 0.0f } },
          { { 0.5f, 0.5f }, { 0.0f, 1.0f } },
          { { -0.5f, 0.5f }, { 1.0f, 1.0f } } };
The documentation for this class was generated from the following files:
Source/Rendering/Objects/Rectangle/TexturedRectangle.hpp
Source/Rendering/Objects/Rectangle/TexturedRectangle.cpp