Chronos: Chronos::Engine::Shape Class Reference
Chronos::Engine::Shape Class Reference
Class for creating a shape(triangle, rectangle, etc.).
#include <shape.hpp>
Public Member Functions
void init (Chronos::Engine::Device *device, VkCommandPool commandPool, Chronos::Engine::SwapChain *swapChain, VkSampler textureSampler, std::string texturePath, VkRenderPass *renderPass)
Initializes the shape object and creates the necessary objects.
void update (uint32_t currentFrame) override
Updates the shape object for the current frame.
void destroy () override
Destroys the shape object and frees the memory.
void createDescriptorSets () override
std::vector< VkDescriptorType > getDescriptorTypes () override
std::vector< VkShaderStageFlagBits > getDescriptorStages () override
std::vector< VkShaderStageFlagBits > getShaderStages ()
Public Member Functions inherited from Chronos::Engine::Object
virtual void init (Chronos::Engine::Device *device, VkCommandPool commandPool, Chronos::Engine::SwapChain *swapChain, VkSampler textureSampler, VkRenderPass *renderPass)
Initializes the object.
void recreateGraphicsPipeline ()
Recreates the graphics pipeline for the object.
Public Attributes
Chronos::Engine::ShapeParams params
The parameters that are associated with the shape.
std::vector< uint16_t > indices
The indices that is used to specify the order of vertices to render.
Chronos::Engine::Texture texture
The texture that is to be used.
std::vector< Vertex > vertices
The vertices that is used to render the shape.
Chronos::Engine::Buffer vertexBuffer
The vertex buffer that is used to store the vertices.
Chronos::Engine::Buffer indexBuffer
The index buffer that is used to store the indices.
Public Attributes inherited from Chronos::Engine::Object
VkPipeline graphicsPipeline
VkPipelineLayout pipelineLayout
std::vector< VkDescriptorSet > descriptorSets
Private Member Functions
PipelineAttributes getPipelineAttributes () override
Additional Inherited Members
Protected Member Functions inherited from Chronos::Engine::Object
void createGraphicsPipeline ()
Creates the graphics pipeline for the object.
void createDescriptorPool ()
Creates the Vulkan descriptor pool for the object.
void createDescriptorSetLayout ()
Creates the Vulkan descriptor set layout for the object.
Protected Attributes inherited from Chronos::Engine::Object
std::string vertexShaderPath
std::string fragmentShaderPath
Chronos::Engine::Device * device
Chronos::Engine::SwapChain * swapChain
VkCommandPool commandPool
VkSampler textureSampler
VkRenderPass * renderPass
VkDescriptorSetLayout descriptorSetLayout
VkDescriptorPool descriptorPool
std::vector< Chronos::Engine::UniformBuffer > uniformBuffers
Detailed Description
Class for creating a shape(triangle, rectangle, etc.).
This class is used to create a shape(triangle, rectangle, etc.). It is a child of the Object class. It handles all the vulkan objects needed for rendering the shape.
Definition at line 21 of file shape.hpp.
Member Function Documentation
createDescriptorSets()
void Chronos::Engine::Shape::createDescriptorSets () override virtual
Implements Chronos::Engine::Object.
Definition at line 38 of file shape.cpp.
 {
     std::vector<VkDescriptorSetLayout> layouts(MAX_FRAMES_IN_FLIGHT,
         descriptorSetLayout);
     VkDescriptorSetAllocateInfo allocInfo {};
     allocInfo.sType = VK_STRUCTURE_TYPE_DESCRIPTOR_SET_ALLOCATE_INFO;
     allocInfo.descriptorPool = descriptorPool;
     allocInfo.descriptorSetCount = static_cast<uint32_t>(MAX_FRAMES_IN_FLIGHT);
     allocInfo.pSetLayouts = layouts.data();
     descriptorSets.resize(MAX_FRAMES_IN_FLIGHT);
     if (vkAllocateDescriptorSets(device->device, &allocInfo,
             descriptorSets.data())
         != VK_SUCCESS) {
         throw std::runtime_error("failed to allocate descriptor sets!");
     }
     for (size_t i = 0; i < MAX_FRAMES_IN_FLIGHT; i++) {
         VkDescriptorBufferInfo bufferInfo {};
         bufferInfo.buffer = uniformBuffers[i].buffer;
         bufferInfo.offset = 0;
         bufferInfo.range = sizeof(UniformBufferObject);
         VkWriteDescriptorSet descriptorWrite {};
         VkDescriptorImageInfo imageInfo {};
         imageInfo.imageLayout = VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL;
         imageInfo.imageView = texture.textureImageView;
         imageInfo.sampler = textureSampler;
         std::array<VkWriteDescriptorSet, 2> descriptorWrites {};
         descriptorWrites[0].sType = VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET;
         descriptorWrites[0].dstSet = descriptorSets[i];
         descriptorWrites[0].dstBinding = 0;
         descriptorWrites[0].dstArrayElement = 0;
         descriptorWrites[0].descriptorType = VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER;
         descriptorWrites[0].descriptorCount = 1;
         descriptorWrites[0].pBufferInfo = &bufferInfo;
         descriptorWrites[1].sType = VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET;
         descriptorWrites[1].dstSet = descriptorSets[i];
         descriptorWrites[1].dstBinding = 1;
         descriptorWrites[1].dstArrayElement = 0;
         descriptorWrites[1].descriptorType = VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER;
         descriptorWrites[1].descriptorCount = 1;
         descriptorWrites[1].pImageInfo = &imageInfo;
         vkUpdateDescriptorSets(device->device,
             static_cast<uint32_t>(descriptorWrites.size()),
             descriptorWrites.data(), 0, nullptr);
     }
 }
References MAX_FRAMES_IN_FLIGHT.
destroy()
void Chronos::Engine::Shape::destroy () override virtual
Destroys the shape object and frees the memory.
This destroys all the vulkan related objects related to this class and frees memory.
Implements Chronos::Engine::Object.
Definition at line 29 of file shape.cpp.
 {
     texture.destroy();
     vertexBuffer.destroy();
     indexBuffer.destroy();
     Chronos::Engine::Object::destroy();
 }
References Chronos::Engine::Object::destroy().
getDescriptorStages()
std::vector< VkShaderStageFlagBits > Chronos::Engine::Shape::getDescriptorStages () override virtual
Implements Chronos::Engine::Object.
Definition at line 102 of file shape.cpp.
 {
     return std::vector<VkShaderStageFlagBits> { VK_SHADER_STAGE_VERTEX_BIT,
         VK_SHADER_STAGE_FRAGMENT_BIT };
 }
getDescriptorTypes()
std::vector< VkDescriptorType > Chronos::Engine::Shape::getDescriptorTypes () override virtual
Implements Chronos::Engine::Object.
Definition at line 96 of file shape.cpp.
 {
     return std::vector<VkDescriptorType> { VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER,
         VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER };
 }
getPipelineAttributes()
Chronos::Engine::PipelineAttributes Chronos::Engine::Shape::getPipelineAttributes () override private virtual
Implements Chronos::Engine::Object.
Definition at line 108 of file shape.cpp.
 {
     Chronos::Engine::PipelineAttributes pipelineAttributes;
     auto bindingDescription = Vertex::getBindingDescription();
     auto attributeDescriptions = Vertex::getAttributeDescriptions();
     pipelineAttributes.bindingDescriptions.resize(1);
     pipelineAttributes.bindingDescriptions[0] = bindingDescription;
     pipelineAttributes.attributeDescriptions.resize(3);
     for (int i = 0; i < 3; i++) {
         pipelineAttributes.attributeDescriptions[i] = attributeDescriptions[i];
     }
     pipelineAttributes.topology = VK_PRIMITIVE_TOPOLOGY_TRIANGLE_LIST;
     pipelineAttributes.frontFace = VK_FRONT_FACE_COUNTER_CLOCKWISE;
     pipelineAttributes.colorBlendAttachment.colorWriteMask = VK_COLOR_COMPONENT_R_BIT | VK_COLOR_COMPONENT_G_BIT | VK_COLOR_COMPONENT_B_BIT | VK_COLOR_COMPONENT_A_BIT;
     pipelineAttributes.colorBlendAttachment.blendEnable = VK_FALSE;
     pipelineAttributes.colorBlendAttachment.srcColorBlendFactor = VK_BLEND_FACTOR_ONE;
     pipelineAttributes.colorBlendAttachment.dstColorBlendFactor = VK_BLEND_FACTOR_ZERO; // Optional
     pipelineAttributes.colorBlendAttachment.colorBlendOp = VK_BLEND_OP_ADD; // Optional
     pipelineAttributes.colorBlendAttachment.srcAlphaBlendFactor = VK_BLEND_FACTOR_ONE; // Optional
     pipelineAttributes.colorBlendAttachment.dstAlphaBlendFactor = VK_BLEND_FACTOR_ZERO; // Optional
     pipelineAttributes.colorBlendAttachment.alphaBlendOp = VK_BLEND_OP_ADD; // Optional
     return pipelineAttributes;
 }
References Chronos::Engine::PipelineAttributes::attributeDescriptions, Chronos::Engine::PipelineAttributes::bindingDescriptions, Chronos::Engine::PipelineAttributes::colorBlendAttachment, Chronos::Engine::PipelineAttributes::frontFace, Chronos::Engine::Vertex::getAttributeDescriptions(), Chronos::Engine::Vertex::getBindingDescription(), and Chronos::Engine::PipelineAttributes::topology.
getShaderStages()
std::vector<VkShaderStageFlagBits> Chronos::Engine::Shape::getShaderStages ()
init()
void Chronos::Engine::Shape::init (Chronos::Engine::Device * device, VkCommandPool commandPool, Chronos::Engine::SwapChain * swapChain, VkSampler textureSampler, std::string texturePath, VkRenderPass * renderPass)
Initializes the shape object and creates the necessary objects.
Used to create the shape object and create the necessary vulkan objects for rendering the shape.
Parameters
device The device to use for creating the objects.
commandPool The command pool to create the command buffer on
swapChain The swapchain that is used
textureSampler The texture sampler to use
texturePath The path to the texture(png and jpg supported)
Definition at line 3 of file shape.cpp.
 {
     this->vertexShaderPath = "ThirdParty/Chronos/Shaders/vert.spv";
     this->fragmentShaderPath = "ThirdParty/Chronos/Shaders/frag.spv";
     texture.create(*device, commandPool, texturePath);
     Chronos::Engine::Object::init(device, commandPool, swapChain, textureSampler, renderPass);
     // create the vertex and index buffers and copy the data
     vertexBuffer.size = sizeof(vertices[0]) * vertices.size();
     vertexBuffer.create(*device,
         VK_BUFFER_USAGE_TRANSFER_DST_BIT | VK_BUFFER_USAGE_VERTEX_BUFFER_BIT,
         VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT);
     vertexBuffer.copy(vertices.data(), commandPool);
     indexBuffer.size = sizeof(indices[0]) * indices.size();
     indexBuffer.create(*device,
         VK_BUFFER_USAGE_TRANSFER_DST_BIT | VK_BUFFER_USAGE_INDEX_BUFFER_BIT,
         VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT);
     indexBuffer.copy(indices.data(), commandPool);
 }
References Chronos::Engine::Object::commandPool, Chronos::Engine::Buffer::copy(), Chronos::Engine::Buffer::create(), Chronos::Engine::Texture::create(), Chronos::Engine::Object::device, Chronos::Engine::Object::fragmentShaderPath, indexBuffer, indices, Chronos::Engine::Object::init(), Chronos::Engine::Object::renderPass, Chronos::Engine::Buffer::size, Chronos::Engine::Object::swapChain, texture, Chronos::Engine::Object::textureSampler, vertexBuffer, Chronos::Engine::Object::vertexShaderPath, and vertices.
update()
void Chronos::Engine::Shape::update (uint32_t currentFrame) override virtual
Updates the shape object for the current frame.
This function is used to update the shape object for the current frame. It is called by the ObjectManager class. It does this by updating the uniform buffer.
Parameters
currentFrame The current frame number to render to.
Implements Chronos::Engine::Object.
Definition at line 89 of file shape.cpp.
 {
     uniformBuffers[currentFrame].update(swapChain->swapChainExtent, params.x,
         params.y, params.rotation, params.xSize,
         params.ySize);
 }
Member Data Documentation
indexBuffer
Chronos::Engine::Buffer Chronos::Engine::Shape::indexBuffer
The index buffer that is used to store the indices.
Definition at line 86 of file shape.hpp.
indices
std::vector<uint16_t> Chronos::Engine::Shape::indices
The indices that is used to specify the order of vertices to render.
Definition at line 66 of file shape.hpp.
params
Chronos::Engine::ShapeParams Chronos::Engine::Shape::params
The parameters that are associated with the shape.
Definition at line 28 of file shape.hpp.
texture
Chronos::Engine::Texture Chronos::Engine::Shape::texture
The texture that is to be used.
Definition at line 71 of file shape.hpp.
vertexBuffer
Chronos::Engine::Buffer Chronos::Engine::Shape::vertexBuffer
The vertex buffer that is used to store the vertices.
Definition at line 81 of file shape.hpp.
vertices
std::vector<Vertex> Chronos::Engine::Shape::vertices
The vertices that is used to render the shape.
Definition at line 76 of file shape.hpp.
The documentation for this class was generated from the following files:
Source/Engine/Headers/shape.hpp
Source/Engine/Source/shape.cpp