Chronos: Chronos::Manager::Manager Class Reference
Chronos::Manager::Manager Class Reference
The main manager of chronos.
#include <chronos.hpp>
Public Member Functions
Manager (Initializer initializer)
Constructor for chronos. The initalizer struct with the necessary options to be passed.
GLFWwindow * getWindow ()
Gets a reference to the GLFWWindow.
void drawFrame ()
Draws the current frame to the window.
int addText (Chronos::Engine::TextParams params, std::string fontType, int fontSize)
Adds text to the window.
int addPolygon (Chronos::Manager::ShapeParams shapeParams, PolygonType polygonType, int texture)
Adds a textured shape(triangle or rectangle) to the window.
int addPolygon (Chronos::Manager::ShapeParams shapeParams, PolygonType polygonType)
Adds a soild color shape(triangle or rectangle) to the window.
int addPolygon (Chronos::Manager::ShapeParams shapeParams, int texture, std::vector< std::array< float, 2 >> vertices)
Adds a custom textured polygon with arbitary vertices to the window.
void updatePolygon (int shapeNo, Chronos::Manager::ShapeParams shapeParams)
Updates the polygon(any) with the new parameters.
void updatePolygon (int shapeNo, Chronos::Manager::ShapeParams shapeParams, std::vector< std::array< float, 2 >> vertices)
Updates the polygon(npolygon) with the new parameters.
std::vector< std::pair< int, Chronos::Manager::ShapeParams > > getPolygonDetails ()
Returns the details of all npolygon shapes defined.
std::vector< std::pair< int, Chronos::Manager::ShapeParams > > getShapeDetails ()
Returns the details of all shapes(triangle or rectangle) defined.
void updateText (int textNo, Chronos::Engine::TextParams params)
Updates the text with the new parameters.
std::vector< std::pair< int, Chronos::Engine::TextParams > > getTextDetails ()
Returns the details of all text defined.
void removePolygon (int shapeNo)
Removes the polygon from the window.
void removeText (int textNo)
Removes the text from the window.
int changeBackgroundColor (float r, float g, float b)
Changes the background color of the window.
int addTexture (std::string texturePath, std::string textureName)
Loads a texture from file.
void removeTexture (int textureNo)
Removes the texture from the window.
std::vector< TextureDetails > getTextureDetails ()
Returns the details of all textures defined.
std::vector< std::array< float, 2 > > getPolygonVertices (int polygonNo)
void changePresentMode (std::string presentMode)
Changes the present mode of the swapchain.
std::vector< std::string > getMSAAModes ()
void changeMSAA (std::string mode)
int addRig (int x, int y)
void removeRig (int rigNo)
void rigAddBone (int rigNo, int parentNo)
void rigRemoveBone (int rigNo, int boneNo)
void rigAddChild (int rigNo, int parentNo, int childNo)
void rigRemoveChild (int rigNo, int parentNo, int childNo)
void rigSetRelX (int rigNo, int boneNo, float relX)
void rigSetRelY (int rigNo, int boneNo, float relY)
void rigSetLength (int rigNo, int boneNo, float length)
void rigSetAngle (int rigNo, int boneNo, float angle)
void rigSetParent (int rigNo, int boneNo, int parentNo)
float rigGetRelX (int rigNo, int boneNo)
float rigGetRelY (int rigNo, int boneNo)
float rigGetLength (int rigNo, int boneNo)
float rigGetAngle (int rigNo, int boneNo)
float rigGetX (int rigNo, int boneNo)
float rigGetY (int rigNo, int boneNo)
int rigGetParent (int rigNo, int boneNo)
std::vector< int > rigGetChildren (int rigNo, int boneNo)
int addKeyframeVariable (std::vector< std::pair< float, float >> keyframes)
void removeKeyframeVariable (int keyframeNo)
void keyframeSetTime (int keyframeNo, float time)
void keyframeSetKeyframe (int keyframeNo, int keyframe)
int keyframeGetKeyframe (int keyframeNo)
std::vector< std::pair< float, float > > getKeyframes (int keyframeNo)
float keyframeGetVariable (int keyframeNo)
Private Attributes
Chronos::Engine::Engine engine
The backend Vulkan engine, used for rendering the desired shapes and text.s.
Chronos::Animation::AnimationManager animManager
Detailed Description
The main manager of chronos.
Only this class must be used for interfacing with chronos. Do not use the internal classes for this Any changes to the window can be done via this object. Please use only the functions and variables in this class. For more information, refer to the individual methods and variables and the examples
Definition at line 138 of file chronos.hpp.
Constructor & Destructor Documentation
Manager()
Chronos::Manager::Manager::Manager (Initializer initializer)
Constructor for chronos. The initalizer struct with the necessary options to be passed.
For options, refer to the Initializer struct
Definition at line 31 of file manager.cpp.
 {
     // check whether the bg color is between 0 and 1
     if (initializer.BackgroundColor[0] < 0 || initializer.BackgroundColor[0] > 1 || initializer.BackgroundColor[1] < 0 || initializer.BackgroundColor[1] > 1 || initializer.BackgroundColor[2] < 0 || initializer.BackgroundColor[2] > 1) {
         throw std::runtime_error("Invalid background color");
     }
     engine.bgColor[0] = initializer.BackgroundColor[0];
     engine.bgColor[1] = initializer.BackgroundColor[1];
     engine.bgColor[2] = initializer.BackgroundColor[2];
     if (initializer.WindowWidth <= 0 || initializer.WindowHeight <= 0) {
         throw std::runtime_error("Invalid window size");
     }
     engine.width = initializer.WindowWidth;
     engine.height = initializer.WindowHeight;
 #ifdef ENABLE_EDITOR
     engine.setEditorAddElementsCallback(initializer.editorAddElements);
 #endif
 }
References Chronos::Manager::Initializer::BackgroundColor, Chronos::Manager::Initializer::WindowHeight, and Chronos::Manager::Initializer::WindowWidth.
Member Function Documentation
addKeyframeVariable()
int Chronos::Manager::Manager::addKeyframeVariable (std::vector< std::pair< float, float >> keyframes) inline
Definition at line 527 of file chronos.hpp.
{
             return animManager.addKeyframeVariable(keyframes);
         }
References animManager.
addPolygon() [1/3]
int Chronos::Manager::Manager::addPolygon (Chronos::Manager::ShapeParams shapeParams, int texture, std::vector< std::array< float, 2 >> vertices)
Adds a custom textured polygon with arbitary vertices to the window.
Use this to add a custom polygon to the window. Please note that this function only supports textured shapes.
Options for the shape are defined in the ShapeParams struct. The color field in the struct is not used, It can be skipped. The texture field must be set to the textureNo of the texture to be used. For options related to the shape, please refer the struct. A texture path must be selected. To add other types of shapes, such as colored or npolygon, use the other overrides available. The vertices must be defined in the vertices vector. The vertices must be defined in the order of the polygon. The first vertex is the starting point of the polygon. The number of vertices shall be fixed. However their values may be changed using the updatePolygon function.
It returns a shapeNo that can be used for modifying the shape in other functions in this class
Parameters
shapeParams The parameters(x, y, rotation... etc) for the shape
texture The textureNo of the texture to be used
Returns
Returns the shapeNo that can be used for referencing this shape later.
Definition at line 61 of file managerShapeFunctions.cpp.
 {
     // this fucntion is for npolygons only
     int shapeNo;
     // check to make sure the texture exists
     std::vector<Chronos::Manager::TextureDetails> textureDetails = getTextureDetails();
     bool textureExists = false;
     for (auto& textureDetail : textureDetails) {
         if (textureDetail.textureNo == texture) {
             textureExists = true;
             break;
         }
     }
     if (!textureExists) {
         throw std::runtime_error("Texture does not exist");
     }
     // check whether shape name exists
     for (auto& shape : engine.shapeManager.objects) {
         if (strcmp(shape.second.params.shapeName, shapeParams.shapeName) == 0) {
             throw std::runtime_error("Shape name already exists");
         }
     }
     if (!textureExists) {
         throw std::runtime_error("Texture does not exist");
     }
     shapeNo = engine.polygonManager.addPolygon(shapeParams, vertices, engine.textureManager.getTexture(texture));
     // we add 3 to shapeNo to know they are textured npolygons
     shapeNo = std::stoi("3" + std::to_string(shapeNo));
     return shapeNo;
 }
References Chronos::Manager::ShapeParams::shapeName.
addPolygon() [2/3]
int Chronos::Manager::Manager::addPolygon (Chronos::Manager::ShapeParams shapeParams, PolygonType polygonType)
Adds a soild color shape(triangle or rectangle) to the window.
Use this to add a shape(triangle or rectangle) to the window. Please note that this function only supports solid color shapes.
Options for the shape are defined in the ShapeParams struct. The color field in the struct must be filled. For options related to the shape, please refer the struct. In order to choose between triangle and rectangle, the option must be set in polygonType. Do not select npolygon, as it is not supported in this function. To add other types of shapes, such as textured or npolygon, use the other overrides available.
It returns a shapeNo that can be used for modifying the shape in other functions in this class
Parameters
shapeParams The parameters(x, y, rotation... etc) for the shape
polygonType The type of shape(triangle or rectangle)
Returns
Returns the shapeNo that can be used for referencing this shape later.
Definition at line 97 of file managerShapeFunctions.cpp.
 {
     // this function is for colored triangles and rectangles only
     // check whether shape name exists
     for (auto& shape : engine.shapeManager.objects) {
         if (strcmp(shape.second.params.shapeName, shapeParams.shapeName) == 0) {
             throw std::runtime_error("Shape name already exists");
         }
     }
     int shapeNo;
     if (polygonType.triangle) {
         shapeNo = engine.colorShapeManager.addTriangle(shapeParams);
     } else if (polygonType.rectangle) {
         shapeNo = engine.colorShapeManager.addRectangle(shapeParams);
     } else {
         throw std::runtime_error("Polygon type not supported");
     }
     // we add 2 to shapeNo to know they are colored triangles or rectangles
     shapeNo = std::stoi("2" + std::to_string(shapeNo));
     return shapeNo;
 }
References Chronos::Manager::PolygonType::rectangle, Chronos::Manager::ShapeParams::shapeName, and Chronos::Manager::PolygonType::triangle.
addPolygon() [3/3]
int Chronos::Manager::Manager::addPolygon (Chronos::Manager::ShapeParams shapeParams, PolygonType polygonType, int texture)
Adds a textured shape(triangle or rectangle) to the window.
Use this to add a shape(triangle or rectangle) to the window. Please note that this function only supports textured shapes.
Options for the shape are defined in the ShapeParams struct. The color field in the struct is not used, It can be skipped. The texture field must be set to the textureNo of the texture to be used. For options related to the shape, please refer the struct. In order to choose between triangle and rectangle, the option must be set in polygonType. Do not select npolygon, as it is not supported in this function. A texture path must be selected. To add other types of shapes, such as colored or npolygon, use the other overrides available.
It returns a shapeNo that can be used for modifying the shape in other functions in this class
Parameters
shapeParams The parameters(x, y, rotation... etc) for the shape
polygonType The type of shape(triangle or rectangle)
texture The textureNo of the texture to be used
Returns
Returns the shapeNo that can be used for referencing this shape later.
Definition at line 25 of file managerShapeFunctions.cpp.
 {
     // this function is for textured triangles and rectangles only
     // we need to add a check for the texture
     std::vector<Chronos::Manager::TextureDetails> textureDetails = getTextureDetails();
     bool textureExists = false;
     for (auto& textureDetail : textureDetails) {
         if (textureDetail.textureNo == texture) {
             textureExists = true;
             break;
         }
     }
     if (!textureExists) {
         throw std::runtime_error("Texture does not exist");
     }
     // check whether shape name exists
     for (auto& shape : engine.shapeManager.objects) {
         if (strcmp(shape.second.params.shapeName, shapeParams.shapeName) == 0) {
             throw std::runtime_error("Shape name already exists");
         }
     }
     int shapeNo;
     if (polygonType.triangle) {
         shapeNo = engine.shapeManager.addTriangle(shapeParams, engine.textureManager.getTexture(texture));
     } else if (polygonType.rectangle) {
         shapeNo = engine.shapeManager.addRectangle(shapeParams, engine.textureManager.getTexture(texture));
     } else {
         throw std::runtime_error("Polygon type not supported");
     }
     // we add 1 to shapeNo to know they are textured triangles or rectangles
     shapeNo = std::stoi("1" + std::to_string(shapeNo));
     return shapeNo;
 }
References engine, Chronos::Engine::TextureManager::getTexture(), getTextureDetails(), Chronos::Manager::PolygonType::rectangle, Chronos::Engine::Engine::shapeManager, Chronos::Manager::ShapeParams::shapeName, Chronos::Engine::Engine::textureManager, and Chronos::Manager::PolygonType::triangle.
addRig()
int Chronos::Manager::Manager::addRig (int x, int y) inline
Definition at line 451 of file chronos.hpp.
{
             return animManager.addRig(x, y);
         }
References animManager.
addText()
int Chronos::Manager::Manager::addText (Chronos::Engine::TextParams params, std::string fontType, int fontSize)
Adds text to the window.
If you want to add text to the window, this function must be used. It returns a textNo, that is used for updating, modifyign and removing the text instance One may select the fontType and fontSize from the available options. The fontType and fontSize must be selected from the available options. Font size may be from 6 to 50. The fontType may be one of the following:
arial
arial_bold
consolas
consolas_bold
courier
courier_bold
times
times_bold
An example of how this function is called is:
addText(params, "arial", 12);
In the above, params refer to the text parameters that are assumed to be defined and filled. The necessary functions must be defined in the struct. For the options, please refer to the Text struct
Parameters
params The necessary parameters needed for rendering text
Returns
The textNo, for the text instance.
Definition at line 26 of file managerTextFunctions.cpp.
 {
     if (params.text == "") {
         throw std::runtime_error("Text cannot be empty");
     }
     // Chronos::Engine::Text font;
     Chronos::Engine::Text font;
     font.params = params;
     Chronos::Engine::FontTypes fontStyle = Chronos::Engine::getFontType(fontType, fontSize);
     return engine.textManager.addFont(font, fontStyle);
 }
References Chronos::Engine::TextManager::addFont(), engine, Chronos::Engine::getFontType(), Chronos::Engine::Text::params, Chronos::Engine::TextParams::text, and Chronos::Engine::Engine::textManager.
addTexture()
int Chronos::Manager::Manager::addTexture (std::string texturePath, std::string textureName)
Loads a texture from file.
If a texture is needed to be loaded from a file, then this function can be used. The texture is loaded from the file and added to the texture manager. The textureNo is returned, which can be used for referencing the texture in other functions.
Note: Only png and jpg files are supported.
Parameters
texturePath The path of the texture file
textureName The name of the texture. This must be unique.
Definition at line 25 of file managerTextureFunctions.cpp.
 {
     for (auto& textureDetail : getTextureDetails()) {
         if (textureDetail.textureName == textureName) {
             break;
         }
     }
     return engine.textureManager.addTexture(texturePath, textureName);
 }
References Chronos::Engine::TextureManager::addTexture(), engine, getTextureDetails(), and Chronos::Engine::Engine::textureManager.
changeBackgroundColor()
int Chronos::Manager::Manager::changeBackgroundColor (float r, float g, float b)
Changes the background color of the window.
If changing the background color of the window is desired, then by passing the RGB values to this function, it may be accomplished.
Parameters
r Red value
g Green value
b Blue value
Definition at line 58 of file manager.cpp.
 {
     if (r < 0 || r > 1 || g < 0 || g > 1 || b < 0 || b > 1) {
         throw std::runtime_error("Invalid background color");
     }
     engine.bgColor[0] = r;
     engine.bgColor[1] = g;
     engine.bgColor[2] = b;
     return 0;
 }
changeMSAA()
void Chronos::Manager::Manager::changeMSAA (std::string mode) inline
Definition at line 447 of file chronos.hpp.
{
             engine.changeMSAA(mode);
         }
References Chronos::Engine::Engine::changeMSAA(), and engine.
changePresentMode()
void Chronos::Manager::Manager::changePresentMode (std::string presentMode) inline
Changes the present mode of the swapchain.
The present mode is the mode in which the images are presented to the screen. There are various methods available. this can be used to cap or unlock the framerate, control tearing etc. Some of the presentation modes available are:
immediate: Images submitted by your application are transferred to the screen right away, which may result in tearing.
fifo : The swap chain is a queue where the display takes an image from the front of the queue when the display is refreshed and the program inserts rendered images at the back of the queue.If the queue is full then the program has to wait. This is most similar to vertical sync as found in modern games.The moment that the display is refreshed is known as "vertical blank".
fifo_relaxed : This mode only differs from the previous one if the application is late and the queue was empty at the last vertical blank. Instead of waiting for the next vertical blank, the image is transferred right away when it finally arrives.This may result in visible tearing.
mailbox : This is another variation of the second mode.Instead of blocking the application when the queue is full, the images that are already queued are simply replaced with the newer ones.This mode can be used to render frames as fast as possible while still avoiding tearing, resulting in fewer latency issues than standard vertical sync.This is commonly known as "triple buffering", although the existence of three buffers alone does not necessarily mean that the framerate
Parameters
mode The mode to change to. It can be one of the following:
immediate
fifo
fifo_relaxed
mailbox
Definition at line 439 of file chronos.hpp.
{
             engine.setPresentMode(presentMode);
         }
References engine, and Chronos::Engine::Engine::setPresentMode().
drawFrame()
void Chronos::Manager::Manager::drawFrame ()
Draws the current frame to the window.
This must called every frame during the game loop.
This function updates all the attributes of the objects defined by the user and submitted to chronos. It then submits sthe necessary information to the GPU to render the frame.
Definition at line 53 of file manager.cpp.
 {
     animManager.update();
     engine.drawFrame();
 }
getKeyframes()
std::vector<std::pair<float, float> > Chronos::Manager::Manager::getKeyframes (int keyframeNo) inline
Definition at line 547 of file chronos.hpp.
{
             return animManager.getKeyframes(keyframeNo);
         }
References animManager.
getMSAAModes()
std::vector<std::string> Chronos::Manager::Manager::getMSAAModes () inline
Definition at line 443 of file chronos.hpp.
{
             return engine.getAvailableMSAAModes();
         }
References engine, and Chronos::Engine::Engine::getAvailableMSAAModes().
getPolygonDetails()
std::vector< std::pair< int, Chronos::Manager::ShapeParams > > Chronos::Manager::Manager::getPolygonDetails ()
Returns the details of all npolygon shapes defined.
If the details of the npolygon shapes are needed, this function can be used to get the details of all npolygon shapes. It returns a vector of pairs, where the first element is the shapeNo and the second element is the shapeParams.
Returns
A vector of pairs, where the first element is the shapeNo and the second element is the shapeParams of the corresponding polygon.
Definition at line 177 of file managerShapeFunctions.cpp.
 {
     // get the details of the npolygons
     std::vector<std::pair<int, Chronos::Manager::ShapeParams>> shapeDetails;
     for (auto& shape : engine.polygonManager.objects) {
         std::pair<int, Chronos::Manager::ShapeParams> shapeDetail;
         shapeDetail.first = std::stoi("3" + std::to_string(shape.first));
         shapeDetail.second = shape.second.params;
         shapeDetails.push_back(shapeDetail);
     }
     return shapeDetails;
 }
getPolygonVertices()
std::vector< std::array< float, 2 > > Chronos::Manager::Manager::getPolygonVertices (int polygonNo)
Definition at line 191 of file managerShapeFunctions.cpp.
 {
     if (std::to_string(polygonNo).substr(0, 1) == "3") { // textured npolygons
         int actualPolygonNo = polygonNo - 3 * (10 * (std::to_string(polygonNo).size() - 1));
         if (engine.polygonManager.objects.count(actualPolygonNo) == 0) {
             throw std::runtime_error("Shape does not exist");
         }
         std::vector<Chronos::Engine::TexturedVertex> texturedVertices = engine.polygonManager.objects[actualPolygonNo].vertices;
         std::vector<std::array<float, 2>> vertices;
         for (Chronos::Engine::TexturedVertex vertex : texturedVertices) {
             vertices.push_back({ vertex.pos[0], vertex.pos[1] });
         }
         return vertices;
     } else {
         throw std::runtime_error("Shape does not exist");
     }
 }
getShapeDetails()
std::vector< std::pair< int, Chronos::Manager::ShapeParams > > Chronos::Manager::Manager::getShapeDetails ()
Returns the details of all shapes(triangle or rectangle) defined.
If the details of the shapes(triangle or rectangle) are needed, this function can be used to get the details of all shapes. It returns a vector of pairs, where the first element is the shapeNo and the second element is the shapeParams.
Note: This function does not return the details of npolygon shapes. For npolygon shapes, use the other override.
Note: This will return both textured and colored shapes.
Returns
A vector of pairs, where the first element is the shapeNo and the second element is the shapeParams of the corresponding polygon.
Definition at line 159 of file managerShapeFunctions.cpp.
 {
     std::vector<std::pair<int, Chronos::Manager::ShapeParams>> shapeDetails;
     // we need both colored and textured triangles and rectangles
     for (auto& shape : engine.shapeManager.objects) {
         std::pair<int, Chronos::Manager::ShapeParams> shapeDetail;
         shapeDetail.first = std::stoi("1" + std::to_string(shape.first));
         shapeDetail.second = shape.second.params;
         shapeDetails.push_back(shapeDetail);
     }
     for (auto& shape : engine.colorShapeManager.objects) {
         std::pair<int, Chronos::Manager::ShapeParams> shapeDetail;
         shapeDetail.first = std::stoi("2" + std::to_string(shape.first));
         shapeDetail.second = shape.second.params;
         shapeDetails.push_back(shapeDetail);
     }
     return shapeDetails;
 }
getTextDetails()
std::vector< std::pair< int, Chronos::Engine::TextParams > > Chronos::Manager::Manager::getTextDetails ()
Returns the details of all text defined.
If the details of the text are needed, this function can be used to get the details of all text. It returns a vector of pairs, where the first element is the textNo and the second element is the textParams.
Returns
A vector of pairs, where the first element is the textNo and the second element is the textParams of the corresponding text.
Definition at line 56 of file managerTextFunctions.cpp.
 {
     std::vector<std::pair<int, Chronos::Engine::TextParams>> textDetails;
     for (auto& text : engine.textManager.objects) {
         std::pair<int, Chronos::Engine::TextParams> textDetail;
         textDetail.first = text.first;
         textDetail.second = text.second.params;
         textDetails.push_back(textDetail);
     }
     return textDetails;
 }
getTextureDetails()
std::vector< Chronos::Manager::TextureDetails > Chronos::Manager::Manager::getTextureDetails ()
Returns the details of all textures defined.
If the details of the textures are needed, this function can be used to get the details of all textures. It returns a vector of TextureDetails, where the textureName, texturePath and textureNo are returned.
Returns
A vector of TextureDetails, where the textureName, texturePath and textureNo are returned.
Definition at line 39 of file managerTextureFunctions.cpp.
 {
     std::vector<Chronos::Manager::TextureDetails> textureDetails;
     for (auto& texture : engine.textureManager.textures) {
         Chronos::Manager::TextureDetails details;
         details.textureNo = texture.first;
         details.textureName = texture.second.textureName;
         details.texturePath = texture.second.texturePath;
         details.height = texture.second.height;
         details.width = texture.second.width;
 #ifdef ENABLE_EDITOR
         details.descriptorSet = texture.second.descriptorSet;
 #endif
         textureDetails.push_back(details);
     }
     return textureDetails;
 }
References Chronos::Manager::TextureDetails::height, Chronos::Manager::TextureDetails::textureName, Chronos::Manager::TextureDetails::textureNo, Chronos::Manager::TextureDetails::texturePath, and Chronos::Manager::TextureDetails::width.
getWindow()
GLFWwindow * Chronos::Manager::Manager::getWindow ()
Gets a reference to the GLFWWindow.
Since Chronos initialzes the window, along with managing it, the window is with chronos.
However for input handling and advanced window management, chronos will not do this. Instead you are expected to directly call the GLFW functions and define the options yourself.
Returns
The GLFWWindow instance created and used by Chronos
Definition at line 27 of file manager.cpp.
 {
     return engine.window;
 }
References engine, and Chronos::Engine::Engine::window.
keyframeGetKeyframe()
int Chronos::Manager::Manager::keyframeGetKeyframe (int keyframeNo) inline
Definition at line 543 of file chronos.hpp.
{
             return animManager.keyframeGetKeyframe(keyframeNo);
         }
References animManager.
keyframeGetVariable()
float Chronos::Manager::Manager::keyframeGetVariable (int keyframeNo) inline
Definition at line 551 of file chronos.hpp.
{
             return animManager.keyframeGetVariable(keyframeNo);
         }
References animManager.
keyframeSetKeyframe()
void Chronos::Manager::Manager::keyframeSetKeyframe (int keyframeNo, int keyframe) inline
Definition at line 539 of file chronos.hpp.
{
             animManager.keyframeSetKeyframe(keyframeNo, keyframe);
         }
References animManager.
keyframeSetTime()
void Chronos::Manager::Manager::keyframeSetTime (int keyframeNo, float time) inline
Definition at line 535 of file chronos.hpp.
{
             animManager.keyframeSetTime(keyframeNo, time);
         }
References animManager.
removeKeyframeVariable()
void Chronos::Manager::Manager::removeKeyframeVariable (int keyframeNo) inline
Definition at line 531 of file chronos.hpp.
{
             animManager.removeKeyframeVariable(keyframeNo);
         }
References animManager.
removePolygon()
void Chronos::Manager::Manager::removePolygon (int shapeNo)
Removes the polygon from the window.
By referencing the shapeNo, the manager removes and destroys the shape from the screen. This applies to all types of shapes.
Parameters
shapeNo The reference to the shape
Definition at line 209 of file managerShapeFunctions.cpp.
 {
     if (std::to_string(shapeNo).substr(0, 1) == "1") { // textured triangles and rectangles
         int actualShapeNo = shapeNo - 1 * (10 * (std::to_string(shapeNo).size() - 1));
         if (engine.shapeManager.objects.count(actualShapeNo) == 0) {
             throw std::runtime_error("Shape does not exist");
         }
         engine.shapeManager.remove(actualShapeNo);
     } else if (std::to_string(shapeNo).substr(0, 1) == "2") { // colored triangles and rectangles
         int actualShapeNo = shapeNo - 2 * (10 * (std::to_string(shapeNo).size() - 1));
         if (engine.colorShapeManager.objects.count(actualShapeNo) == 0) {
             throw std::runtime_error("Shape does not exist");
         }
         engine.colorShapeManager.remove(actualShapeNo);
     } else if (std::to_string(shapeNo).substr(0, 1) == "3") { // textured npolygons
         int actualShapeNo = shapeNo - 3 * (10 * (std::to_string(shapeNo).size() - 1));
         if (engine.polygonManager.objects.count(actualShapeNo) == 0) {
             throw std::runtime_error("Shape does not exist");
         }
         engine.polygonManager.remove(actualShapeNo);
     } else {
         throw std::runtime_error("Shape does not exist");
     }
 }
removeRig()
void Chronos::Manager::Manager::removeRig (int rigNo) inline
Definition at line 455 of file chronos.hpp.
{
             animManager.removeRig(rigNo);
         }
References animManager.
removeText()
void Chronos::Manager::Manager::removeText (int textNo)
Removes the text from the window.
By referencing the textNo, the manager removes and destroys the text from the screen.
Definition at line 50 of file managerTextFunctions.cpp.
 {
     engine.textManager.remove(textNo);
 }
removeTexture()
void Chronos::Manager::Manager::removeTexture (int textureNo)
Removes the texture from the window.
By referencing the textureNo, the manager removes and destroys the texture from the screen.
Parameters
textureNo The reference to the texture
Definition at line 34 of file managerTextureFunctions.cpp.
 {
     engine.textureManager.removeTexture(textureNo);
 }
rigAddBone()
void Chronos::Manager::Manager::rigAddBone (int rigNo, int parentNo) inline
Definition at line 459 of file chronos.hpp.
{
             animManager.rigAddBone(rigNo, parentNo);
         }
References animManager.
rigAddChild()
void Chronos::Manager::Manager::rigAddChild (int rigNo, int parentNo, int childNo) inline
Definition at line 467 of file chronos.hpp.
{
             animManager.rigAddChild(rigNo, parentNo, childNo);
         }
References animManager.
rigGetAngle()
float Chronos::Manager::Manager::rigGetAngle (int rigNo, int boneNo) inline
Definition at line 507 of file chronos.hpp.
{
             return animManager.rigGetAngle(rigNo, boneNo);
         }
References animManager.
rigGetChildren()
std::vector<int> Chronos::Manager::Manager::rigGetChildren (int rigNo, int boneNo) inline
Definition at line 523 of file chronos.hpp.
{
             return animManager.rigGetChildren(rigNo, boneNo);
         }
References animManager.
rigGetLength()
float Chronos::Manager::Manager::rigGetLength (int rigNo, int boneNo) inline
Definition at line 503 of file chronos.hpp.
{
             return animManager.rigGetLength(rigNo, boneNo);
         }
References animManager.
rigGetParent()
int Chronos::Manager::Manager::rigGetParent (int rigNo, int boneNo) inline
Definition at line 519 of file chronos.hpp.
{
             return animManager.rigGetParent(rigNo, boneNo);
         }
References animManager.
rigGetRelX()
float Chronos::Manager::Manager::rigGetRelX (int rigNo, int boneNo) inline
Definition at line 495 of file chronos.hpp.
{
             return animManager.rigGetRelX(rigNo, boneNo);
         }
References animManager.
rigGetRelY()
float Chronos::Manager::Manager::rigGetRelY (int rigNo, int boneNo) inline
Definition at line 499 of file chronos.hpp.
{
             return animManager.rigGetRelY(rigNo, boneNo);
         }
References animManager.
rigGetX()
float Chronos::Manager::Manager::rigGetX (int rigNo, int boneNo) inline
Definition at line 511 of file chronos.hpp.
{
             return animManager.rigGetX(rigNo, boneNo);
         }
References animManager.
rigGetY()
float Chronos::Manager::Manager::rigGetY (int rigNo, int boneNo) inline
Definition at line 515 of file chronos.hpp.
{
             return animManager.rigGetY(rigNo, boneNo);
         }
References animManager.
rigRemoveBone()
void Chronos::Manager::Manager::rigRemoveBone (int rigNo, int boneNo) inline
Definition at line 463 of file chronos.hpp.
{
             animManager.rigRemoveBone(rigNo, boneNo);
         }
References animManager.
rigRemoveChild()
void Chronos::Manager::Manager::rigRemoveChild (int rigNo, int parentNo, int childNo) inline
Definition at line 471 of file chronos.hpp.
{
             animManager.rigRemoveChild(rigNo, parentNo, childNo);
         }
References animManager.
rigSetAngle()
void Chronos::Manager::Manager::rigSetAngle (int rigNo, int boneNo, float angle) inline
Definition at line 487 of file chronos.hpp.
{
             animManager.rigSetAngle(rigNo, boneNo, angle);
         }
References animManager.
rigSetLength()
void Chronos::Manager::Manager::rigSetLength (int rigNo, int boneNo, float length) inline
Definition at line 483 of file chronos.hpp.
{
             animManager.rigSetLength(rigNo, boneNo, length);
         }
References animManager.
rigSetParent()
void Chronos::Manager::Manager::rigSetParent (int rigNo, int boneNo, int parentNo) inline
Definition at line 491 of file chronos.hpp.
{
             animManager.rigSetParent(rigNo, boneNo, parentNo);
         }
References animManager.
rigSetRelX()
void Chronos::Manager::Manager::rigSetRelX (int rigNo, int boneNo, float relX) inline
Definition at line 475 of file chronos.hpp.
{
             animManager.rigSetRelX(rigNo, boneNo, relX);
         }
References animManager.
rigSetRelY()
void Chronos::Manager::Manager::rigSetRelY (int rigNo, int boneNo, float relY) inline
Definition at line 479 of file chronos.hpp.
{
             animManager.rigSetRelY(rigNo, boneNo, relY);
         }
References animManager.
updatePolygon() [1/2]
void Chronos::Manager::Manager::updatePolygon (int shapeNo, Chronos::Manager::ShapeParams shapeParams)
Updates the polygon(any) with the new parameters.
After initializing the shape, if you want to change the parameters of the shape to new attributes, using the shapeNo and passing the shapeParams, the new parameters can be propogated to the shape. The results will be displayed on the next drawFrame() call.
Note:
If textured shape is chosen then the color field will have no effect on the shape. The texture will be always be displayed.
Note:
This function cannot update the vertices of npolygon. To update the vertices of npolygon, use the other override.
Parameters
shapeNo The shapeNo reference to the shape. Generated during `addPolygon() call.
shapeParams The updated shape parameters to update the shape with.
Definition at line 120 of file managerShapeFunctions.cpp.
 {
     if (std::to_string(shapeNo).substr(0, 1) == "1") { // textured triangles and rectangles
         int actualShapeNo = shapeNo - 1 * (10 * (std::to_string(shapeNo).size() - 1));
         if (engine.shapeManager.objects.count(actualShapeNo) == 0) {
             throw std::runtime_error("Shape does not exist");
         }
         engine.shapeManager.objects[actualShapeNo].params = shapeParams;
     } else if (std::to_string(shapeNo).substr(0, 1) == "3") { // textured npolygons
         int actualShapeNo = shapeNo - 3 * (10 * (std::to_string(shapeNo).size() - 1));
         if (engine.polygonManager.objects.count(actualShapeNo) == 0) {
             throw std::runtime_error("Shape does not exist");
         }
         engine.polygonManager.objects[actualShapeNo].params = shapeParams;
     } else if (std::to_string(shapeNo).substr(0, 1) == "2") { // colored triangles and rectangles
         int actualShapeNo = shapeNo - 2 * (10 * (std::to_string(shapeNo).size() - 1));
         if (engine.colorShapeManager.objects.count(actualShapeNo) == 0) {
             throw std::runtime_error("Shape does not exist");
         }
         engine.colorShapeManager.objects[actualShapeNo].params = shapeParams;
     } else {
         throw std::runtime_error("Shape does not exist");
     }
 }
updatePolygon() [2/2]
void Chronos::Manager::Manager::updatePolygon (int shapeNo, Chronos::Manager::ShapeParams shapeParams, std::vector< std::array< float, 2 >> vertices)
Updates the polygon(npolygon) with the new parameters.
After initializing the shape, if you want to change the parameters of the shape to new attributes, using the shapeNo and passing the shapeParams, the new parameters can be propogated to the shape.
The vertices can also be updated. Please note that the number of vertices must remain the same. However their values may be changed.
The results will be displayed on the next drawFrame() call.
Note:
Yhe color field will have no effect on the shape. The texture will be always be displayed.
Note:
This function can be only used with npolygon shape. For rectangle or triangle, use the other override.
Note:
The number of vertices must remain the same. However their values may be changed.
Parameters
shapeNo The shapeNo reference to the shape. Generated during `addPolygon() call.
shapeParams The updated shape parameters to update the shape with.
vertices The updated vertices of the polygon.
Definition at line 145 of file managerShapeFunctions.cpp.
 {
     if (std::to_string(shapeNo).substr(0, 1) == "3") { // textured npolygons
         int actualShapeNo = shapeNo - 3 * (10 * (std::to_string(shapeNo).size() - 1));
         if (engine.polygonManager.objects.count(actualShapeNo) == 0) {
             throw std::runtime_error("Shape does not exist");
         }
         engine.polygonManager.objects[actualShapeNo].params = shapeParams;
         engine.polygonManager.objects[actualShapeNo].updateVertices(vertices);
     } else {
         throw std::runtime_error("Shape does not exist");
     }
 }
updateText()
void Chronos::Manager::Manager::updateText (int textNo, Chronos::Engine::TextParams params)
Updates the text with the new parameters.
After initializing the text, if you want to change the parameters of the text to new attributes, using the textNo and passing the textParams, the new parameters can be propogated to the text. The results will be displayed on the next drawFrame() call.
Parameters
textNo The textNo reference to the text. Generated during addText() call.
params The updated text parameters to update the text with.
Definition at line 39 of file managerTextFunctions.cpp.
 {
     if (params.text == "") {
         throw std::runtime_error("Text cannot be empty");
     }
     if (engine.textManager.objects.count(textNo) == 0) {
         throw std::runtime_error("Text does not exist");
     }
     engine.textManager.objects[textNo].params = params;
 }
References Chronos::Engine::TextParams::text.
Member Data Documentation
animManager
Chronos::Animation::AnimationManager Chronos::Manager::Manager::animManager private
Definition at line 583 of file chronos.hpp.
engine
Chronos::Engine::Engine Chronos::Manager::Manager::engine private
The backend Vulkan engine, used for rendering the desired shapes and text.s.
Definition at line 581 of file chronos.hpp.
The documentation for this class was generated from the following files:
include/chronos.hpp
Source/API/Source/manager.cpp
Source/API/Source/managerShapeFunctions.cpp
Source/API/Source/managerTextFunctions.cpp
Source/API/Source/managerTextureFunctions.cpp