Chronos: Chronos::Engine::ColoredRectangle Class Reference
Chronos::Engine::ColoredRectangle Class Reference
#include <ColoredRectangle.hpp>
Public Member Functions
void init (Chronos::Engine::Device *device, VkCommandPool commandPool, Chronos::Engine::SwapChain *swapChain, VkSampler textureSampler, VkRenderPass *renderPass)
void update (uint32_t currentFrame) override
Updates the object for the current frame.
void destroy () override
Destroys the object and releases associated resources.
void render (uint32_t currentFrame, uint32_t imageIndex, float bgColor[3], VkViewport &viewport, VkRect2D &scissor, std::vector< VkCommandBuffer > &commandBuffers) override
Public Member Functions inherited from Chronos::Engine::Object
void init (Chronos::Engine::Device *device, VkCommandPool commandPool, Chronos::Engine::SwapChain *swapChain, VkSampler textureSampler, VkRenderPass *renderPass, ObjectType objectType)
Initializes the object.
void recreateGraphicsPipeline ()
Recreates the graphics pipeline for the object.
Public Attributes
const std::vector< uint16_t > indices = std::vector<uint16_t> { 0, 1, 2, 2, 3, 0 }
Chronos::Manager::ShapeParams params
const std::vector< ColorVertex > vertices
Chronos::Engine::Buffer vertexBuffer
The vertex buffer that is used to store the vertices.
Chronos::Engine::Buffer indexBuffer
The index buffer that is used to store the indices.
Public Attributes inherited from Chronos::Engine::Object
VkPipeline graphicsPipeline
VkPipelineLayout pipelineLayout
std::vector< VkDescriptorSet > descriptorSets
Chronos::Engine::ObjectType objectType
Private Member Functions
void createDescriptorSets () override
std::vector< VkDescriptorType > getDescriptorTypes () override
std::vector< VkShaderStageFlagBits > getDescriptorStages () override
PipelineAttributes getPipelineAttributes () override
Private Attributes
std::vector< Chronos::Engine::ColorBuffer > colorBuffers
Additional Inherited Members
Protected Member Functions inherited from Chronos::Engine::Object
void createGraphicsPipeline ()
Creates the graphics pipeline for the object.
void createDescriptorPool ()
Creates the Vulkan descriptor pool for the object.
void createDescriptorSetLayout ()
Creates the Vulkan descriptor set layout for the object.
Protected Attributes inherited from Chronos::Engine::Object
std::string vertexShaderPath
std::string fragmentShaderPath
Chronos::Engine::Device * device
Chronos::Engine::SwapChain * swapChain
VkCommandPool commandPool
VkSampler textureSampler
VkRenderPass * renderPass
VkDescriptorSetLayout descriptorSetLayout
VkDescriptorPool descriptorPool
std::vector< Chronos::Engine::UniformBuffer > uniformBuffers
Detailed Description
Definition at line 33 of file ColoredRectangle.hpp.
Member Function Documentation
createDescriptorSets()
void Chronos::Engine::ColoredRectangle::createDescriptorSets () override private virtual
Implements Chronos::Engine::Object.
Definition at line 73 of file ColoredRectangle.cpp.
{
    std::vector<VkDescriptorSetLayout> layouts(
    MAX_FRAMES_IN_FLIGHT, descriptorSetLayout);
    VkDescriptorSetAllocateInfo allocInfo {};
    allocInfo.sType = VK_STRUCTURE_TYPE_DESCRIPTOR_SET_ALLOCATE_INFO;
    allocInfo.descriptorPool = descriptorPool;
    allocInfo.descriptorSetCount = static_cast<uint32_t>(MAX_FRAMES_IN_FLIGHT);
    allocInfo.pSetLayouts = layouts.data();
    descriptorSets.resize(MAX_FRAMES_IN_FLIGHT);
    if (vkAllocateDescriptorSets(
        device->device, &allocInfo, descriptorSets.data())
    != VK_SUCCESS) {
    throw std::runtime_error("failed to allocate descriptor sets!");
    }
    for (size_t i = 0; i < MAX_FRAMES_IN_FLIGHT; i++) {
    VkDescriptorBufferInfo bufferInfo {};
    bufferInfo.buffer = uniformBuffers[i].buffer;
    bufferInfo.offset = 0;
    bufferInfo.range = sizeof(UniformBufferObject);
    VkDescriptorBufferInfo bufferInfo2 {};
    bufferInfo2.buffer = colorBuffers[i].buffer;
    bufferInfo2.offset = 0;
    bufferInfo2.range = sizeof(UniformColorBufferObject);
    std::array<VkWriteDescriptorSet, 2> descriptorWrites {};
    descriptorWrites[0].sType = VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET;
    descriptorWrites[0].dstSet = descriptorSets[i];
    descriptorWrites[0].dstBinding = 0;
    descriptorWrites[0].dstArrayElement = 0;
    descriptorWrites[0].descriptorType = VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER;
    descriptorWrites[0].descriptorCount = 1;
    descriptorWrites[0].pBufferInfo = &bufferInfo;
    descriptorWrites[1].sType = VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET;
    descriptorWrites[1].dstSet = descriptorSets[i];
    descriptorWrites[1].dstBinding = 1;
    descriptorWrites[1].dstArrayElement = 0;
    descriptorWrites[1].descriptorType = VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER;
    descriptorWrites[1].descriptorCount = 1;
    descriptorWrites[1].pBufferInfo = &bufferInfo2;
    vkUpdateDescriptorSets(device->device,
        static_cast<uint32_t>(descriptorWrites.size()),
        descriptorWrites.data(), 0, nullptr);
    }
}
References MAX_FRAMES_IN_FLIGHT.
destroy()
void Chronos::Engine::ColoredRectangle::destroy () override virtual
Destroys the object and releases associated resources.
This method is responsible for cleaning up the object's resources, including uniform buffers, descriptor pool, descriptor set layout, graphics pipeline, and pipeline layout.
Implements Chronos::Engine::Object.
Definition at line 63 of file ColoredRectangle.cpp.
{
    vertexBuffer.destroy();
    indexBuffer.destroy();
    for (size_t i = 0; i < MAX_FRAMES_IN_FLIGHT; i++) {
    colorBuffers[i].destroy();
    }
    Chronos::Engine::Object::destroy();
}
References Chronos::Engine::Object::destroy(), and MAX_FRAMES_IN_FLIGHT.
getDescriptorStages()
std::vector< VkShaderStageFlagBits > Chronos::Engine::ColoredRectangle::getDescriptorStages () override private virtual
Implements Chronos::Engine::Object.
Definition at line 131 of file ColoredRectangle.cpp.
{
    return std::vector<VkShaderStageFlagBits> { VK_SHADER_STAGE_VERTEX_BIT,
    VK_SHADER_STAGE_FRAGMENT_BIT };
}
getDescriptorTypes()
std::vector< VkDescriptorType > Chronos::Engine::ColoredRectangle::getDescriptorTypes () override private virtual
Implements Chronos::Engine::Object.
Definition at line 124 of file ColoredRectangle.cpp.
{
    return std::vector<VkDescriptorType> { VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER,
    VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER };
}
getPipelineAttributes()
Chronos::Engine::PipelineAttributes Chronos::Engine::ColoredRectangle::getPipelineAttributes () override private virtual
Implements Chronos::Engine::Object.
Definition at line 138 of file ColoredRectangle.cpp.
{
    Chronos::Engine::PipelineAttributes pipelineAttributes;
    auto bindingDescription = ColorVertex::getBindingDescription();
    auto attributeDescriptions = ColorVertex::getAttributeDescriptions();
    pipelineAttributes.bindingDescriptions.resize(1);
    pipelineAttributes.bindingDescriptions[0] = bindingDescription;
    pipelineAttributes.attributeDescriptions.resize(
    attributeDescriptions.size());
    for (int i = 0; i < static_cast<int>(attributeDescriptions.size()); i++) {
    pipelineAttributes.attributeDescriptions[i] = attributeDescriptions[i];
    }
    pipelineAttributes.topology = VK_PRIMITIVE_TOPOLOGY_TRIANGLE_LIST;
    pipelineAttributes.frontFace = VK_FRONT_FACE_COUNTER_CLOCKWISE;
    pipelineAttributes.colorBlendAttachment.colorWriteMask
    = VK_COLOR_COMPONENT_R_BIT | VK_COLOR_COMPONENT_G_BIT
    | VK_COLOR_COMPONENT_B_BIT | VK_COLOR_COMPONENT_A_BIT;
    pipelineAttributes.colorBlendAttachment.blendEnable = VK_FALSE;
    pipelineAttributes.colorBlendAttachment.srcColorBlendFactor
    = VK_BLEND_FACTOR_ONE;
    pipelineAttributes.colorBlendAttachment.dstColorBlendFactor
    = VK_BLEND_FACTOR_ZERO; // Optional
    pipelineAttributes.colorBlendAttachment.colorBlendOp
    = VK_BLEND_OP_ADD; // Optional
    pipelineAttributes.colorBlendAttachment.srcAlphaBlendFactor
    = VK_BLEND_FACTOR_ONE; // Optional
    pipelineAttributes.colorBlendAttachment.dstAlphaBlendFactor
    = VK_BLEND_FACTOR_ZERO; // Optional
    pipelineAttributes.colorBlendAttachment.alphaBlendOp
    = VK_BLEND_OP_ADD; // Optional
    return pipelineAttributes;
}
References Chronos::Engine::PipelineAttributes::attributeDescriptions, Chronos::Engine::PipelineAttributes::bindingDescriptions, Chronos::Engine::PipelineAttributes::colorBlendAttachment, Chronos::Engine::PipelineAttributes::frontFace, Chronos::Engine::ColorVertex::getAttributeDescriptions(), Chronos::Engine::ColorVertex::getBindingDescription(), and Chronos::Engine::PipelineAttributes::topology.
init()
void Chronos::Engine::ColoredRectangle::init (Chronos::Engine::Device * device, VkCommandPool commandPool, Chronos::Engine::SwapChain * swapChain, VkSampler textureSampler, VkRenderPass * renderPass)
Definition at line 25 of file ColoredRectangle.cpp.
{
    this->vertexShaderPath = SPIV_SHADER_PATH "/colorVert.spv";
    this->fragmentShaderPath = SPIV_SHADER_PATH "/colorFrag.spv";
    colorBuffers.resize(MAX_FRAMES_IN_FLIGHT);
    for (size_t i = 0; i < MAX_FRAMES_IN_FLIGHT; i++) {
    colorBuffers[i].create(*device);
    }
    Chronos::Engine::Object::init(device, commandPool, swapChain,
    textureSampler, renderPass,
    Chronos::Engine::ObjectType::TypeColoredRectangle);
    // create the vertex and index buffers and copy the data
    vertexBuffer.size = sizeof(vertices[0]) * vertices.size();
    vertexBuffer.create(*device,
    VK_BUFFER_USAGE_TRANSFER_DST_BIT | VK_BUFFER_USAGE_VERTEX_BUFFER_BIT,
    VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT);
    vertexBuffer.copy((void*)vertices.data(), commandPool);
    indexBuffer.size = sizeof(indices[0]) * indices.size();
    indexBuffer.create(*device,
    VK_BUFFER_USAGE_TRANSFER_DST_BIT | VK_BUFFER_USAGE_INDEX_BUFFER_BIT,
    VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT);
    indexBuffer.copy((void*)indices.data(), commandPool);
}
References colorBuffers, Chronos::Engine::Object::commandPool, Chronos::Engine::Buffer::copy(), Chronos::Engine::Buffer::create(), Chronos::Engine::Object::device, Chronos::Engine::Object::fragmentShaderPath, indexBuffer, indices, Chronos::Engine::Object::init(), MAX_FRAMES_IN_FLIGHT, Chronos::Engine::Object::renderPass, Chronos::Engine::Buffer::size, Chronos::Engine::Object::swapChain, Chronos::Engine::Object::textureSampler, Chronos::Engine::TypeColoredRectangle, vertexBuffer, Chronos::Engine::Object::vertexShaderPath, and vertices.
render()
void Chronos::Engine::ColoredRectangle::render (uint32_t currentFrame, uint32_t imageIndex, float bgColor[3], VkViewport & viewport, VkRect2D & scissor, std::vector< VkCommandBuffer > & commandBuffers) override virtual
Implements Chronos::Engine::Object.
Definition at line 177 of file ColoredRectangle.cpp.
{
    vkCmdBindPipeline(commandBuffers[currentFrame],
    VK_PIPELINE_BIND_POINT_GRAPHICS, this->graphicsPipeline);
    vkCmdSetViewport(commandBuffers[currentFrame], 0, 1, &viewport);
    vkCmdSetScissor(commandBuffers[currentFrame], 0, 1, &scissor);
    VkBuffer vertexBuffers[] = { this->vertexBuffer.buffer };
    VkDeviceSize offsets[] = { 0 };
    vkCmdBindVertexBuffers(
    commandBuffers[currentFrame], 0, 1, vertexBuffers, offsets);
    vkCmdBindIndexBuffer(commandBuffers[currentFrame], this->indexBuffer.buffer,
    0, VK_INDEX_TYPE_UINT16);
    vkCmdBindDescriptorSets(commandBuffers[currentFrame],
    VK_PIPELINE_BIND_POINT_GRAPHICS, this->pipelineLayout, 0, 1,
    &this->descriptorSets[currentFrame], 0, nullptr);
    vkCmdDrawIndexed(commandBuffers[currentFrame],
    static_cast<uint32_t>(this->indices.size()), 1, 0, 0, 0);
}
update()
void Chronos::Engine::ColoredRectangle::update (uint32_t currentFrame) override virtual
Updates the object for the current frame.
This pure virtual method must be implemented by derived classes to perform any updates required for the object during each frame. The currentFrame parameter represents the index of the current frame in the application.
Parameters
currentFrame Index of the current frame.
Implements Chronos::Engine::Object.
Definition at line 55 of file ColoredRectangle.cpp.
{
    uniformBuffers[currentFrame].update(swapChain->swapChainExtent, params.x,
    params.y, params.rotation, params.xSize, params.ySize);
    colorBuffers[currentFrame].update(
    { params.color[0], params.color[1], params.color[2] });
}
Member Data Documentation
colorBuffers
std::vector<Chronos::Engine::ColorBuffer> Chronos::Engine::ColoredRectangle::colorBuffers private
Definition at line 66 of file ColoredRectangle.hpp.
indexBuffer
Chronos::Engine::Buffer Chronos::Engine::ColoredRectangle::indexBuffer
The index buffer that is used to store the indices.
Definition at line 59 of file ColoredRectangle.hpp.
indices
const std::vector<uint16_t> Chronos::Engine::ColoredRectangle::indices = std::vector<uint16_t> { 0, 1, 2, 2, 3, 0 }
Definition at line 40 of file ColoredRectangle.hpp.
{ 0, 1, 2, 2, 3, 0 };
params
Chronos::Manager::ShapeParams Chronos::Engine::ColoredRectangle::params
Definition at line 42 of file ColoredRectangle.hpp.
vertexBuffer
Chronos::Engine::Buffer Chronos::Engine::ColoredRectangle::vertexBuffer
The vertex buffer that is used to store the vertices.
Definition at line 51 of file ColoredRectangle.hpp.
vertices
const std::vector<ColorVertex> Chronos::Engine::ColoredRectangle::vertices
Initial value:
= std::vector<ColorVertex> { { { -0.5f, -0.5f } },
          { { 0.5f, -0.5f } }, { { 0.5f, 0.5f } },
          { { -0.5f, 0.5f } } }
Definition at line 43 of file ColoredRectangle.hpp.
                                 { { { -0.5f, -0.5f } },
          { { 0.5f, -0.5f } }, { { 0.5f, 0.5f } },
          { { -0.5f, 0.5f } } };
The documentation for this class was generated from the following files:
Source/Rendering/Objects/Rectangle/ColoredRectangle.hpp
Source/Rendering/Objects/Rectangle/ColoredRectangle.cpp