Chronos: Chronos::Engine::Buffer Class Reference
Chronos::Engine::Buffer Class Reference
Used to store buffers in GPU.
#include <buffers.hpp>
Public Member Functions
void create (Chronos::Engine::Device device, VkBufferUsageFlags flags, VkMemoryPropertyFlags properties)
This is used to initialize the buffer.
void copy (void *data, VkCommandPool commandPool)
Copies the data to the buffer.
void destroy ()
Destroys the buffer and frees the memory.
Public Attributes
VkBuffer buffer
The buffer.
VkDeviceSize size
The size of the buffer.
VkDeviceMemory memory
The device memory of the buffer.
Private Attributes
Chronos::Engine::Device device
The device on which the buffer is stored.
Detailed Description
Used to store buffers in GPU.
It contains the buffer, the size and the memory variables needed for this, along with the appropriate functions to use them.
Definition at line 39 of file buffers.hpp.
Member Function Documentation
copy()
void Chronos::Engine::Buffer::copy (void * data, VkCommandPool commandPool)
Copies the data to the buffer.
It does this by coping the data into a temporary staging buffer and then copying it to the final buffer.
Parameters
data The data to copy.
commandPool The command pool to use for the staging buffer and commands during the copy.
Definition at line 39 of file buffers.cpp.
{
    // copies the data to a staging buffer in order to copy to device buffer
    void* data;
    VkBuffer stagingBuffer;
    VkDeviceMemory stagingBufferMemory;
    Chronos::Engine::createBuffer(device, size,
    VK_BUFFER_USAGE_TRANSFER_SRC_BIT,
    VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT
        | VK_MEMORY_PROPERTY_HOST_COHERENT_BIT,
    &stagingBuffer, &stagingBufferMemory);
    vkMapMemory(device.device, stagingBufferMemory, 0, size, 0, &data);
    memcpy(data, inputData, (size_t)size);
    vkUnmapMemory(device.device, stagingBufferMemory);
    Chronos::Engine::copyBuffer(
    device, stagingBuffer, buffer, size, commandPool);
    vkDestroyBuffer(device.device, stagingBuffer, nullptr);
    vkFreeMemory(device.device, stagingBufferMemory, nullptr);
    LOG(3,
    "Data [" + std::to_string((uint64_t)buffer)
        + "] copied to device buffer [" + std::to_string((uint64_t)buffer)
        + "]")
}
References Chronos::Engine::copyBuffer(), Chronos::Engine::createBuffer(), and LOG.
create()
void Chronos::Engine::Buffer::create (Chronos::Engine::Device device, VkBufferUsageFlags flags, VkMemoryPropertyFlags properties)
This is used to initialize the buffer.
It is calls the createBuffer function for this purpose and stores the results.
Parameters
device The device on which the buffer should be stored.
flags The flags to use for the buffer. @params properties The memory properties to use for the buffer.
Definition at line 27 of file buffers.cpp.
{
    this->device = device;
    Chronos::Engine::createBuffer(
    this->device, size, flags, properties, &buffer, &memory);
    LOG(2,
    "Buffer [" + std::to_string((uint64_t)this->buffer)
        + "] created for buffer object [" + std::to_string((uint64_t)this)
        + "]")
}
References buffer, Chronos::Engine::createBuffer(), device, LOG, memory, and size.
destroy()
void Chronos::Engine::Buffer::destroy ()
Destroys the buffer and frees the memory.
Definition at line 63 of file buffers.cpp.
{
    vkDestroyBuffer(device.device, buffer, nullptr);
    vkFreeMemory(device.device, memory, nullptr);
    LOG(2,
    "Buffer [" + std::to_string((uint64_t)buffer)
        + "] destroyed on device ["
        + std::to_string((uint64_t)device.device) + "]")
}
References LOG.
Member Data Documentation
buffer
VkBuffer Chronos::Engine::Buffer::buffer
The buffer.
Definition at line 78 of file buffers.hpp.
device
Chronos::Engine::Device Chronos::Engine::Buffer::device private
The device on which the buffer is stored.
Definition at line 94 of file buffers.hpp.
memory
VkDeviceMemory Chronos::Engine::Buffer::memory
The device memory of the buffer.
Definition at line 88 of file buffers.hpp.
size
VkDeviceSize Chronos::Engine::Buffer::size
The size of the buffer.
Definition at line 83 of file buffers.hpp.
The documentation for this class was generated from the following files:
Source/Rendering/buffers.hpp
Source/Rendering/buffers.cpp