Chronos: Chronos::Engine::Polygon Class Reference
Chronos::Engine::Polygon Class Reference
A class to represent a polygon object.
#include <polygon.hpp>
Public Member Functions
void init (Chronos::Engine::Device *device, VkCommandPool commandPool, Chronos::Engine::SwapChain *swapChain, VkSampler textureSampler, Chronos::Engine::Texture texture, VkRenderPass *renderPass, std::vector< std::array< float, 2 >> vertices)
Initializes the polygon object.
void updateVertices (std::vector< std::array< float, 2 >>vertices)
Updates the vertices of the polygon.
void update (uint32_t currentFrame) override
Updates the polygon object.
void destroy () override
Destroys the polygon object.
void createDescriptorSets () override
std::vector< VkDescriptorType > getDescriptorTypes () override
std::vector< VkShaderStageFlagBits > getDescriptorStages () override
PipelineAttributes getPipelineAttributes () override
Public Member Functions inherited from Chronos::Engine::Object
virtual void init (Chronos::Engine::Device *device, VkCommandPool commandPool, Chronos::Engine::SwapChain *swapChain, VkSampler textureSampler, VkRenderPass *renderPass)
Initializes the object.
void recreateGraphicsPipeline ()
Recreates the graphics pipeline for the object.
Public Attributes
Chronos::Manager::ShapeParams params
Basic properties of the polygon.
std::vector< uint16_t > indices
Chronos::Engine::Texture texture
std::vector< TexturedVertex > vertices
std::vector< Chronos::Engine::Buffer > polygonVertexBuffers
Chronos::Engine::Buffer indexBuffer
Public Attributes inherited from Chronos::Engine::Object
VkPipeline graphicsPipeline
VkPipelineLayout pipelineLayout
std::vector< VkDescriptorSet > descriptorSets
Private Member Functions
void copyVerticestoBuffer (Chronos::Engine::Buffer vertexBuffer)
Copies the current vertices in the vertices vector to the vertex buffer given.
Private Attributes
void * mappedMemory = nullptr
std::vector< bool > copyVertices
Flags to know if the vertex buffer is to be updated.
Additional Inherited Members
Protected Member Functions inherited from Chronos::Engine::Object
void createGraphicsPipeline ()
Creates the graphics pipeline for the object.
void createDescriptorPool ()
Creates the Vulkan descriptor pool for the object.
void createDescriptorSetLayout ()
Creates the Vulkan descriptor set layout for the object.
Protected Attributes inherited from Chronos::Engine::Object
std::string vertexShaderPath
std::string fragmentShaderPath
Chronos::Engine::Device * device
Chronos::Engine::SwapChain * swapChain
VkCommandPool commandPool
VkSampler textureSampler
VkRenderPass * renderPass
VkDescriptorSetLayout descriptorSetLayout
VkDescriptorPool descriptorPool
std::vector< Chronos::Engine::UniformBuffer > uniformBuffers
Detailed Description
A class to represent a polygon object.
A polygon object is a shape that can have any number of vertices and can be textured These vertices can also be updated on the fly after creation. This is done by creating a vertex buffer and copying the vertices to it The indices are generated using the earcut library. This library takes a list of vertices and generates a list of indices that represent the triangles that make up the polygon It uses a polygon triagulation algorithm to do this. Since the vertices can be updated any time, we have to create multiple vertex buffers and update them as the frames are being updated.
Definition at line 19 of file polygon.hpp.
Member Function Documentation
copyVerticestoBuffer()
void Chronos::Engine::Polygon::copyVerticestoBuffer (Chronos::Engine::Buffer vertexBuffer) private
Copies the current vertices in the vertices vector to the vertex buffer given.
Definition at line 58 of file polygon.cpp.
{
     if(vkMapMemory(device->device, vertexBuffer.memory, 0, VK_WHOLE_SIZE, 0, &this->mappedMemory)
         != VK_SUCCESS){
         throw std::runtime_error("Failed to map memory");
     }
     if(this->mappedMemory == nullptr){
         throw std::runtime_error("Memory not mapped, current address is " + std::to_string((uint64_t)this->mappedMemory));
     }
     memcpy(this->mappedMemory, this->vertices.data(), (size_t)vertexBuffer.size);
     vkUnmapMemory(device->device, vertexBuffer.memory);
 }
References Chronos::Engine::Buffer::memory, and Chronos::Engine::Buffer::size.
createDescriptorSets()
void Chronos::Engine::Polygon::createDescriptorSets () override virtual
Implements Chronos::Engine::Object.
Definition at line 103 of file polygon.cpp.
{
     std::vector<VkDescriptorSetLayout> layouts(MAX_FRAMES_IN_FLIGHT,
         descriptorSetLayout);
     VkDescriptorSetAllocateInfo allocInfo {};
     allocInfo.sType = VK_STRUCTURE_TYPE_DESCRIPTOR_SET_ALLOCATE_INFO;
     allocInfo.descriptorPool = descriptorPool;
     allocInfo.descriptorSetCount = static_cast<uint32_t>(MAX_FRAMES_IN_FLIGHT);
     allocInfo.pSetLayouts = layouts.data();
     descriptorSets.resize(MAX_FRAMES_IN_FLIGHT);
     if (vkAllocateDescriptorSets(device->device, &allocInfo,
             descriptorSets.data())
         != VK_SUCCESS) {
         throw std::runtime_error("failed to allocate descriptor sets!");
     }
     for (size_t i = 0; i < MAX_FRAMES_IN_FLIGHT; i++) {
         VkDescriptorBufferInfo bufferInfo {};
         bufferInfo.buffer = uniformBuffers[i].buffer;
         bufferInfo.offset = 0;
         bufferInfo.range = sizeof(UniformBufferObject);
         VkWriteDescriptorSet descriptorWrite {};
         VkDescriptorImageInfo imageInfo {};
         imageInfo.imageLayout = VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL;
         imageInfo.imageView = texture.textureImageView;
         imageInfo.sampler = textureSampler;
         std::array<VkWriteDescriptorSet, 2> descriptorWrites {};
         descriptorWrites[0].sType = VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET;
         descriptorWrites[0].dstSet = descriptorSets[i];
         descriptorWrites[0].dstBinding = 0;
         descriptorWrites[0].dstArrayElement = 0;
         descriptorWrites[0].descriptorType = VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER;
         descriptorWrites[0].descriptorCount = 1;
         descriptorWrites[0].pBufferInfo = &bufferInfo;
         descriptorWrites[1].sType = VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET;
         descriptorWrites[1].dstSet = descriptorSets[i];
         descriptorWrites[1].dstBinding = 1;
         descriptorWrites[1].dstArrayElement = 0;
         descriptorWrites[1].descriptorType = VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER;
         descriptorWrites[1].descriptorCount = 1;
         descriptorWrites[1].pImageInfo = &imageInfo;
         vkUpdateDescriptorSets(device->device,
             static_cast<uint32_t>(descriptorWrites.size()),
             descriptorWrites.data(), 0, nullptr);
     }
 }
References MAX_FRAMES_IN_FLIGHT.
destroy()
void Chronos::Engine::Polygon::destroy () override virtual
Destroys the polygon object.
This function destroys the polygon object. It frees the memory allocated for the vertex buffer, index buffer and descriptor sets
Implements Chronos::Engine::Object.
Definition at line 95 of file polygon.cpp.
{
     for (auto& buffer : polygonVertexBuffers){
         buffer.destroy();
     }
     indexBuffer.destroy();
     Chronos::Engine::Object::destroy();
 }
References Chronos::Engine::Object::destroy().
getDescriptorStages()
std::vector< VkShaderStageFlagBits > Chronos::Engine::Polygon::getDescriptorStages () override virtual
Implements Chronos::Engine::Object.
Definition at line 157 of file polygon.cpp.
{
     return {VK_SHADER_STAGE_VERTEX_BIT, VK_SHADER_STAGE_FRAGMENT_BIT};
 }
getDescriptorTypes()
std::vector< VkDescriptorType > Chronos::Engine::Polygon::getDescriptorTypes () override virtual
Implements Chronos::Engine::Object.
Definition at line 153 of file polygon.cpp.
{
     return {VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER, VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER};
 }
getPipelineAttributes()
Chronos::Engine::PipelineAttributes Chronos::Engine::Polygon::getPipelineAttributes () override virtual
Implements Chronos::Engine::Object.
Definition at line 161 of file polygon.cpp.
{
     Chronos::Engine::PipelineAttributes pipelineAttributes;
     auto bindingDescription = TexturedVertex::getBindingDescription();
     auto attributeDescriptions = TexturedVertex::getAttributeDescriptions();
     pipelineAttributes.bindingDescriptions.resize(1);
     pipelineAttributes.bindingDescriptions[0] = bindingDescription;
     pipelineAttributes.attributeDescriptions.resize(attributeDescriptions.size());
     for (int i = 0; i < attributeDescriptions.size(); i++) {
         pipelineAttributes.attributeDescriptions[i] = attributeDescriptions[i];
     }
     pipelineAttributes.topology = VK_PRIMITIVE_TOPOLOGY_TRIANGLE_LIST;
     pipelineAttributes.frontFace = VK_FRONT_FACE_COUNTER_CLOCKWISE;
     pipelineAttributes.colorBlendAttachment.colorWriteMask = VK_COLOR_COMPONENT_R_BIT | VK_COLOR_COMPONENT_G_BIT | VK_COLOR_COMPONENT_B_BIT | VK_COLOR_COMPONENT_A_BIT;
     pipelineAttributes.colorBlendAttachment.blendEnable = VK_FALSE;
     pipelineAttributes.colorBlendAttachment.srcColorBlendFactor = VK_BLEND_FACTOR_ONE;
     pipelineAttributes.colorBlendAttachment.dstColorBlendFactor = VK_BLEND_FACTOR_ZERO; // Optional
     pipelineAttributes.colorBlendAttachment.colorBlendOp = VK_BLEND_OP_ADD; // Optional
     pipelineAttributes.colorBlendAttachment.srcAlphaBlendFactor = VK_BLEND_FACTOR_ONE; // Optional
     pipelineAttributes.colorBlendAttachment.dstAlphaBlendFactor = VK_BLEND_FACTOR_ZERO; // Optional
     pipelineAttributes.colorBlendAttachment.alphaBlendOp = VK_BLEND_OP_ADD; // Optional
     return pipelineAttributes;
 }
References Chronos::Engine::PipelineAttributes::attributeDescriptions, Chronos::Engine::PipelineAttributes::bindingDescriptions, Chronos::Engine::PipelineAttributes::colorBlendAttachment, Chronos::Engine::PipelineAttributes::frontFace, Chronos::Engine::TexturedVertex::getAttributeDescriptions(), Chronos::Engine::TexturedVertex::getBindingDescription(), and Chronos::Engine::PipelineAttributes::topology.
init()
void Chronos::Engine::Polygon::init (Chronos::Engine::Device * device, VkCommandPool commandPool, Chronos::Engine::SwapChain * swapChain, VkSampler textureSampler, Chronos::Engine::Texture texture, VkRenderPass * renderPass, std::vector< std::array< float, 2 >> vertices)
Initializes the polygon object.
This function initializes the polygon object. It creates the vertex buffer, index buffer and descriptor sets for the object It also calculates the indices using the earcut library.
Definition at line 15 of file polygon.cpp.
{
     this->vertexShaderPath = SPIV_SHADER_PATH"/textureVert.spv";
     this->fragmentShaderPath = SPIV_SHADER_PATH"/textureFrag.spv";
     this->texture = texture;
     //we copy the vertices to the vertex struct. For the texture cooring we use the same vertex coordinates, but we map them to the range [0, 1] from [-1, 1]
     for (auto& vertex : vertices) {
         TexturedVertex tv = {{vertex[0], vertex[1]}, {(vertex[0] + 1.0f)/2.0f, (vertex[1] + 1.0f)/2.0f}};
         this->vertices.push_back(tv);
     }
     //we use the earcut library to triangulate the polygon and generate the indicies
     std::vector<uint32_t> triangleIndices = mapbox::earcut<uint32_t>(std::array<std::vector<std::array<float, 2>>, 2>{vertices, {}});
     for (uint32_t i = 0; i < triangleIndices.size(); i++){
         if(triangleIndices[i] >= vertices.size()){
             throw std::runtime_error("Index" + std::to_string(triangleIndices[i]) + " out of range");
         }
         this->indices.push_back(triangleIndices[i]);
     }
     Chronos::Engine::Object::init(device, commandPool, swapChain, textureSampler, renderPass);
     // create the vertex and index buffers and copy the data
     polygonVertexBuffers.resize(MAX_FRAMES_IN_FLIGHT);
     for (auto& buffer : polygonVertexBuffers){
         buffer.size = sizeof(this->vertices[0]) * this->vertices.size();
         buffer.create(*device,
             VK_BUFFER_USAGE_VERTEX_BUFFER_BIT,
             VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT | VK_MEMORY_PROPERTY_HOST_COHERENT_BIT); //we use host visible and coherent memory to be able to map it and to edit the vertiuces
         copyVerticestoBuffer(buffer);
     }
     copyVertices.resize(MAX_FRAMES_IN_FLIGHT, false);
     indexBuffer.size = sizeof(this->indices[0]) * this->indices.size();
     indexBuffer.create(*device,
         VK_BUFFER_USAGE_TRANSFER_DST_BIT | VK_BUFFER_USAGE_INDEX_BUFFER_BIT,
         VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT); //inidcies will not change
     indexBuffer.copy(this->indices.data(), commandPool);
 }
References Chronos::Engine::Object::commandPool, Chronos::Engine::Buffer::copy(), copyVertices, copyVerticestoBuffer(), Chronos::Engine::Buffer::create(), Chronos::Engine::Object::device, Chronos::Engine::Object::fragmentShaderPath, indexBuffer, indices, Chronos::Engine::Object::init(), MAX_FRAMES_IN_FLIGHT, polygonVertexBuffers, Chronos::Engine::Object::renderPass, Chronos::Engine::Buffer::size, Chronos::Engine::Object::swapChain, texture, Chronos::Engine::Object::textureSampler, Chronos::Engine::Object::vertexShaderPath, and vertices.
update()
void Chronos::Engine::Polygon::update (uint32_t currentFrame) override virtual
Updates the polygon object.
Same as other objects. One thing to note is that the vertices are copied to the vertex buffer if the copyVertices flag is set to true
Implements Chronos::Engine::Object.
Definition at line 85 of file polygon.cpp.
{
     if (copyVertices[currentFrame]){
         copyVerticestoBuffer(polygonVertexBuffers[currentFrame]);
         copyVertices[currentFrame] = false;
     }
     uniformBuffers[currentFrame].update(swapChain->swapChainExtent, params.x,
         params.y, params.rotation, params.xSize,
         params.ySize);
 }
updateVertices()
void Chronos::Engine::Polygon::updateVertices (std::vector< std::array< float, 2 >> vertices)
Updates the vertices of the polygon.
This function updates the vertices of the polygon. It copies the vertices to the vertex stroage buffer and sets the copyVertices flag to true for all buffers
Definition at line 70 of file polygon.cpp.
{
     //There are a vertex buffer, one for each frame in flight. We need to update all of them
     //however, some of them may be in use, hence we just set bools correspoding to each buffer to true
     //on update of the frame, we will copy the vertices to the buffer if the bool is true for that frame
     assert(vertices.size() == this->vertices.size());
     this->vertices.clear();
     for (auto& vertex : vertices) {
         TexturedVertex tv = {{vertex[0], vertex[1]}, {(vertex[0] + 1.0f)/2.0f, (vertex[1] + 1.0f)/2.0f}};
         this->vertices.push_back(tv);
     }
     for(int i = 0; i < copyVertices.size(); i++){
         copyVertices[i] = true;
     }
 }
Member Data Documentation
copyVertices
std::vector<bool> Chronos::Engine::Polygon::copyVertices private
Flags to know if the vertex buffer is to be updated.
Definition at line 80 of file polygon.hpp.
indexBuffer
Chronos::Engine::Buffer Chronos::Engine::Polygon::indexBuffer
Definition at line 63 of file polygon.hpp.
indices
std::vector<uint16_t> Chronos::Engine::Polygon::indices
Definition at line 59 of file polygon.hpp.
mappedMemory
void* Chronos::Engine::Polygon::mappedMemory = nullptr private
Definition at line 70 of file polygon.hpp.
params
Chronos::Manager::ShapeParams Chronos::Engine::Polygon::params
Basic properties of the polygon.
Definition at line 25 of file polygon.hpp.
polygonVertexBuffers
std::vector<Chronos::Engine::Buffer> Chronos::Engine::Polygon::polygonVertexBuffers
Definition at line 62 of file polygon.hpp.
texture
Chronos::Engine::Texture Chronos::Engine::Polygon::texture
Definition at line 60 of file polygon.hpp.
vertices
std::vector<TexturedVertex> Chronos::Engine::Polygon::vertices
Definition at line 61 of file polygon.hpp.
The documentation for this class was generated from the following files:
Source/Engine/Headers/polygon.hpp
Source/Engine/Source/polygon.cpp