Chronos: Chronos::Engine::TextManager Class Reference
Chronos::Engine::TextManager Class Reference
This is the text manager for Chronos. It handles creation, modification, updating and desrtuction of text.
#include <textManager.hpp>
Public Member Functions
int addFont (Chronos::Engine::Text font, Chronos::Engine::FontTypes fontStyle)
Adds a font to the text manager.
void render (uint32_t currentFrame, uint32_t imageIndex, float bgColor[3])
Records the commands needed for rendering the text.
void remove (int fontNo)
Removes a font from the text manager.
Public Member Functions inherited from Chronos::Engine::ObjectManager< Chronos::Engine::Text >
void remove (int objectNo)
Removes an object with the specified index.
void init (Chronos::Engine::Device *device, Chronos::Engine::SwapChain *swapChain, VkCommandPool commandPool)
Initializes the ObjectManager.
void destroy ()
Destroys resources associated with the ObjectManager.
void update (uint32_t currentFrame)
Updates the objects managed by the ObjectManager.
void changeMsaa ()
Changes the multisampling settings for rendering.
void recreate ()
Recreates resources for rendering.
Private Member Functions
void createRenderPass ()
Creates the render pass needed for rendering the text.
Additional Inherited Members
Public Attributes inherited from Chronos::Engine::ObjectManager< Chronos::Engine::Text >
int nextFreeObjectNo
std::map< int, Object > objects
std::vector< VkCommandBuffer > commandBuffers
Protected Member Functions inherited from Chronos::Engine::ObjectManager< Chronos::Engine::Text >
void endRender (uint32_t currentFrame)
Ends the rendering process for the specified frame.
int addObject (Object object)
Adds an object to the ObjectManager.
void cleanup ()
Cleans up resources associated with rendering.
Protected Attributes inherited from Chronos::Engine::ObjectManager< Chronos::Engine::Text >
Chronos::Engine::Device * device
Chronos::Engine::SwapChain * swapChain
VkCommandPool commandPool
VkRenderPass renderPass
VkSampler textureSampler
std::vector< VkFramebuffer > framebuffers
Detailed Description
This is the text manager for Chronos. It handles creation, modification, updating and desrtuction of text.
Definition at line 13 of file textManager.hpp.
Member Function Documentation
addFont()
int Chronos::Engine::TextManager::addFont (Chronos::Engine::Text font, Chronos::Engine::FontTypes fontStyle)
Adds a font to the text manager.
Parameters
font The font to add.
Definition at line 66 of file textManager.cpp.
 {
     font.init(device, commandPool, swapChain, textureSampler, &renderPass, fontStyle);
     return Chronos::Engine::ObjectManager<Chronos::Engine::Text>::addObject(font);
 }
References Chronos::Engine::ObjectManager< Object >::addObject(), and Chronos::Engine::Text::init().
createRenderPass()
void Chronos::Engine::TextManager::createRenderPass () private virtual
Creates the render pass needed for rendering the text.
Implements Chronos::Engine::ObjectManager< Chronos::Engine::Text >.
Definition at line 15 of file textManager.cpp.
 {
 #ifdef ENABLE_EDITOR
     renderPass = Chronos::Engine::createRenderPass(
         *device, *swapChain, VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL,
         VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL,
         VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL, true, false, true);
 #else
     renderPass = Chronos::Engine::createRenderPass(
         *device, *swapChain, VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL,
         VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL, VK_IMAGE_LAYOUT_PRESENT_SRC_KHR,
         true, false, true);
 #endif
 }
References Chronos::Engine::createRenderPass(), Chronos::Engine::ObjectManager< Chronos::Engine::Text >::device, Chronos::Engine::ObjectManager< Chronos::Engine::Text >::renderPass, and Chronos::Engine::ObjectManager< Chronos::Engine::Text >::swapChain.
remove()
void Chronos::Engine::TextManager::remove (int fontNo)
Removes a font from the text manager.
Parameters
fontNo The index of the font to remove.
Definition at line 72 of file textManager.cpp.
 {
     if (objects.count(fontNo) == 0) {
         throw std::runtime_error("Font does not exist");
     }
     Chronos::Engine::ObjectManager<Chronos::Engine::Text>::remove(fontNo);
 }
References Chronos::Engine::ObjectManager< Object >::remove().
render()
void Chronos::Engine::TextManager::render (uint32_t currentFrame, uint32_t imageIndex, float bgColor[3]) virtual
Records the commands needed for rendering the text.
When this function is called, it records the commands that are needed for rendering all the text stored in this class.
Parameters
currentFrame The current frame to render to.
imageIndex The index of the framebuffer associated with the current frame
bgColor The background color to use for rendering the background.
Reimplemented from Chronos::Engine::ObjectManager< Chronos::Engine::Text >.
Definition at line 30 of file textManager.cpp.
 {
     Chronos::Engine::ObjectManager<Chronos::Engine::Text>::render(currentFrame, imageIndex, bgColor);
     VkViewport viewport {};
     viewport.x = 0.0f;
     viewport.y = 0.0f;
     viewport.width = static_cast<float>(swapChain->swapChainExtent.width);
     viewport.height = static_cast<float>(swapChain->swapChainExtent.height);
     viewport.minDepth = 0.0f;
     viewport.maxDepth = 1.0f;
     VkRect2D scissor {};
     scissor.offset = { 0, 0 };
     scissor.extent = swapChain->swapChainExtent;
     for (auto& object : objects) {
         vkCmdBindPipeline(commandBuffers[currentFrame],
             VK_PIPELINE_BIND_POINT_GRAPHICS, object.second.graphicsPipeline);
         vkCmdSetViewport(commandBuffers[currentFrame], 0, 1, &viewport);
         vkCmdSetScissor(commandBuffers[currentFrame], 0, 1, &scissor);
         VkBuffer vertexBuffers[] = { object.second.vertexBuffer };
         VkDeviceSize offsets[] = { 0 };
         vkCmdBindVertexBuffers(commandBuffers[currentFrame], 0, 1, vertexBuffers,
             offsets);
         vkCmdBindVertexBuffers(commandBuffers[currentFrame], 1, 1, vertexBuffers,
             offsets);
         vkCmdBindDescriptorSets(commandBuffers[currentFrame],
             VK_PIPELINE_BIND_POINT_GRAPHICS, object.second.pipelineLayout, 0, 1,
             &object.second.descriptorSets[currentFrame], 0, nullptr);
         for (uint32_t j = 0; j < object.second.numLetters; j++) {
             vkCmdDraw(commandBuffers[currentFrame], 4, 1, j * 4, 0);
         }
     }
     Chronos::Engine::ObjectManager<Chronos::Engine::Text>::endRender(currentFrame);
 }
References Chronos::Engine::ObjectManager< Object >::endRender(), and Chronos::Engine::ObjectManager< Object >::render().
The documentation for this class was generated from the following files:
Source/Engine/Headers/textManager.hpp
Source/Engine/Source/textManager.cpp