Chronos: Chronos::Engine::Object Class Reference
Chronos::Engine::Object Class Reference abstract
Abstract class for creating and managing generic graphical objects.
#include <object.hpp>
Public Member Functions
void init (Chronos::Engine::Device *device, VkCommandPool commandPool, Chronos::Engine::SwapChain *swapChain, VkSampler textureSampler, VkRenderPass *renderPass, ObjectType objectType)
Initializes the object.
virtual void update (uint32_t currentFrame)=0
Updates the object for the current frame.
virtual void render (uint32_t currentFrame, uint32_t imageIndex, float bgColor[3], VkViewport &viewport, VkRect2D &scissor, std::vector< VkCommandBuffer > &commandBuffers)=0
virtual void destroy ()=0
Destroys the object and releases associated resources.
void recreateGraphicsPipeline ()
Recreates the graphics pipeline for the object.
Public Attributes
VkPipeline graphicsPipeline
VkPipelineLayout pipelineLayout
std::vector< VkDescriptorSet > descriptorSets
Chronos::Engine::ObjectType objectType
Protected Member Functions
void createGraphicsPipeline ()
Creates the graphics pipeline for the object.
void createDescriptorPool ()
Creates the Vulkan descriptor pool for the object.
void createDescriptorSetLayout ()
Creates the Vulkan descriptor set layout for the object.
virtual void createDescriptorSets ()=0
virtual std::vector< VkDescriptorType > getDescriptorTypes ()=0
virtual std::vector< VkShaderStageFlagBits > getDescriptorStages ()=0
virtual PipelineAttributes getPipelineAttributes ()=0
Protected Attributes
std::string vertexShaderPath
std::string fragmentShaderPath
Chronos::Engine::Device * device
Chronos::Engine::SwapChain * swapChain
VkCommandPool commandPool
VkSampler textureSampler
VkRenderPass * renderPass
VkDescriptorSetLayout descriptorSetLayout
VkDescriptorPool descriptorPool
std::vector< Chronos::Engine::UniformBuffer > uniformBuffers
Detailed Description
Abstract class for creating and managing generic graphical objects.
The Object class provides an interface for creating and managing generic graphical objects. Derived classes are expected to implement specific functionality for initialization, updates, and destruction of the object depending on specific use case.
Definition at line 66 of file object.hpp.
Member Function Documentation
createDescriptorPool()
void Chronos::Engine::Object::createDescriptorPool () protected
Creates the Vulkan descriptor pool for the object.
This method sets up and creates the Vulkan descriptor pool based on the descriptor types used by the object.
Definition at line 268 of file object.cpp.
{
    std::vector<VkDescriptorType> descriptorTypes = getDescriptorTypes();
    std::vector<VkDescriptorPoolSize> poolSizes { descriptorTypes.size() };
    for (size_t i = 0; i < descriptorTypes.size(); i++) {
    poolSizes[i].type = descriptorTypes[i];
    poolSizes[i].descriptorCount
        = static_cast<uint32_t>(MAX_FRAMES_IN_FLIGHT);
    }
    VkDescriptorPoolCreateInfo poolInfo {};
    poolInfo.sType = VK_STRUCTURE_TYPE_DESCRIPTOR_POOL_CREATE_INFO;
    poolInfo.poolSizeCount = static_cast<uint32_t>(poolSizes.size());
    poolInfo.pPoolSizes = poolSizes.data();
    poolInfo.maxSets = static_cast<uint32_t>(MAX_FRAMES_IN_FLIGHT);
    if (vkCreateDescriptorPool(
        device->device, &poolInfo, nullptr, &descriptorPool)
    != VK_SUCCESS) {
    throw std::runtime_error("failed to create descriptor pool!");
    }
}
References MAX_FRAMES_IN_FLIGHT.
createDescriptorSetLayout()
void Chronos::Engine::Object::createDescriptorSetLayout () protected
Creates the Vulkan descriptor set layout for the object.
This method sets up and creates the Vulkan descriptor set layout based on the descriptor types and stages used by the object.
Definition at line 291 of file object.cpp.
{
    std::vector<VkDescriptorType> descriptorTypes = getDescriptorTypes();
    std::vector<VkShaderStageFlagBits> descriptorStages = getDescriptorStages();
    if (descriptorTypes.size() != descriptorStages.size()) {
    throw std::runtime_error(
        "descriptorTypes and descriptorStages must be the same size");
    }
    std::vector<VkDescriptorSetLayoutBinding> bindings {
    descriptorTypes.size()
    };
    for (size_t i = 0; i < descriptorTypes.size(); i++) {
    bindings[i].binding = i;
    bindings[i].descriptorType = descriptorTypes[i];
    bindings[i].descriptorCount = 1;
    bindings[i].stageFlags = descriptorStages[i];
    bindings[i].pImmutableSamplers = nullptr;
    }
    VkDescriptorSetLayoutCreateInfo layoutInfo {};
    layoutInfo.sType = VK_STRUCTURE_TYPE_DESCRIPTOR_SET_LAYOUT_CREATE_INFO;
    layoutInfo.bindingCount = static_cast<uint32_t>(bindings.size());
    layoutInfo.pBindings = bindings.data();
    if (vkCreateDescriptorSetLayout(
        device->device, &layoutInfo, nullptr, &descriptorSetLayout)
    != VK_SUCCESS) {
    throw std::runtime_error("failed to create descriptor set layout!");
    }
}
createDescriptorSets()
virtual void Chronos::Engine::Object::createDescriptorSets () protected pure virtual
Implemented in Chronos::Engine::ColoredRectangle, Chronos::Engine::TexturedRectangle, and Chronos::Engine::Text.
createGraphicsPipeline()
void Chronos::Engine::Object::createGraphicsPipeline () protected
Creates the graphics pipeline for the object.
This method is responsible for configuring and creating the Vulkan graphics pipeline used by the object, including shader modules, vertex input, input assembly, viewport, rasterization, multisampling, color blending, and dynamic states.
Definition at line 99 of file object.cpp.
{
    Chronos::Engine::PipelineAttributes pipelineAttributes
    = getPipelineAttributes();
    auto vertShaderCode = readFile(vertexShaderPath.c_str());
    auto fragShaderCode = readFile(fragmentShaderPath.c_str());
    VkShaderModule vertShaderModule
    = createShaderModule(vertShaderCode, device->device);
    VkShaderModule fragShaderModule
    = createShaderModule(fragShaderCode, device->device);
    VkPipelineShaderStageCreateInfo vertShaderStageInfo {};
    vertShaderStageInfo.sType
    = VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO;
    vertShaderStageInfo.stage = VK_SHADER_STAGE_VERTEX_BIT;
    vertShaderStageInfo.module = vertShaderModule;
    vertShaderStageInfo.pName
    = "main"; // start from main(vulkan can start from elsewhere also)
    VkPipelineShaderStageCreateInfo fragShaderStageInfo {};
    fragShaderStageInfo.sType
    = VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO;
    fragShaderStageInfo.stage = VK_SHADER_STAGE_FRAGMENT_BIT;
    fragShaderStageInfo.module = fragShaderModule;
    fragShaderStageInfo.pName = "main";
    VkPipelineShaderStageCreateInfo shaderStages[]
    = { vertShaderStageInfo, fragShaderStageInfo };
    auto bindingDescription = pipelineAttributes.bindingDescriptions;
    auto attributeDescriptions = pipelineAttributes.attributeDescriptions;
    VkPipelineVertexInputStateCreateInfo vertexInputInfo {};
    vertexInputInfo.sType
    = VK_STRUCTURE_TYPE_PIPELINE_VERTEX_INPUT_STATE_CREATE_INFO;
    vertexInputInfo.vertexBindingDescriptionCount
    = static_cast<uint32_t>(bindingDescription.size());
    vertexInputInfo.vertexAttributeDescriptionCount
    = static_cast<uint32_t>(attributeDescriptions.size());
    vertexInputInfo.pVertexBindingDescriptions = bindingDescription.data();
    vertexInputInfo.pVertexAttributeDescriptions = attributeDescriptions.data();
    VkPipelineInputAssemblyStateCreateInfo inputAssembly {};
    inputAssembly.sType
    = VK_STRUCTURE_TYPE_PIPELINE_INPUT_ASSEMBLY_STATE_CREATE_INFO;
    inputAssembly.topology
    = pipelineAttributes.topology; // we are using indexed rendering so
                       // we need to use triangle list
    inputAssembly.primitiveRestartEnable = VK_FALSE;
    VkViewport viewport {};
    viewport.x = 0.0f;
    viewport.y = 0.0f;
    viewport.width = (float)(*swapChain).swapChainExtent.width;
    viewport.height = (float)(*swapChain).swapChainExtent.height;
    viewport.minDepth = 0.0f;
    viewport.maxDepth = 1.0f;
    VkRect2D scissor {};
    scissor.offset = { 0, 0 };
    scissor.extent = (*swapChain).swapChainExtent;
    VkPipelineViewportStateCreateInfo viewportState {};
    viewportState.sType = VK_STRUCTURE_TYPE_PIPELINE_VIEWPORT_STATE_CREATE_INFO;
    viewportState.viewportCount = 1;
    viewportState.pViewports = &viewport;
    viewportState.scissorCount = 1;
    viewportState.pScissors = &scissor;
    VkPipelineRasterizationStateCreateInfo rasterizer {};
    rasterizer.sType
    = VK_STRUCTURE_TYPE_PIPELINE_RASTERIZATION_STATE_CREATE_INFO;
    rasterizer.depthClampEnable = VK_FALSE;
    rasterizer.rasterizerDiscardEnable = VK_FALSE;
    rasterizer.polygonMode = VK_POLYGON_MODE_FILL;
    rasterizer.lineWidth = 1.0f;
    rasterizer.cullMode = VK_CULL_MODE_BACK_BIT;
    rasterizer.frontFace = pipelineAttributes.frontFace; // counter clockwuise
    rasterizer.depthBiasEnable = VK_FALSE;
    rasterizer.depthBiasConstantFactor = 0.0f;
    rasterizer.depthBiasClamp = 0.0f;
    rasterizer.depthBiasSlopeFactor = 0.0f;
    VkPipelineMultisampleStateCreateInfo multisampling {};
    multisampling.sType
    = VK_STRUCTURE_TYPE_PIPELINE_MULTISAMPLE_STATE_CREATE_INFO;
    multisampling.sampleShadingEnable = VK_FALSE;
    multisampling.rasterizationSamples = device->msaaSamples;
    multisampling.minSampleShading = 1.0f; // Optional
    multisampling.pSampleMask = nullptr; // Optional
    multisampling.alphaToCoverageEnable = VK_FALSE; // Optional
    multisampling.alphaToOneEnable = VK_FALSE;
    multisampling.sampleShadingEnable = VK_TRUE;
    VkPipelineColorBlendStateCreateInfo colorBlending {};
    colorBlending.sType
    = VK_STRUCTURE_TYPE_PIPELINE_COLOR_BLEND_STATE_CREATE_INFO;
    colorBlending.logicOpEnable = VK_FALSE;
    colorBlending.logicOp = VK_LOGIC_OP_COPY;
    colorBlending.attachmentCount = 1;
    colorBlending.pAttachments = &pipelineAttributes.colorBlendAttachment;
    colorBlending.blendConstants[0] = 0.0f;
    colorBlending.blendConstants[1] = 0.0f;
    colorBlending.blendConstants[2] = 0.0f;
    colorBlending.blendConstants[3] = 0.0f;
    std::vector<VkDynamicState> dynamicStates
    = { VK_DYNAMIC_STATE_VIEWPORT, VK_DYNAMIC_STATE_SCISSOR };
    VkPipelineDynamicStateCreateInfo dynamicState {};
    dynamicState.sType = VK_STRUCTURE_TYPE_PIPELINE_DYNAMIC_STATE_CREATE_INFO;
    dynamicState.dynamicStateCount
    = static_cast<uint32_t>(dynamicStates.size());
    dynamicState.pDynamicStates = dynamicStates.data();
    VkPipelineLayoutCreateInfo pipelineLayoutInfo {};
    pipelineLayoutInfo.sType = VK_STRUCTURE_TYPE_PIPELINE_LAYOUT_CREATE_INFO;
    pipelineLayoutInfo.setLayoutCount = 1; // Optional
    pipelineLayoutInfo.pSetLayouts = &descriptorSetLayout; // Optional
    pipelineLayoutInfo.pushConstantRangeCount = 0; // Optional
    pipelineLayoutInfo.pPushConstantRanges = nullptr; // Optional
    if (vkCreatePipelineLayout(
        device->device, &pipelineLayoutInfo, nullptr, &pipelineLayout)
    != VK_SUCCESS) {
    throw std::runtime_error("failed to create pipeline layout!");
    }
    VkGraphicsPipelineCreateInfo pipelineInfo {};
    pipelineInfo.sType = VK_STRUCTURE_TYPE_GRAPHICS_PIPELINE_CREATE_INFO;
    pipelineInfo.stageCount = 2;
    pipelineInfo.pStages = shaderStages;
    pipelineInfo.pVertexInputState = &vertexInputInfo;
    pipelineInfo.pInputAssemblyState = &inputAssembly;
    pipelineInfo.pViewportState = &viewportState;
    pipelineInfo.pRasterizationState = &rasterizer;
    pipelineInfo.pMultisampleState = &multisampling;
    pipelineInfo.pDepthStencilState = nullptr; // Optional
    pipelineInfo.pColorBlendState = &colorBlending;
    pipelineInfo.pDynamicState = &dynamicState;
    pipelineInfo.layout = pipelineLayout;
    pipelineInfo.renderPass = *renderPass;
    pipelineInfo.subpass = 0;
    pipelineInfo.basePipelineHandle = VK_NULL_HANDLE; // Optional
    pipelineInfo.basePipelineIndex = -1;
    if (vkCreateGraphicsPipelines(device->device, VK_NULL_HANDLE, 1,
        &pipelineInfo, nullptr, &graphicsPipeline)
    != VK_SUCCESS) {
    throw std::runtime_error("failed to create graphics pipeline!");
    }
    // destory the shader modules
    vkDestroyShaderModule(device->device, fragShaderModule, nullptr);
    vkDestroyShaderModule(device->device, vertShaderModule, nullptr);
}
References Chronos::Engine::PipelineAttributes::attributeDescriptions, Chronos::Engine::PipelineAttributes::bindingDescriptions, Chronos::Engine::PipelineAttributes::colorBlendAttachment, createShaderModule(), Chronos::Engine::PipelineAttributes::frontFace, readFile(), and Chronos::Engine::PipelineAttributes::topology.
destroy()
void Chronos::Engine::Object::destroy () pure virtual
Destroys the object and releases associated resources.
This method is responsible for cleaning up the object's resources, including uniform buffers, descriptor pool, descriptor set layout, graphics pipeline, and pipeline layout.
Implemented in Chronos::Engine::ColoredRectangle, Chronos::Engine::TexturedRectangle, and Chronos::Engine::Text.
Definition at line 257 of file object.cpp.
{
    for (size_t i = 0; i < MAX_FRAMES_IN_FLIGHT; i++) {
    uniformBuffers[i].destroy();
    }
    vkDestroyDescriptorPool(device->device, descriptorPool, nullptr);
    vkDestroyDescriptorSetLayout(device->device, descriptorSetLayout, nullptr);
    vkDestroyPipeline(device->device, graphicsPipeline, nullptr);
    vkDestroyPipelineLayout(device->device, pipelineLayout, nullptr);
}
References MAX_FRAMES_IN_FLIGHT.
getDescriptorStages()
virtual std::vector< VkShaderStageFlagBits > Chronos::Engine::Object::getDescriptorStages () protected pure virtual
Implemented in Chronos::Engine::ColoredRectangle, Chronos::Engine::TexturedRectangle, and Chronos::Engine::Text.
getDescriptorTypes()
virtual std::vector< VkDescriptorType > Chronos::Engine::Object::getDescriptorTypes () protected pure virtual
Implemented in Chronos::Engine::ColoredRectangle, Chronos::Engine::TexturedRectangle, and Chronos::Engine::Text.
getPipelineAttributes()
virtual PipelineAttributes Chronos::Engine::Object::getPipelineAttributes () protected pure virtual
Implemented in Chronos::Engine::ColoredRectangle, Chronos::Engine::TexturedRectangle, and Chronos::Engine::Text.
init()
void Chronos::Engine::Object::init (Chronos::Engine::Device * device, VkCommandPool commandPool, Chronos::Engine::SwapChain * swapChain, VkSampler textureSampler, VkRenderPass * renderPass, ObjectType objectType)
Initializes the object.
This method initializes the Object with necessary Vulkan-related parameters, such as the device, command pool, swap chain, texture sampler, and render pass. It also allocates uniform buffers and creates descriptor sets, descriptor pool, descriptor set layout, and the graphics pipeline for rendering the object.
Parameters
device The device used by the object.
commandPool Vulkan command pool for the object.
swapChain Swap chain used by the object.
textureSampler Vulkan texture sampler used by the object.
renderPass Vulkan render pass that is used for rendering object in question.
Definition at line 77 of file object.cpp.
{
    this->device = device;
    this->swapChain = swapChain;
    this->commandPool = commandPool;
    this->textureSampler = textureSampler;
    this->renderPass = renderPass;
    this->objectType = objectType;
    uniformBuffers.resize(MAX_FRAMES_IN_FLIGHT);
    for (size_t i = 0; i < MAX_FRAMES_IN_FLIGHT; i++) {
    uniformBuffers[i].create(*device);
    }
    createDescriptorPool();
    createDescriptorSetLayout();
    createDescriptorSets();
    createGraphicsPipeline();
}
References commandPool, Chronos::Engine::SwapChain::create(), createDescriptorPool(), createDescriptorSetLayout(), createDescriptorSets(), createGraphicsPipeline(), device, MAX_FRAMES_IN_FLIGHT, objectType, renderPass, swapChain, textureSampler, and uniformBuffers.
recreateGraphicsPipeline()
void Chronos::Engine::Object::recreateGraphicsPipeline ()
Recreates the graphics pipeline for the object.
This method is used to recreate the graphics pipeline when needed, typically after changes in the rendering configuration such as MSAA changes. It destroys the existing graphics pipeline and pipeline layout before creating a new one.
Definition at line 324 of file object.cpp.
{
    vkDestroyPipeline(device->device, graphicsPipeline, nullptr);
    vkDestroyPipelineLayout(device->device, pipelineLayout, nullptr);
    createGraphicsPipeline();
}
render()
virtual void Chronos::Engine::Object::render (uint32_t currentFrame, uint32_t imageIndex, float bgColor[3], VkViewport & viewport, VkRect2D & scissor, std::vector< VkCommandBuffer > & commandBuffers) pure virtual
Implemented in Chronos::Engine::ColoredRectangle, Chronos::Engine::TexturedRectangle, and Chronos::Engine::Text.
update()
virtual void Chronos::Engine::Object::update (uint32_t currentFrame) pure virtual
Updates the object for the current frame.
This pure virtual method must be implemented by derived classes to perform any updates required for the object during each frame. The currentFrame parameter represents the index of the current frame in the application.
Parameters
currentFrame Index of the current frame.
Implemented in Chronos::Engine::ColoredRectangle, Chronos::Engine::TexturedRectangle, and Chronos::Engine::Text.
Member Data Documentation
commandPool
VkCommandPool Chronos::Engine::Object::commandPool protected
Vulkan command pool associated with the object.
Definition at line 140 of file object.hpp.
descriptorPool
VkDescriptorPool Chronos::Engine::Object::descriptorPool protected
Vulkan descriptor pool used by the object.
Definition at line 149 of file object.hpp.
descriptorSetLayout
VkDescriptorSetLayout Chronos::Engine::Object::descriptorSetLayout protected
Vulkan descriptor set layout used by the object.
Definition at line 146 of file object.hpp.
descriptorSets
std::vector<VkDescriptorSet> Chronos::Engine::Object::descriptorSets
Vulkan descriptor sets associated with the object.
Definition at line 129 of file object.hpp.
device
Chronos::Engine::Device* Chronos::Engine::Object::device protected
Device to render to.
Definition at line 137 of file object.hpp.
fragmentShaderPath
std::string Chronos::Engine::Object::fragmentShaderPath protected
Path to the fragment shader file.
Definition at line 136 of file object.hpp.
graphicsPipeline
VkPipeline Chronos::Engine::Object::graphicsPipeline
Vulkan graphics pipeline used by the object.
Definition at line 124 of file object.hpp.
objectType
Chronos::Engine::ObjectType Chronos::Engine::Object::objectType
Type of the object.
Definition at line 131 of file object.hpp.
pipelineLayout
VkPipelineLayout Chronos::Engine::Object::pipelineLayout
Vulkan pipeline layout used by the object.
Definition at line 127 of file object.hpp.
renderPass
VkRenderPass* Chronos::Engine::Object::renderPass protected
Renderpass that the object will render to.
Definition at line 144 of file object.hpp.
swapChain
Chronos::Engine::SwapChain* Chronos::Engine::Object::swapChain protected
Swapchain to present to.
Definition at line 138 of file object.hpp.
textureSampler
VkSampler Chronos::Engine::Object::textureSampler protected
Vulkan texture sampler used by the object.
Definition at line 142 of file object.hpp.
uniformBuffers
std::vector<Chronos::Engine::UniformBuffer> Chronos::Engine::Object::uniformBuffers protected
uniform buffers associated with the object.
Definition at line 180 of file object.hpp.
vertexShaderPath
std::string Chronos::Engine::Object::vertexShaderPath protected
Path to the vertex shader file.
Definition at line 134 of file object.hpp.
The documentation for this class was generated from the following files:
Source/Rendering/Objects/object.hpp
Source/Rendering/Objects/object.cpp