Chronos: Chronos::Editor::EditorManager Class Reference
Chronos::Editor::EditorManager Class Reference
#include <editorManager.hpp>
Public Member Functions
void init (Chronos::Manager::Manager *manager)
void addElements ()
Private Member Functions
void MenuBar ()
void ShapeWindow ()
void PolygonWindow ()
void TextureWindow ()
void TextWindow ()
void AnimationWindow ()
void SettingsWindow ()
void TotalCodeGenerationWindow ()
void ShapeDetailsWindow ()
void PolygonDetailsWindow ()
void TextureDetailsWindow ()
void TextDetailsWindow ()
void KeyframeDetailsWindow ()
void DebugMetricsWindow ()
void DebugLogWindow ()
int getKeyframeNo (float *valuePointer)
bool doesKeyframeExist (float *valuePointer)
void keyframeCheckbox (float *valuePointer, std::string name)
void updateKeyframes ()
Private Attributes
Chronos::Manager::Manager * manager
bool pinMenuBar = true
bool showShapeWindow = false
bool showPolygonWindow = false
bool showTextureWindow = false
bool showTextWindow = false
bool showAnimationWindow = false
bool showSettingsWindow = false
bool showGeneratedCodeWindow = false
bool showShapeDetailsWindow = false
bool showPolygonDetailsWindow = false
bool showTextureDetailsWindow = false
bool showTextDetailsWindow = false
bool showKeyframeDetailsWindow = false
bool showDebugMetricsWindow = false
bool showDebugLogWindow = false
Chronos::Manager::ShapeParams newShapeParams
int newShapeType = 0
int newShapeFill = 0
int currentShapeTextureSelection = 0
char currentShapeTextureName [200] = "Select Texture"
int currentShapeSelection = 0
Chronos::Manager::ShapeParams newPolygonParams
int numVertices = 4
std::vector< std::array< float, 2 > > polygonVertices = { { -0.5, -0.5 }, { 0.5, -0.5 }, { 0.5, 0.5 }, { -0.5, 0.5 } }
int currentPolygonTextureSelection = 0
char currentPolygonTextureName [200] = "Select Texture"
int currentPolygonSelection = 0
std::vector< std::array< float, 2 > > currentPolygonVertices
char newTexturePath [200]
char newTextureName [200]
int currentTextureSelection = 0
Chronos::Engine::TextParams newTextParams
std::string currentFontSelection = "consolas"
int currentFontSizeSelection = 6
int currentTextSelection = 0
Chronos::Manager::ShapeParams shapeDetailsShapeParams
int shapeDetailsShapeNo = 0
Chronos::Manager::ShapeParams polygonDetailsShapeParams
int polygonDetailsShapeNo = 0
Chronos::Engine::TextParams textDetailsTextParams
int textDetailsTextNo = 0
int textureDetailsCurrentSelection = 0
char windowTitle [200] = GAME_NAME
std::string presentMode = "mailbox"
float bgColor [3] = { 0, 0, 0 }
bool fullScreen = false
bool isWindowFullscreen = false
std::string msaaSamples = "1"
std::unordered_map< float *, int > floatPointerToKeyframeNo
float * currentKeyframeValuePointer = nullptr
Detailed Description
Definition at line 27 of file editorManager.hpp.
Member Function Documentation
addElements()
void Chronos::Editor::EditorManager::addElements ()
Definition at line 30 of file editorManager.cpp.
 {
     Chronos::Editor::setImGuiStyle();
     this->MenuBar();
     this->ShapeWindow();
     this->PolygonWindow();
     this->TextureWindow();
     this->TextWindow();
     this->AnimationWindow();
     this->SettingsWindow();
     this->TotalCodeGenerationWindow();
     this->ShapeDetailsWindow();
     this->PolygonDetailsWindow();
     this->TextureDetailsWindow();
     this->TextDetailsWindow();
     this->KeyframeDetailsWindow();
     this->DebugMetricsWindow();
     this->DebugLogWindow();
 #ifdef CHRONOS_PROFILING
     this->ProfilingWindow();
 #endif
     this->updateKeyframes();
     LOG(4, "Editor", "Elements added to the editor.")
 }
References AnimationWindow(), DebugLogWindow(), DebugMetricsWindow(), KeyframeDetailsWindow(), LOG, MenuBar(), PolygonDetailsWindow(), PolygonWindow(), Chronos::Editor::setImGuiStyle(), SettingsWindow(), ShapeDetailsWindow(), ShapeWindow(), TextDetailsWindow(), TextureDetailsWindow(), TextureWindow(), TextWindow(), TotalCodeGenerationWindow(), and updateKeyframes().
AnimationWindow()
void Chronos::Editor::EditorManager::AnimationWindow () private
Definition at line 839 of file editorManager.cpp.
 {
     if (this->showAnimationWindow) {
     ImGui::Begin("Animation", &this->showAnimationWindow);
     ImGui::SeparatorText("Animation");
     ImGui::End();
     }
 }
DebugLogWindow()
void Chronos::Editor::EditorManager::DebugLogWindow () private
Definition at line 803 of file editorManager.cpp.
 {
     if (this->showDebugLogWindow) {
     ImGui::ShowDebugLogWindow(&this->showDebugLogWindow);
     }
 }
DebugMetricsWindow()
void Chronos::Editor::EditorManager::DebugMetricsWindow () private
Definition at line 796 of file editorManager.cpp.
 {
     if (this->showDebugMetricsWindow) {
     ImGui::ShowMetricsWindow(&this->showDebugMetricsWindow);
     }
 }
doesKeyframeExist()
bool Chronos::Editor::EditorManager::doesKeyframeExist (float * valuePointer) private
Definition at line 874 of file editorManager.cpp.
 {
     if (this->getKeyframeNo(valuePointer) == -1)
     return false;
     return true;
 }
getKeyframeNo()
int Chronos::Editor::EditorManager::getKeyframeNo (float * valuePointer) private
Definition at line 861 of file editorManager.cpp.
 {
     if (!valuePointer) {
     throw std::runtime_error("Value Pointer is null");
     }
     if (this->floatPointerToKeyframeNo.find(valuePointer)
     == this->floatPointerToKeyframeNo.end()) {
     return -1;
     } else {
     return this->floatPointerToKeyframeNo[valuePointer];
     }
 }
init()
void Chronos::Editor::EditorManager::init (Chronos::Manager::Manager * manager) inline
Definition at line 29 of file editorManager.hpp.
     {
         this->manager = manager;
     }
References manager.
keyframeCheckbox()
void Chronos::Editor::EditorManager::keyframeCheckbox (float * valuePointer, std::string name) private
Definition at line 881 of file editorManager.cpp.
 {
     bool isAnimated = this->doesKeyframeExist(valuePointer);
     bool currentChange = isAnimated;
     ImGui::Checkbox(name.c_str(), &currentChange);
     if (currentChange != isAnimated) {
     LOG(3, "EditorManager",
         "Animate checkbox changed for valuePointer ["
         + std::to_string((long long)valuePointer) + "]");
     if (currentChange) {
         int keyframeNo = this->manager->addKeyframeVariable(
         { { 0, *valuePointer }, { 100, *valuePointer } });
         this->floatPointerToKeyframeNo[valuePointer] = keyframeNo;
         LOG(3, "EditorManager",
         "Added keyframe for valuePointer ["
             + std::to_string((long long)valuePointer) + "] with keyframeNo ["
             + std::to_string(keyframeNo) + "]")
     } else {
         int keyframeNo = this->getKeyframeNo(valuePointer);
         if (keyframeNo == -1) {
         throw std::runtime_error("Could not find keyframe number!!!");
         }
         this->manager->removeKeyframeVariable(keyframeNo);
         this->floatPointerToKeyframeNo.erase(valuePointer);
         LOG(3, "EditorManager",
         "Removed keyframe for valuePointer ["
             + std::to_string((long long)valuePointer) + "] with keyframeNo ["
             + std::to_string(keyframeNo) + "]")
     }
     }
     if (currentChange) {
     ImGui::SameLine();
     if (ImGui::Button("Keyframe Details")) {
         this->showKeyframeDetailsWindow = true;
         this->currentKeyframeValuePointer = valuePointer;
     }
     }
 }
References LOG.
KeyframeDetailsWindow()
void Chronos::Editor::EditorManager::KeyframeDetailsWindow () private
Definition at line 848 of file editorManager.cpp.
 {
     if (this->showKeyframeDetailsWindow) {
     ImGui::Begin("Keyframe Details", &this->showKeyframeDetailsWindow);
     ImGui::SeparatorText("Keyframe Details");
     ImGui::Text("Current Value pointer: %p",
         (void*)this->currentKeyframeValuePointer);
     int keyframeNo = this->getKeyframeNo(this->currentKeyframeValuePointer);
     ImGui::Text("Keyframe Number: %d", keyframeNo);
     ImGui::End();
     }
 }
MenuBar()
void Chronos::Editor::EditorManager::MenuBar () private
Definition at line 56 of file editorManager.cpp.
 {
     if (this->pinMenuBar) {
     if (ImGui::BeginMainMenuBar()) {
         ImGui::MenuItem("Shape", NULL, &this->showShapeWindow);
         ImGui::MenuItem("Polygon", NULL, &this->showPolygonWindow);
         ImGui::MenuItem("Texture", NULL, &this->showTextureWindow);
         ImGui::MenuItem("Text", NULL, &this->showTextWindow);
         ImGui::MenuItem("Animation", NULL, &this->showAnimationWindow);
         ImGui::MenuItem("Settings", NULL, &this->showSettingsWindow);
         ImGui::MenuItem(
         "Generated Code", NULL, &this->showGeneratedCodeWindow);
 #ifdef CHRONOS_PROFILING
         ImGui::MenuItem("Profiling", NULL, &this->showProfilingWindow);
 #endif
         ImGui::EndMainMenuBar();
     }
     } else {
     ImGui::Begin("Editor", nullptr, ImGuiWindowFlags_MenuBar);
     if (ImGui::BeginMenuBar()) {
         ImGui::MenuItem("Shape", NULL, &this->showShapeWindow);
         ImGui::MenuItem("Polygon", NULL, &this->showPolygonWindow);
         ImGui::MenuItem("Texture", NULL, &this->showTextureWindow);
         ImGui::MenuItem("Text", NULL, &this->showTextWindow);
         ImGui::MenuItem("Animation", NULL, &this->showAnimationWindow);
         ImGui::MenuItem("Settings", NULL, &this->showSettingsWindow);
         ImGui::MenuItem(
         "Generated Code", NULL, &this->showGeneratedCodeWindow);
         ImGui::EndMenuBar();
     }
     ImGui::End();
     }
 }
PolygonDetailsWindow()
void Chronos::Editor::EditorManager::PolygonDetailsWindow () private
Definition at line 683 of file editorManager.cpp.
 {
     if (this->showPolygonDetailsWindow) {
     ImGui::Begin("Polygon Details", &this->showPolygonDetailsWindow);
     ImGui::SeparatorText("Polygon Details");
     std::vector<std::pair<int, Chronos::Manager::ShapeParams>>
         polygonDetails = this->manager->getPolygonDetails();
     if (polygonDetails.size() == 0) {
         ImGui::Text("No Polygons");
     } else {
         ImGui::InputText(
         "Polygon Name", this->polygonDetailsShapeParams.shapeName, 200);
         ImGui::DragFloat("X(-1 to 1)", &this->polygonDetailsShapeParams.x,
         0.01f, -1.0f, 1.0f);
         ImGui::DragFloat("Y(-1 to 1)", &this->polygonDetailsShapeParams.y,
         0.01f, -1.0f, 1.0f);
         ImGui::DragFloat("X Size", &this->polygonDetailsShapeParams.xSize,
         0.01f, 0.0f, FLT_MAX);
         ImGui::DragFloat("Y Size", &this->polygonDetailsShapeParams.ySize,
         0.01f, 0.0f, FLT_MAX);
         ImGui::DragFloat("Rotation",
         &this->polygonDetailsShapeParams.rotation, 0.01f, 0.0f,
         FLT_MAX);
         this->currentPolygonVertices = this->manager->getPolygonVertices(
         this->polygonDetailsShapeNo);
         ImGui::SeparatorText("Polygon Vertices");
         for (int i = 0;
          i < static_cast<int>(this->currentPolygonVertices.size());
          i++) {
         ImGui::Text("Vertex %d", i);
         ImGui::DragFloat(
             ("X " + std::to_string(i + 1) + "(-1 to 1)").c_str(),
             &this->currentPolygonVertices[i][0], 0.01f, -1.0f, 1.0f);
         ImGui::DragFloat(
             ("Y " + std::to_string(i + 1) + "(-1 to 1)").c_str(),
             &this->currentPolygonVertices[i][1], 0.01f, -1.0f, 1.0f);
         }
         this->manager->updatePolygon(this->polygonDetailsShapeNo,
         this->polygonDetailsShapeParams, this->currentPolygonVertices);
     }
     ImGui::End();
     }
 }
PolygonWindow()
void Chronos::Editor::EditorManager::PolygonWindow () private
Definition at line 227 of file editorManager.cpp.
 {
     if (this->showPolygonWindow) {
     bool doesPolygonExist = false;
     ImGui::Begin("Polygon", &this->showPolygonWindow);
     ImGui::SeparatorText("Add Polygon");
     ImGui::SeparatorText("Polygon Name");
     ImGui::InputText("Polygon Name", this->newPolygonParams.shapeName, 200);
     std::vector<std::pair<int, Chronos::Manager::ShapeParams>>
         namePolygonDetails = this->manager->getPolygonDetails();
     for (std::pair<int, Chronos::Manager::ShapeParams> polygonDetail :
         namePolygonDetails) {
         if (!strcmp(this->newPolygonParams.shapeName,
             polygonDetail.second.shapeName)) {
         ImGui::Text("Name Already Exists");
         doesPolygonExist = true;
         break;
         }
     }
     ImGui::SeparatorText("Properties");
     ImGui::DragFloat(
         "X(-1 to 1)", &this->newPolygonParams.x, 0.01f, -1.0f, 1.0f);
     ImGui::DragFloat(
         "Y(-1 to 1)", &this->newPolygonParams.y, 0.01f, -1.0f, 1.0f);
     ImGui::DragFloat(
         "X Size", &this->newPolygonParams.xSize, 0.01f, 0.0f, FLT_MAX);
     ImGui::DragFloat(
         "Y Size", &this->newPolygonParams.ySize, 0.01f, 0.0f, FLT_MAX);
     ImGui::DragFloat(
         "Rotation", &this->newPolygonParams.rotation, 0.01f, 0.0f, FLT_MAX);
     if (ImGui::BeginCombo("Select Texture", currentPolygonTextureName)) {
         std::vector<Chronos::Manager::TextureDetails> details
         = this->manager->getTextureDetails();
         if (details.size() == 0) {
         ImGui::Selectable("No Textures");
         } else {
         for (Chronos::Manager::TextureDetails textureDetail : details) {
             bool isSelected = currentPolygonTextureSelection
             == textureDetail.textureNo;
             if (ImGui::Selectable(
                 textureDetail.textureName.c_str(), isSelected)) {
             currentPolygonTextureSelection
                 = textureDetail.textureNo;
             strcpy(currentPolygonTextureName,
                 textureDetail.textureName.c_str());
             }
             if (isSelected) {
             ImGui::SetItemDefaultFocus();
             }
         }
         }
         ImGui::EndCombo();
     }
     ImGui::SeparatorText("Vertices");
     ImGui::Text("Number of Vertices %d", this->numVertices);
     if (ImGui::Button("Add Vertices")) {
         this->numVertices++;
         this->polygonVertices.push_back({ 0.0f, 0.0f });
         LOG(1, "Editor", "Vertex added to polygon")
     }
     ImGui::SameLine();
     if (ImGui::Button("Remove Vertices")) {
         if (this->numVertices > 3) {
         this->numVertices--;
         this->polygonVertices.pop_back();
         LOG(1, "Editor", "Vertex removed from polygon")
         }
     }
     for (int i = 0; i < this->numVertices; i++) {
         ImGui::Text("Vertex %d", i);
         ImGui::DragFloat(
         ("coord X " + std::to_string(i + 1) + "(-1 to 1)").c_str(),
         &this->polygonVertices[i][0], 0.01f, -1.0f, 1.0f);
         ImGui::DragFloat(
         ("coord Y " + std::to_string(i + 1) + "(-1 to 1)").c_str(),
         &this->polygonVertices[i][1], 0.01f, -1.0f, 1.0f);
     }
     if (!doesPolygonExist) {
         if (ImGui::Button("Add Shape")) {
         this->manager->addPolygon(this->newShapeParams,
             this->currentPolygonTextureSelection,
             this->polygonVertices);
         LOG(1, "Editor",
             "Polygon added with shapeName ["
             + std::string(this->newShapeParams.shapeName) + "]")
         }
     }
     ImGui::SeparatorText("Current Shapes");
     if (ImGui::BeginListBox("Shapes")) {
         std::vector<std::pair<int, Chronos::Manager::ShapeParams>>
         polygonDetails = this->manager->getPolygonDetails();
         if (polygonDetails.size() == 0) {
         ImGui::Selectable("No Polygons");
         } else {
         for (int i = 0; i < static_cast<int>(polygonDetails.size());
              i++) {
             if (ImGui::Selectable(polygonDetails[i].second.shapeName,
                 this->currentPolygonSelection == i)) {
             this->currentPolygonSelection = i;
             }
         }
         }
         ImGui::EndListBox();
         if (polygonDetails.size() > 0) {
         if (ImGui::Button("Edit Polygon")) {
             this->showPolygonDetailsWindow = true;
             this->polygonDetailsShapeNo
             = polygonDetails[currentPolygonSelection].first;
             this->polygonDetailsShapeParams
             = polygonDetails[currentPolygonSelection].second;
             LOG(1, "Editor",
             "Polygon selected for editing with shapeNo ["
                 + std::to_string(this->polygonDetailsShapeNo) + "]")
         }
         ImGui::SameLine();
         if (ImGui::Button("Remove Polygon")) {
             this->manager->removePolygon(
             polygonDetails[currentPolygonSelection].first);
             LOG(1, "Editor",
             "Polygon removed with shapeNo ["
                 + std::to_string(
                 polygonDetails[currentPolygonSelection].first)
                 + "]")
         }
         }
     }
     ImGui::End();
     }
 }
References LOG.
SettingsWindow()
void Chronos::Editor::EditorManager::SettingsWindow () private
Definition at line 551 of file editorManager.cpp.
 {
     if (this->showSettingsWindow) {
     ImGui::Begin("Settings", &this->showSettingsWindow);
     ImGui::SeparatorText("Build Information");
     ImGui::Text("Engine name: %s", "Chronos");
     ImGui::Text("Build Version: %d.%d.%d", CHRONOS_VERSION_MAJOR,
         CHRONOS_VERSION_MINOR, CHRONOS_VERSION_PATCH);
     ImGui::Text("Build Date: %s", __DATE__);
     ImGui::Text("Build Time: %s", __TIME__);
     ImGui::SeparatorText("Window Settings");
     ImGui::InputText("Window Title", this->windowTitle, 200);
     if (ImGui::Button("Update Window Title")) {
         glfwSetWindowTitle(this->manager->getWindow(), this->windowTitle);
         LOG(1, "Editor",
         "Window title updated to [" + std::string(this->windowTitle)
             + "]")
     }
     ImGui::Checkbox("Make Window Fullscreen", &this->fullScreen);
     if (this->fullScreen && !this->isWindowFullscreen) {
         GLFWwindow* window = this->manager->getWindow();
         const GLFWvidmode* mode = glfwGetVideoMode(glfwGetPrimaryMonitor());
         glfwSetWindowMonitor(window, glfwGetPrimaryMonitor(), 0, 0,
         mode->width, mode->height, mode->refreshRate);
         this->isWindowFullscreen = true;
         LOG(1, "Editor", "Window set to fullscreen")
     } else if (!this->fullScreen && this->isWindowFullscreen) {
         GLFWwindow* window = this->manager->getWindow();
         glfwSetWindowMonitor(window, nullptr, 0, 0, 800, 600, 0);
         this->isWindowFullscreen = false;
         LOG(1, "Editor", "Window set to windowed mode")
     }
     ImGui::SeparatorText("Present Mode");
     if (ImGui::BeginCombo("Present Mode", this->presentMode.c_str())) {
         if (ImGui::Selectable("mailbox", this->presentMode == "mailbox")) {
         this->presentMode = "mailbox";
         }
         if (ImGui::Selectable(
             "immediate", this->presentMode == "immediate")) {
         this->presentMode = "immediate";
         }
         if (ImGui::Selectable("fifo", this->presentMode == "fifo")) {
         this->presentMode = "fifo";
         }
         if (ImGui::Selectable(
             "fifo_relaxed", this->presentMode == "fifo_relaxed")) {
         this->presentMode = "fifo_relaxed";
         }
         ImGui::EndCombo();
     }
     if (ImGui::Button("Update Present Mode")) {
         this->manager->changePresentMode(this->presentMode);
         LOG(1, "Editor",
         "Present mode updated to [" + this->presentMode + "]")
     }
     ImGui::SeparatorText("MSAA Samples");
     std::vector<std::string> msaaSamples = this->manager->getMSAAModes();
     for (std::string sample : msaaSamples) {
         if (ImGui::Selectable(
             sample.c_str(), this->msaaSamples == sample)) {
         this->msaaSamples = sample;
         }
     }
     if (ImGui::Button("Update MSAA Samples")) {
         this->manager->changeMSAA(this->msaaSamples);
         LOG(1, "Editor",
         "MSAA Samples updated to [" + this->msaaSamples + "]")
     }
     ImGui::SeparatorText("Background Color");
     ImGui::ColorEdit3("Background Color", this->bgColor);
     if (ImGui::Button("Update Background Color")) {
         this->manager->changeBackgroundColor(
         this->bgColor[0], this->bgColor[1], this->bgColor[2]);
         LOG(1, "Editor",
         "Background color updated to ["
             + std::to_string(this->bgColor[0]) + ", "
             + std::to_string(this->bgColor[1]) + ", "
             + std::to_string(this->bgColor[2]) + "]")
     }
     ImGui::SeparatorText("ImGui Debug Settings");
     ImGui::Checkbox("Show Metrics", &this->showDebugMetricsWindow);
     ImGui::Checkbox("Show Log", &this->showDebugLogWindow);
     ImGui::Checkbox("Pin Menu Bar", &this->pinMenuBar);
     ImGui::End();
     }
 }
References LOG.
ShapeDetailsWindow()
void Chronos::Editor::EditorManager::ShapeDetailsWindow () private
Definition at line 644 of file editorManager.cpp.
 {
     if (this->showShapeDetailsWindow) {
     ImGui::Begin("Shape Details", &this->showShapeDetailsWindow);
     ImGui::SeparatorText("Shape Details");
     if (this->manager->getShapeDetails().size() == 0) {
         ImGui::Text("No Shapes");
     } else {
         ImGui::InputText(
         "Shape Name", this->shapeDetailsShapeParams.shapeName, 200);
         ImGui::DragFloat("X(-1 to 1)", &this->shapeDetailsShapeParams.x,
         0.01f, -1.0f, 1.0f);
         ImGui::SameLine();
         this->keyframeCheckbox(&this->shapeDetailsShapeParams.x, "X");
         ImGui::DragFloat("Y(-1 to 1)", &this->shapeDetailsShapeParams.y,
         0.01f, -1.0f, 1.0f);
         ImGui::SameLine();
         this->keyframeCheckbox(&this->shapeDetailsShapeParams.y, "Y");
         ImGui::DragFloat("X Size", &this->shapeDetailsShapeParams.xSize,
         0.01f, 0.0f, FLT_MAX);
         ImGui::SameLine();
         this->keyframeCheckbox(&this->shapeDetailsShapeParams.xSize, "X size");
         ImGui::DragFloat("Y Size", &this->shapeDetailsShapeParams.ySize,
         0.01f, 0.0f, FLT_MAX);
         ImGui::SameLine();
         this->keyframeCheckbox(&this->shapeDetailsShapeParams.ySize, "Y size");
         ImGui::DragFloat("Rotation",
         &this->shapeDetailsShapeParams.rotation, 0.01f, 0.0f, FLT_MAX);
         ImGui::SameLine();
         this->keyframeCheckbox(&this->shapeDetailsShapeParams.rotation, "Rotation");
         ImGui::ColorEdit3(
         "Color", this->shapeDetailsShapeParams.color.data());
         this->manager->updatePolygon(
         this->shapeDetailsShapeNo, this->shapeDetailsShapeParams);
     }
     ImGui::End();
     }
 }
ShapeWindow()
void Chronos::Editor::EditorManager::ShapeWindow () private
Definition at line 90 of file editorManager.cpp.
 {
     if (this->showShapeWindow) {
     ImGui::Begin("Shape", &this->showShapeWindow);
     bool doesNameExist = false;
     ImGui::SeparatorText("Shape Name");
     ImGui::InputText("Shape Name", this->newShapeParams.shapeName, 200);
     std::vector<std::pair<int, Chronos::Manager::ShapeParams>>
         nameShapeDetails = this->manager->getShapeDetails();
     for (std::pair<int, Chronos::Manager::ShapeParams> shapeDetail :
         nameShapeDetails) {
         if (!strcmp(this->newShapeParams.shapeName,
             shapeDetail.second.shapeName)) {
         ImGui::Text("Name Already Exists");
         doesNameExist = true;
         break;
         }
     }
     ImGui::SeparatorText("Type");
     ImGui::RadioButton("Triangle", &this->newShapeType, 0);
     ImGui::RadioButton("Rectangle", &this->newShapeType, 1);
     ImGui::SeparatorText("Fill");
     ImGui::RadioButton("Color", &this->newShapeFill, 0);
     ImGui::RadioButton("Texture", &this->newShapeFill, 1);
     ImGui::SeparatorText("Properties");
     ImGui::DragFloat(
         "X(-1 to 1)", &this->newShapeParams.x, 0.01f, -1.0f, 1.0f);
     ImGui::DragFloat(
         "Y(-1 to 1)", &this->newShapeParams.y, 0.01f, -1.0f, 1.0f);
     ImGui::DragFloat(
         "X Size", &this->newShapeParams.xSize, 0.01f, 0.0f, FLT_MAX);
     ImGui::DragFloat(
         "Y Size", &this->newShapeParams.ySize, 0.01f, 0.0f, FLT_MAX);
     ImGui::DragFloat(
         "Rotation", &this->newShapeParams.rotation, 0.01f, 0.0f, FLT_MAX);
     switch (this->newShapeFill) {
     case 0:
         ImGui::ColorEdit3("Color", this->newShapeParams.color.data());
         break;
     case 1:
         if (ImGui::BeginCombo("Select Texture", currentShapeTextureName)) {
         std::vector<Chronos::Manager::TextureDetails> details
             = this->manager->getTextureDetails();
         if (details.size() == 0) {
             ImGui::Selectable("No Textures");
         } else {
             for (Chronos::Manager::TextureDetails textureDetail :
             details) {
             bool isSelected = currentShapeTextureSelection
                 == textureDetail.textureNo;
             if (ImGui::Selectable(textureDetail.textureName.c_str(),
                 isSelected)) {
                 currentShapeTextureSelection
                 = textureDetail.textureNo;
                 strcpy(currentShapeTextureName,
                 textureDetail.textureName.c_str());
                 LOG(1, "Editor",
                 "Texture selected for shapeNo ["
                     + std::to_string(
                     currentShapeTextureSelection)
                     + "], textureName ["
                     + currentShapeTextureName + "]")
             }
             if (isSelected) {
                 ImGui::SetItemDefaultFocus();
             }
             }
         }
         ImGui::EndCombo();
         }
     }
     if (!doesNameExist) {
         if (ImGui::Button("Add Shape")) {
         Chronos::Manager::PolygonType type;
         switch (this->newShapeType) {
         case 0:
             type.triangle = true;
             break;
         case 1:
             type.rectangle = true;
             break;
         }
         switch (this->newShapeFill) {
         case 0:
             this->manager->addPolygon(this->newShapeParams, type);
             LOG(1, "Editor",
             "Colored shape added with shapeName ["
                 + std::string(this->newShapeParams.shapeName) + "]")
             break;
         case 1:
             this->manager->addPolygon(this->newShapeParams, type,
             this->currentShapeTextureSelection);
             LOG(1, "Editor",
             "Textured shape added with shapeName ["
                 + std::string(this->newShapeParams.shapeName) + "]")
             break;
         }
         }
     }
     ImGui::SeparatorText("Current Shapes");
     if (ImGui::BeginListBox("Shapes")) {
         std::vector<std::pair<int, Chronos::Manager::ShapeParams>>
         shapeDetails = this->manager->getShapeDetails();
         if (shapeDetails.size() == 0) {
         ImGui::Selectable("No Shapes");
         } else {
         for (int i = 0; i < static_cast<int>(shapeDetails.size());
              i++) {
             if (ImGui::Selectable(shapeDetails[i].second.shapeName,
                 this->currentShapeSelection == i)) {
             this->currentShapeSelection = i;
             }
         }
         }
         ImGui::EndListBox();
         if (shapeDetails.size() > 0) {
         ImGui::Text("Selected Shape: %d",
             shapeDetails[currentShapeSelection].first);
         if (ImGui::Button("Edit Shape")) {
             this->showShapeDetailsWindow = true;
             this->shapeDetailsShapeNo
             = shapeDetails[currentShapeSelection].first;
             this->shapeDetailsShapeParams
             = shapeDetails[currentShapeSelection].second;
         }
         ImGui::SameLine();
         if (ImGui::Button("Remove Shape")) {
             this->manager->removePolygon(
             shapeDetails[currentShapeSelection].first);
         }
         }
     }
     ImGui::End();
     }
 }
References LOG, Chronos::Manager::PolygonType::rectangle, and Chronos::Manager::PolygonType::triangle.
TextDetailsWindow()
void Chronos::Editor::EditorManager::TextDetailsWindow () private
Definition at line 762 of file editorManager.cpp.
 {
     if (this->showTextDetailsWindow) {
     ImGui::Begin("Text Details", &this->showTextDetailsWindow);
     ImGui::SeparatorText("Text Details");
     std::vector<std::pair<int, Chronos::Engine::TextParams>> textDetails
         = this->manager->getTextDetails();
     if (textDetails.size() == 0) {
         ImGui::Text("No Text");
     } else {
         char inputText[2048];
         strcpy(inputText, this->textDetailsTextParams.text.c_str());
         ImGui::InputText("Text", inputText, 2048);
         if (inputText[0] != '\0') {
         this->textDetailsTextParams.text = inputText;
         ImGui::Text("Text Field cannot be empty");
         }
         ImGui::DragFloat("X(-1 to 1)", &this->textDetailsTextParams.x,
         0.01f, -1.0f, 1.0f);
         ImGui::DragFloat("Y(-1 to 1)", &this->textDetailsTextParams.y,
         0.01f, -1.0f, 1.0f);
         ImGui::DragFloat("Rotation", &this->textDetailsTextParams.rotation,
         0.01f, 0.0f, FLT_MAX);
         ImGui::DragFloat("Scale", &this->textDetailsTextParams.scale, 0.01f,
         0.0f, FLT_MAX);
         ImGui::ColorEdit3(
         "Color", this->textDetailsTextParams.color.data());
         this->manager->updateText(
         this->textDetailsTextNo, this->textDetailsTextParams);
     }
     ImGui::End();
     }
 }
TextureDetailsWindow()
void Chronos::Editor::EditorManager::TextureDetailsWindow () private
Definition at line 728 of file editorManager.cpp.
 {
     if (this->showTextureDetailsWindow) {
     ImGui::Begin("Texture Details", &this->showTextureDetailsWindow);
     ImGui::SeparatorText("Texture Details");
     std::vector<Chronos::Manager::TextureDetails> textureDetails
         = this->manager->getTextureDetails();
     if (textureDetails.size() == 0) {
         ImGui::Text("No Textures");
     } else {
         ImGui::Text("Texture Name: %s",
         textureDetails[this->textureDetailsCurrentSelection]
             .textureName.data());
         ImGui::Text("Texture Path: %s",
         textureDetails[this->textureDetailsCurrentSelection]
             .texturePath.data());
         ImGui::Text("Width: %d",
         textureDetails[this->textureDetailsCurrentSelection].width);
         ImGui::Text("Height: %d",
         textureDetails[this->textureDetailsCurrentSelection].height);
         ImGui::SeparatorText("Texture Preview");
         ImGui::Image(
         (ImTextureID)
             textureDetails[this->textureDetailsCurrentSelection]
             .descriptorSet,
         ImVec2(
             textureDetails[this->textureDetailsCurrentSelection].width,
             textureDetails[this->textureDetailsCurrentSelection]
             .height));
     }
     ImGui::End();
     }
 }
TextureWindow()
void Chronos::Editor::EditorManager::TextureWindow () private
Definition at line 359 of file editorManager.cpp.
 {
     if (this->showTextureWindow) {
     ImGui::Begin("Texture", &this->showTextureWindow);
     bool doesTextureExist = false;
     ImGui::SeparatorText("Add Textures");
     ImGui::InputText("Texture Path", this->newTexturePath, 200);
     ImGui::InputText("Texture Name", this->newTextureName, 200);
     std::vector<Chronos::Manager::TextureDetails> nameTextureDetails
         = this->manager->getTextureDetails();
     for (Chronos::Manager::TextureDetails textureDetail :
         nameTextureDetails) {
         if (!strcmp(
             this->newTextureName, textureDetail.textureName.c_str())) {
         ImGui::Text("Name Already Exists");
         doesTextureExist = true;
         break;
         }
         if (std::string(this->newTextureName).size() == '\0') {
         ImGui::Text("Name Cannot be empty");
         doesTextureExist = true;
         break;
         }
         if (!std::string(this->newTexturePath).ends_with(".jpg")
         && !std::string(this->newTexturePath).ends_with(".png")) {
         ImGui::Text("Only jpg and png files are supported");
         doesTextureExist = true;
         break;
         }
     }
     if (!doesTextureExist) {
         if (ImGui::Button("Add Texture")) {
         this->manager->addTexture(
             this->newTexturePath, this->newTextureName);
         this->newTexturePath[0] = '\0';
         LOG(1, "Editor",
             "Texture added with textureName ["
             + std::string(this->newTextureName)
             + "] and texturePath [" + this->newTexturePath + "]")
         }
     }
     ImGui::SeparatorText("Current Textures");
     std::vector<Chronos::Manager::TextureDetails> details
         = this->manager->getTextureDetails();
     if (ImGui::BeginListBox("Textures")) {
         if (details.size() == 0) {
         ImGui::Selectable("No Textures");
         } else {
         for (int i = 0; i < static_cast<int>(details.size()); i++) {
             if (ImGui::Selectable(details[i].textureName.c_str(),
                 currentTextureSelection == i)) {
             currentTextureSelection = i;
             }
         }
         }
         ImGui::EndListBox();
     }
     if (details.size() > 0) {
         if (ImGui::Button("Remove Texture")) {
         this->manager->removeTexture(
             details[currentTextureSelection].textureNo);
         LOG(1, "Editor",
             "Texture removed with textureNo ["
             + std::to_string(
                 details[currentTextureSelection].textureNo)
             + "]")
         }
         ImGui::SameLine();
         if (ImGui::Button("View Texture Details")) {
         this->showTextureDetailsWindow = true;
         LOG(1, "Editor",
             "Texture selected for editing with textureNo ["
             + std::to_string(this->textureDetailsCurrentSelection)
             + "]")
         }
     }
     ImGui::End();
     }
 }
References LOG.
TextWindow()
void Chronos::Editor::EditorManager::TextWindow () private
Definition at line 440 of file editorManager.cpp.
 {
     if (this->showTextWindow) {
     ImGui::Begin("Text", &this->showTextWindow);
     ImGui::SeparatorText("Add Text");
     char inputText[2048];
     strcpy(inputText, this->newTextParams.text.c_str());
     ImGui::InputText("Text", inputText, 2048);
     this->newTextParams.text = inputText;
     ImGui::DragFloat(
         "X(-1 to 1)", &this->newTextParams.x, 0.01f, -1.0f, 1.0f);
     ImGui::DragFloat(
         "Y(-1 to 1)", &this->newTextParams.y, 0.01f, -1.0f, 1.0f);
     ImGui::DragFloat(
         "Rotation", &this->newTextParams.rotation, 0.01f, 0.0f, FLT_MAX);
     ImGui::DragFloat(
         "Scale", &this->newTextParams.scale, 0.01f, 0.0f, FLT_MAX);
     ImGui::ColorEdit3("Color", this->newTextParams.color.data());
     if (ImGui::BeginCombo(
         "Select Font", this->currentFontSelection.c_str())) {
         if (ImGui::Selectable(
             "consolas", this->currentFontSelection == "consolas")) {
         this->currentFontSelection = "consolas";
         LOG(1, "Editor",
             "Font selected [" + this->currentFontSelection + "]")
         }
         if (ImGui::Selectable("consolas_bold",
             this->currentFontSelection == "consolas_bold")) {
         this->currentFontSelection = "consolas_bold";
         LOG(1, "Editor",
             "Font selected [" + this->currentFontSelection + "]")
         }
         if (ImGui::Selectable(
             "arial", this->currentFontSelection == "arial")) {
         this->currentFontSelection = "arial";
         LOG(1, "Editor",
             "Font selected [" + this->currentFontSelection + "]")
         }
         if (ImGui::Selectable(
             "arial_bold", this->currentFontSelection == "arial_bold")) {
         this->currentFontSelection = "arial_bold";
         LOG(1, "Editor",
             "Font selected [" + this->currentFontSelection + "]")
         }
         if (ImGui::Selectable(
             "times", this->currentFontSelection == "times")) {
         this->currentFontSelection = "times";
         LOG(1, "Editor",
             "Font selected [" + this->currentFontSelection + "]")
         }
         if (ImGui::Selectable(
             "times_bold", this->currentFontSelection == "times_bold")) {
         this->currentFontSelection = "times_bold";
         LOG(1, "Editor",
             "Font selected [" + this->currentFontSelection + "]")
         }
         ImGui::EndCombo();
     }
     ImGui::DragInt("Font Size", &this->currentFontSizeSelection, 1, 6, 50);
     if (this->newTextParams.text.size() == 0) {
         ImGui::Text("Text Cannot be empty");
     } else {
         if (ImGui::Button("Add Text")) {
         this->manager->addText(this->newTextParams,
             this->currentFontSelection, this->currentFontSizeSelection);
         LOG(1, "Editor",
             "Text added with text [" + this->newTextParams.text + "]")
         }
     }
     ImGui::SeparatorText("Current Text");
     if (ImGui::BeginListBox("Text")) {
         std::vector<std::pair<int, Chronos::Engine::TextParams>> textDetails
         = this->manager->getTextDetails();
         if (textDetails.size() == 0) {
         ImGui::Selectable("No Text");
         } else {
         for (int i = 0; i < static_cast<int>(textDetails.size()); i++) {
             if (ImGui::Selectable(textDetails[i].second.text.c_str(),
                 this->currentTextSelection == i)) {
             this->currentTextSelection = i;
             }
         }
         }
         ImGui::EndListBox();
         if (textDetails.size() > 0) {
         if (ImGui::Button("Edit Text")) {
             this->showTextDetailsWindow = true;
             this->textDetailsTextNo
             = textDetails[currentTextSelection].first;
             this->textDetailsTextParams
             = textDetails[currentTextSelection].second;
             LOG(1, "Editor",
             "Text selected for editing with textNo ["
                 + std::to_string(this->textDetailsTextNo) + "]")
         }
         ImGui::SameLine();
         if (ImGui::Button("Remove Text")) {
             this->manager->removeText(
             textDetails[currentTextSelection].first);
             LOG(1, "Editor",
             "Text removed with textNo ["
                 + std::to_string(
                 textDetails[currentTextSelection].first)
                 + "]")
         }
         }
     }
     ImGui::End();
     }
 }
References LOG.
TotalCodeGenerationWindow()
void Chronos::Editor::EditorManager::TotalCodeGenerationWindow () private
Definition at line 827 of file editorManager.cpp.
 {
     if (this->showGeneratedCodeWindow) {
     ImGui::Begin("Generated Code", &this->showGeneratedCodeWindow);
     ImGui::SeparatorText("Generated Code");
     std::string code = Chronos::Editor::generateCode(this->manager);
     ImGui::InputTextMultiline("Code", code.data(), code.size(),
         ImVec2(800, 600), ImGuiInputTextFlags_ReadOnly);
     ImGui::End();
     }
 }
References Chronos::Editor::generateCode().
updateKeyframes()
void Chronos::Editor::EditorManager::updateKeyframes () private
Definition at line 920 of file editorManager.cpp.
 {
     for (auto& [key, value] : this->floatPointerToKeyframeNo) {
     *key = this->manager->keyframeGetVariable(value);
     LOG(4, "EditorManager",
         "Updated keyframe value for keyframeNo [" + std::to_string(value)
         + "] to [" + std::to_string(*key) + "]")
     }
 }
References LOG.
Member Data Documentation
bgColor
float Chronos::Editor::EditorManager::bgColor[3] = { 0, 0, 0 } private
Definition at line 132 of file editorManager.hpp.
currentFontSelection
std::string Chronos::Editor::EditorManager::currentFontSelection = "consolas" private
Definition at line 110 of file editorManager.hpp.
currentFontSizeSelection
int Chronos::Editor::EditorManager::currentFontSizeSelection = 6 private
Definition at line 111 of file editorManager.hpp.
currentKeyframeValuePointer
float* Chronos::Editor::EditorManager::currentKeyframeValuePointer = nullptr private
Definition at line 139 of file editorManager.hpp.
currentPolygonSelection
int Chronos::Editor::EditorManager::currentPolygonSelection = 0 private
Definition at line 100 of file editorManager.hpp.
currentPolygonTextureName
char Chronos::Editor::EditorManager::currentPolygonTextureName[200] = "Select Texture" private
Definition at line 99 of file editorManager.hpp.
currentPolygonTextureSelection
int Chronos::Editor::EditorManager::currentPolygonTextureSelection = 0 private
Definition at line 98 of file editorManager.hpp.
currentPolygonVertices
std::vector<std::array<float, 2> > Chronos::Editor::EditorManager::currentPolygonVertices private
Definition at line 101 of file editorManager.hpp.
currentShapeSelection
int Chronos::Editor::EditorManager::currentShapeSelection = 0 private
Definition at line 91 of file editorManager.hpp.
currentShapeTextureName
char Chronos::Editor::EditorManager::currentShapeTextureName[200] = "Select Texture" private
Definition at line 90 of file editorManager.hpp.
currentShapeTextureSelection
int Chronos::Editor::EditorManager::currentShapeTextureSelection = 0 private
Definition at line 89 of file editorManager.hpp.
currentTextSelection
int Chronos::Editor::EditorManager::currentTextSelection = 0 private
Definition at line 112 of file editorManager.hpp.
currentTextureSelection
int Chronos::Editor::EditorManager::currentTextureSelection = 0 private
Definition at line 106 of file editorManager.hpp.
floatPointerToKeyframeNo
std::unordered_map<float*, int> Chronos::Editor::EditorManager::floatPointerToKeyframeNo private
Definition at line 138 of file editorManager.hpp.
fullScreen
bool Chronos::Editor::EditorManager::fullScreen = false private
Definition at line 133 of file editorManager.hpp.
isWindowFullscreen
bool Chronos::Editor::EditorManager::isWindowFullscreen = false private
Definition at line 134 of file editorManager.hpp.
manager
Chronos::Manager::Manager* Chronos::Editor::EditorManager::manager private
Definition at line 36 of file editorManager.hpp.
msaaSamples
std::string Chronos::Editor::EditorManager::msaaSamples = "1" private
Definition at line 135 of file editorManager.hpp.
newPolygonParams
Chronos::Manager::ShapeParams Chronos::Editor::EditorManager::newPolygonParams private
Definition at line 94 of file editorManager.hpp.
newShapeFill
int Chronos::Editor::EditorManager::newShapeFill = 0 private
Definition at line 88 of file editorManager.hpp.
newShapeParams
Chronos::Manager::ShapeParams Chronos::Editor::EditorManager::newShapeParams private
Definition at line 86 of file editorManager.hpp.
newShapeType
int Chronos::Editor::EditorManager::newShapeType = 0 private
Definition at line 87 of file editorManager.hpp.
newTextParams
Chronos::Engine::TextParams Chronos::Editor::EditorManager::newTextParams private
Definition at line 109 of file editorManager.hpp.
newTextureName
char Chronos::Editor::EditorManager::newTextureName[200] private
Definition at line 105 of file editorManager.hpp.
newTexturePath
char Chronos::Editor::EditorManager::newTexturePath[200] private
Definition at line 104 of file editorManager.hpp.
numVertices
int Chronos::Editor::EditorManager::numVertices = 4 private
Definition at line 95 of file editorManager.hpp.
pinMenuBar
bool Chronos::Editor::EditorManager::pinMenuBar = true private
Definition at line 37 of file editorManager.hpp.
polygonDetailsShapeNo
int Chronos::Editor::EditorManager::polygonDetailsShapeNo = 0 private
Definition at line 120 of file editorManager.hpp.
polygonDetailsShapeParams
Chronos::Manager::ShapeParams Chronos::Editor::EditorManager::polygonDetailsShapeParams private
Definition at line 119 of file editorManager.hpp.
polygonVertices
std::vector<std::array<float, 2> > Chronos::Editor::EditorManager::polygonVertices = { { -0.5, -0.5 }, { 0.5, -0.5 }, { 0.5, 0.5 }, { -0.5, 0.5 } } private
Definition at line 96 of file editorManager.hpp.
presentMode
std::string Chronos::Editor::EditorManager::presentMode = "mailbox" private
Definition at line 131 of file editorManager.hpp.
shapeDetailsShapeNo
int Chronos::Editor::EditorManager::shapeDetailsShapeNo = 0 private
Definition at line 116 of file editorManager.hpp.
shapeDetailsShapeParams
Chronos::Manager::ShapeParams Chronos::Editor::EditorManager::shapeDetailsShapeParams private
Definition at line 115 of file editorManager.hpp.
showAnimationWindow
bool Chronos::Editor::EditorManager::showAnimationWindow = false private
Definition at line 43 of file editorManager.hpp.
showDebugLogWindow
bool Chronos::Editor::EditorManager::showDebugLogWindow = false private
Definition at line 54 of file editorManager.hpp.
showDebugMetricsWindow
bool Chronos::Editor::EditorManager::showDebugMetricsWindow = false private
Definition at line 53 of file editorManager.hpp.
showGeneratedCodeWindow
bool Chronos::Editor::EditorManager::showGeneratedCodeWindow = false private
Definition at line 45 of file editorManager.hpp.
showKeyframeDetailsWindow
bool Chronos::Editor::EditorManager::showKeyframeDetailsWindow = false private
Definition at line 51 of file editorManager.hpp.
showPolygonDetailsWindow
bool Chronos::Editor::EditorManager::showPolygonDetailsWindow = false private
Definition at line 48 of file editorManager.hpp.
showPolygonWindow
bool Chronos::Editor::EditorManager::showPolygonWindow = false private
Definition at line 40 of file editorManager.hpp.
showSettingsWindow
bool Chronos::Editor::EditorManager::showSettingsWindow = false private
Definition at line 44 of file editorManager.hpp.
showShapeDetailsWindow
bool Chronos::Editor::EditorManager::showShapeDetailsWindow = false private
Definition at line 47 of file editorManager.hpp.
showShapeWindow
bool Chronos::Editor::EditorManager::showShapeWindow = false private
Definition at line 39 of file editorManager.hpp.
showTextDetailsWindow
bool Chronos::Editor::EditorManager::showTextDetailsWindow = false private
Definition at line 50 of file editorManager.hpp.
showTextureDetailsWindow
bool Chronos::Editor::EditorManager::showTextureDetailsWindow = false private
Definition at line 49 of file editorManager.hpp.
showTextureWindow
bool Chronos::Editor::EditorManager::showTextureWindow = false private
Definition at line 41 of file editorManager.hpp.
showTextWindow
bool Chronos::Editor::EditorManager::showTextWindow = false private
Definition at line 42 of file editorManager.hpp.
textDetailsTextNo
int Chronos::Editor::EditorManager::textDetailsTextNo = 0 private
Definition at line 124 of file editorManager.hpp.
textDetailsTextParams
Chronos::Engine::TextParams Chronos::Editor::EditorManager::textDetailsTextParams private
Definition at line 123 of file editorManager.hpp.
textureDetailsCurrentSelection
int Chronos::Editor::EditorManager::textureDetailsCurrentSelection = 0 private
Definition at line 127 of file editorManager.hpp.
windowTitle
char Chronos::Editor::EditorManager::windowTitle[200] = GAME_NAME private
Definition at line 130 of file editorManager.hpp.
The documentation for this class was generated from the following files:
Source/Editor/Headers/editorManager.hpp
Source/Editor/Source/editorManager.cpp