Chronos: Source/Rendering/device.cpp File Reference
device.cpp File Reference
#include <set>
#include "logging.hpp"
#include "helper.hpp"
#include "swapchain.hpp"
Functions
static bool checkDeviceExtensionSupport (VkPhysicalDevice device)
Checks if the physical device that we provide it supports the extestions we need. This is used to check if the physical device that we provide it supports the extensions that we need.
static bool isDeviceSuitable (VkPhysicalDevice device, VkSurfaceKHR surface)
Checks if the physical device that we provide it is suitable for our needs.
VkSampleCountFlagBits getMaxUsableSampleCount (VkPhysicalDevice physicalDevice)
Gets the maxmimum supported MSAA sample count.
Function Documentation
checkDeviceExtensionSupport()
static bool checkDeviceExtensionSupport (VkPhysicalDevice device) inline static
Checks if the physical device that we provide it supports the extestions we need. This is used to check if the physical device that we provide it supports the extensions that we need.
Parameters
device The physical device to check.
Returns
Whether the physical device supports the extensions that we need.
Definition at line 48 of file device.cpp.
{
    uint32_t extensionCount;
    vkEnumerateDeviceExtensionProperties(
    device, nullptr, &extensionCount, nullptr);
    std::vector<VkExtensionProperties> availableExtensions(extensionCount);
    vkEnumerateDeviceExtensionProperties(
    device, nullptr, &extensionCount, availableExtensions.data());
    std::set<std::string> requiredExtensions(
    Chronos::Engine::deviceExtensions.begin(), Chronos::Engine::deviceExtensions.end());
    for (const auto& extension : availableExtensions) {
    requiredExtensions.erase(extension.extensionName);
    }
    return requiredExtensions.empty();
}
References Chronos::Engine::deviceExtensions.
getMaxUsableSampleCount()
VkSampleCountFlagBits getMaxUsableSampleCount (VkPhysicalDevice physicalDevice)
Gets the maxmimum supported MSAA sample count.
This gets the maximum supported MSAA sample count for the physical device that we provide it.
Parameters
physicalDevice The physical device to get the maxium supported MSAA sample count for.
Returns
The maxium supported MSAA sample count.
Definition at line 114 of file device.cpp.
{
    // used to get max MSAA count
    VkPhysicalDeviceProperties physicalDeviceProperties;
    vkGetPhysicalDeviceProperties(physicalDevice, &physicalDeviceProperties);
    VkSampleCountFlags counts
    = physicalDeviceProperties.limits.framebufferColorSampleCounts;
    if (counts & VK_SAMPLE_COUNT_64_BIT) {
    return VK_SAMPLE_COUNT_64_BIT;
    }
    if (counts & VK_SAMPLE_COUNT_32_BIT) {
    return VK_SAMPLE_COUNT_32_BIT;
    }
    if (counts & VK_SAMPLE_COUNT_16_BIT) {
    return VK_SAMPLE_COUNT_16_BIT;
    }
    if (counts & VK_SAMPLE_COUNT_8_BIT) {
    return VK_SAMPLE_COUNT_8_BIT;
    }
    if (counts & VK_SAMPLE_COUNT_4_BIT) {
    return VK_SAMPLE_COUNT_4_BIT;
    }
    if (counts & VK_SAMPLE_COUNT_2_BIT) {
    return VK_SAMPLE_COUNT_2_BIT;
    }
    return VK_SAMPLE_COUNT_1_BIT;
}
isDeviceSuitable()
static bool isDeviceSuitable (VkPhysicalDevice device, VkSurfaceKHR surface) inline static
Checks if the physical device that we provide it is suitable for our needs.
For a physical device to be suitable, it must support the extensions that we need, and it must be capable of rendering to the surface that we provide it along with rendering the frames.
Parameters
physicalDevice The physical device to check.
surface The surface to which we are rendering.
Returns
Whether the physical device is suitable for our needs.
Definition at line 81 of file device.cpp.
{
    // check if the device has the required queue families
    Chronos::Engine::QueueFamilyIndices indices
    = Chronos::Engine::findQueueFamilies(device, surface);
    bool extensionsSupported
    = checkDeviceExtensionSupport(device);
    bool swapChainAdequate = false;
    if (extensionsSupported) {
    Chronos::Engine::SwapChainSupportDetails swapChainSupport
        = Chronos::Engine::querySwapChainSupport(device, surface);
    swapChainAdequate = !swapChainSupport.formats.empty()
        && !swapChainSupport.presentModes.empty();
    }
    VkPhysicalDeviceFeatures supportedFeatures;
    vkGetPhysicalDeviceFeatures(device, &supportedFeatures);
    return indices.isComplete() && extensionsSupported && swapChainAdequate
    && supportedFeatures.samplerAnisotropy;
}
References checkDeviceExtensionSupport(), Chronos::Engine::findQueueFamilies(), Chronos::Engine::SwapChainSupportDetails::formats, Chronos::Engine::QueueFamilyIndices::isComplete(), Chronos::Engine::SwapChainSupportDetails::presentModes, and Chronos::Engine::querySwapChainSupport().