Chronos: Source/Editor/editorMain.cpp File Reference
editorMain.cpp File Reference
#include "editorManager.hpp"
#include "logging.hpp"
Functions
void addElements ()
int main ()
Variables
Chronos::Editor::EditorManager editorManager
Function Documentation
addElements()
void addElements ()
Definition at line 28 of file editorMain.cpp.
{ editorManager.addElements(); }
References Chronos::Editor::EditorManager::addElements(), and editorManager.
main()
int main ()
Definition at line 30 of file editorMain.cpp.
{
    Chronos::Manager::Initializer initializer;
    initializer.WindowWidth = 800;
    initializer.WindowHeight = 600;
    initializer.BackgroundColor[0] = 0;
    initializer.BackgroundColor[1] = 0;
    initializer.BackgroundColor[2] = 0;
    initializer.editorAddElements = addElements;
    Chronos::Manager::Manager manager(initializer);
    LOG(2, "EditorMain", "Manager created.")
    editorManager.init(&manager);
    LOG(3, "EditorMain", "EditorManager created.")
    // Chronos::Manager::ShapeParams shapeParams;
    // shapeParams.color = {1.0f, 1.0f, 1.0f};
    // shapeParams.xSize = 0.5f;
    // shapeParams.ySize = 0.5f;
    // int shapeNo = manager.addPolygon(shapeParams, {false, true});
    // int keyframeNo = manager.addKeyframeVariable({{0, 0}, {400, 0.1}, {800,
    // 0.5}, {1200, 0.4}, {1600, 0.2}});
    while (!glfwWindowShouldClose(manager.getWindow())) {
    if (glfwGetKey(manager.getWindow(), GLFW_KEY_ESCAPE) == GLFW_PRESS) {
        glfwSetWindowShouldClose(manager.getWindow(), true);
    }
    // shapeParams.x = manager.keyframeGetVariable(keyframeNo);
    // manager.updatePolygon(shapeNo, shapeParams);
    manager.drawFrame();
    LOG(4, "EditorMain", "Frame drawn.")
    }
    LOG(2, "EditorMain", "Exited rendering loop, closing program.")
    return 0;
}
References addElements(), Chronos::Manager::Initializer::BackgroundColor, Chronos::Manager::Manager::drawFrame(), editorManager, Chronos::Manager::Manager::getWindow(), Chronos::Editor::EditorManager::init(), LOG, Chronos::Manager::Initializer::WindowHeight, and Chronos::Manager::Initializer::WindowWidth.
Variable Documentation
editorManager
Chronos::Editor::EditorManager editorManager
Definition at line 26 of file editorMain.cpp.