glslc shader.vert -o vert.spv
glslc shader.frag -o frag.spv
glslc colorShader.vert -o colorVert.spv
glslc colorShader.frag -o colorFrag.spv
glslc textureShader.vert -o textureVert.spv
glslc textureShader.frag -o textureFrag.spv
glslc circle.vert -o circle_vert.spv
glslc circle.frag -o circle_frag.spv
glslc text.vert -o textVert.spv
glslc text.frag -o textFrag.spv