glslc Vertex/shader.vert -o SPIV/vert.spv
glslc Fragment/shader.frag -o SPIV/frag.spv
glslc Vertex/colorShader.vert -o SPIV/colorVert.spv
glslc Fragment/colorShader.frag -o SPIV/colorFrag.spv
glslc Vertex/textureShader.vert -o SPIV/textureVert.spv
glslc Fragment/textureShader.frag -o SPIV/textureFrag.spv
glslc Vertex/circle.vert -o SPIV/circle_vert.spv
glslc Fragment/circle.frag -o SPIV/circle_frag.spv
glslc Vertex/text.vert -o SPIV/textVert.spv
glslc Fragment/text.frag -o SPIV/textFrag.spv