glslc vertex/shader.vert -o SPIV/vert.spv
glslc frag/shader.frag -o SPIV/frag.spv
glslc vertex/colorShader.vert -o SPIV/colorVert.spv
glslc frag/colorShader.frag -o SPIV/colorFrag.spv
glslc vertex/textureShader.vert -o SPIV/textureVert.spv
glslc frag/textureShader.frag -o SPIV/textureFrag.spv
glslc vertex/circle.vert -o SPIV/circle_vert.spv
glslc frag/circle.frag -o SPIV/circle_frag.spv
glslc vertex/text.vert -o SPIV/textVert.spv
glslc frag/text.frag -o SPIV/textFrag.spv
glslc mesh/textureRectangle.mesh -o SPIV/textureRectMesh.spv
glslc mesh/textureTriangle.mesh -o SPIV/textureTriMesh.spv