name: Build and Test

on:
  push:
    branches: [ "master" ]

jobs:
  # build-windows:
  #   name: Windows 
  #   runs-on: windows-latest
  
  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Install dependencies
  #       run: |
  #         git submodule init
  #         git submodule update
  #     - name: Install Vulkan SDK
  #       uses: humbletim/install-vulkan-sdk@v1.1.1
  #       with:
  #          version: 1.3.204.1
  #          cache: true
           
  #     - name: Configure CMake
  #       run: >
  #         cmake -B build -S .
  
  #     - name: Build
  #       run: cmake --build build --parallel
        
  build-linux-gcc:
    name: Linux (GCC)
    runs-on: ubuntu-latest
    env:
      CC: gcc
      CXX: g++
      CFLAGS: -Werror
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies and get git submodules
        run: |
          sudo apt update
          sudo apt install -y libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libxext-dev libwayland-dev libxkbcommon-dev libvulkan-dev libglm-dev gcc-multilib g++-multilib libfreetype6-dev libglu1-mesa-dev freeglut3-dev mesa-common-dev
          git submodule init
          git submodule update
           
      - name: Configure CMake
        run: >
          cmake -B build -S .
  
      - name: Build
        run: cmake --build build --parallel
  
      # - name: Test
      #   working-directory: build
      #   run: ctest --rerun-failed --output-on-failure
      
  build-linux-clang:
    name: Linux (Clang)
    runs-on: ubuntu-latest
    env:
      CC: clang
      CXX: clang++
      CFLAGS: -Werror
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies and get git submodules
      run: |
        sudo rm -f /etc/apt/sources.list.d/ubuntu-toolchain-r-ubuntu-test-jammy.list
        sudo apt update
        sudo apt-get install -y --allow-downgrades libc6=2.35-* libc6-dev=2.35-* libstdc++6=12.3.0-* libgcc-s1=12.3.0-*
        sudo apt install -y libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libxext-dev libwayland-dev libxkbcommon-dev libvulkan-dev libglm-dev gcc-multilib g++-multilib libfreetype6-dev libglu1-mesa-dev freeglut3-dev mesa-common-dev
        sudo apt install -y ninja-build
        git submodule init
        git submodule update
         
    - name: Configure CMake
      run: >
        cmake -B build -S . -GNinja

    - name: Build
      run: cmake --build build --parallel

    # - name: Test
    #   working-directory: build
    #   run: ctest --rerun-failed --output-on-failure
