# This starter workflow is for a CMake project running on multiple platforms. There is a different starter workflow if you just want a single platform.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-single-platform.yml
name: Build and Test

on:
  push:
    branches: [ "master" ]

jobs:
  build-linux-make:
    name: Linux (Make)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libxext-dev libwayland-dev libxkbcommon-dev libvulkan-dev libglm-dev gcc-multilib g++-multilib libfreetype6-dev libglu1-mesa-dev freeglut3-dev mesa-common-dev
          git submodule init
          git submodule update
      - name: Install Vulkan SDK
        uses: humbletim/install-vulkan-sdk@v1.1.1
        with:
           version: 1.3.204.1
           cache: true
           
      - name: Configure CMake
        run: >
          cmake -B build -S .
  
      - name: Build
        run: cmake --build build --parallel
  
      - name: Test
        working-directory: build
        run: ctest
      
  # build-linux-ninja:
  #   name: Linux (Ninja)
  #   runs-on: ubuntu-latest

  #   steps:
  #   - uses: actions/checkout@v3
  #   - name: Install dependencies
  #     run: |
  #       sudo apt update
  #       sudo apt install -y libxinerama-dev libxcursor-dev libxi-dev libxext-dev libwayland-dev libxkbcommon-dev libvulkan-dev libglm-dev gcc-multilib g++-multilib libfreetype6-dev
  #       sudo apt install -y ninja-build
  #       git submodule init
  #       git submodule update
  #   - name: Install Vulkan SDK
  #     uses: humbletim/install-vulkan-sdk@v1.1.1
  #     with:
  #        version: 1.3.204.1
  #        cache: true
         
  #   - name: Configure CMake
  #     run: >
  #       cmake -B build -S .

  #   - name: Build
  #     run: cmake --build build --parallel

  #   - name: Test
  #     working-directory: build
  #     run: ctest
