name: Build and Test

on:
  push:
    branches: [ "*"]

jobs:
  build-windows:
    name: Windows 
    runs-on: ${{ matrix.os }}
    env:
      CXX: ${{ matrix.compiler }}
    strategy:
      matrix:
        os: [windows-latest, windows-2022]
        compiler: [g++, cl]
    steps:
      - uses: actions/checkout@v3
      - name: Get Submodules
        shell: powershell
        run: |
          git submodule init
          git submodule update
      - name: Install dependencies
        shell: powershell
        run: |
          Invoke-WebRequest -Uri "https://github.com/RahulVadhyar/Chronos/releases/download/CI/1.3.211.0.zip" -OutFile 1.3.211.0.zip
          Expand-Archive -Path 1.3.211.0.zip
          ls 1.3.211.0
          echo "VULKAN_SDK=$(pwd)\1.3.211.0\1.3.211.0\" >>${env:GITHUB_ENV}
      - uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            mingw-w64-x86_64-ninja
  
      - name: Put MSYS2_MinGW64 on PATH
        run: echo "D:/a/_temp/msys64/mingw64/bin" >> $GITHUB_PATH
      - name: Configure CMake
        run: >
          cmake -B build -S .
  
      - name: Build
        run: cmake --build build --parallel
        
  build-linux-gcc:
    name: Linux (GCC)
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-24.04, ubuntu-22.04]
    env:
      CC: gcc
      CXX: g++
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies and get git submodules
        run: |
          sudo apt install -y libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libxext-dev libwayland-dev libxkbcommon-dev libvulkan-dev libglm-dev gcc-multilib g++-multilib libfreetype6-dev libglu1-mesa-dev freeglut3-dev mesa-common-dev
          git submodule init
          git submodule update
           
      - name: Configure CMake
        run: >
          cmake -B build -S .
  
      - name: Build
        run: cmake --build build --parallel
  
      # - name: Test
      #   working-directory: build
      #   run: ctest --rerun-failed --output-on-failure
      
  build-linux-clang:
    name: Linux (Clang)
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-24.04, ubuntu-22.04, ubuntu-20.04]
    env:
      CC: clang
      CXX: clang++
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies and get git submodules
      run: |
        sudo apt update
        sudo apt install -y libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libxext-dev libwayland-dev libxkbcommon-dev libvulkan-dev libglm-dev gcc-multilib g++-multilib libfreetype6-dev libglu1-mesa-dev freeglut3-dev mesa-common-dev
        sudo apt install -y ninja-build
        git submodule init
        git submodule update
         
    - name: Configure CMake
      run: >
        cmake -B build -S . -GNinja

    - name: Build
      run: cmake --build build --parallel

    # - name: Test
    #   working-directory: build
    #   run: ctest --rerun-failed --output-on-failure
